// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/customsearchengine"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/user"
)

// CustomSearchEngineCreate is the builder for creating a CustomSearchEngine entity.
type CustomSearchEngineCreate struct {
	config
	mutation *CustomSearchEngineMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (csec *CustomSearchEngineCreate) SetUserID(i int64) *CustomSearchEngineCreate {
	csec.mutation.SetUserID(i)
	return csec
}

// SetDomain sets the "domain" field.
func (csec *CustomSearchEngineCreate) SetDomain(s string) *CustomSearchEngineCreate {
	csec.mutation.SetDomain(s)
	return csec
}

// SetName sets the "name" field.
func (csec *CustomSearchEngineCreate) SetName(s string) *CustomSearchEngineCreate {
	csec.mutation.SetName(s)
	return csec
}

// SetCreatedAt sets the "created_at" field.
func (csec *CustomSearchEngineCreate) SetCreatedAt(t time.Time) *CustomSearchEngineCreate {
	csec.mutation.SetCreatedAt(t)
	return csec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (csec *CustomSearchEngineCreate) SetNillableCreatedAt(t *time.Time) *CustomSearchEngineCreate {
	if t != nil {
		csec.SetCreatedAt(*t)
	}
	return csec
}

// SetUpdatedAt sets the "updated_at" field.
func (csec *CustomSearchEngineCreate) SetUpdatedAt(t time.Time) *CustomSearchEngineCreate {
	csec.mutation.SetUpdatedAt(t)
	return csec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (csec *CustomSearchEngineCreate) SetNillableUpdatedAt(t *time.Time) *CustomSearchEngineCreate {
	if t != nil {
		csec.SetUpdatedAt(*t)
	}
	return csec
}

// SetID sets the "id" field.
func (csec *CustomSearchEngineCreate) SetID(i int64) *CustomSearchEngineCreate {
	csec.mutation.SetID(i)
	return csec
}

// SetUser sets the "user" edge to the User entity.
func (csec *CustomSearchEngineCreate) SetUser(u *User) *CustomSearchEngineCreate {
	return csec.SetUserID(u.ID)
}

// Mutation returns the CustomSearchEngineMutation object of the builder.
func (csec *CustomSearchEngineCreate) Mutation() *CustomSearchEngineMutation {
	return csec.mutation
}

// Save creates the CustomSearchEngine in the database.
func (csec *CustomSearchEngineCreate) Save(ctx context.Context) (*CustomSearchEngine, error) {
	csec.defaults()
	return withHooks(ctx, csec.sqlSave, csec.mutation, csec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (csec *CustomSearchEngineCreate) SaveX(ctx context.Context) *CustomSearchEngine {
	v, err := csec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (csec *CustomSearchEngineCreate) Exec(ctx context.Context) error {
	_, err := csec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (csec *CustomSearchEngineCreate) ExecX(ctx context.Context) {
	if err := csec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (csec *CustomSearchEngineCreate) defaults() {
	if _, ok := csec.mutation.CreatedAt(); !ok {
		v := customsearchengine.DefaultCreatedAt()
		csec.mutation.SetCreatedAt(v)
	}
	if _, ok := csec.mutation.UpdatedAt(); !ok {
		v := customsearchengine.DefaultUpdatedAt()
		csec.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (csec *CustomSearchEngineCreate) check() error {
	if _, ok := csec.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CustomSearchEngine.user_id"`)}
	}
	if _, ok := csec.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "CustomSearchEngine.domain"`)}
	}
	if v, ok := csec.mutation.Domain(); ok {
		if err := customsearchengine.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "CustomSearchEngine.domain": %w`, err)}
		}
	}
	if _, ok := csec.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CustomSearchEngine.name"`)}
	}
	if v, ok := csec.mutation.Name(); ok {
		if err := customsearchengine.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CustomSearchEngine.name": %w`, err)}
		}
	}
	if _, ok := csec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CustomSearchEngine.created_at"`)}
	}
	if _, ok := csec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CustomSearchEngine.updated_at"`)}
	}
	if len(csec.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "CustomSearchEngine.user"`)}
	}
	return nil
}

func (csec *CustomSearchEngineCreate) sqlSave(ctx context.Context) (*CustomSearchEngine, error) {
	if err := csec.check(); err != nil {
		return nil, err
	}
	_node, _spec := csec.createSpec()
	if err := sqlgraph.CreateNode(ctx, csec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	csec.mutation.id = &_node.ID
	csec.mutation.done = true
	return _node, nil
}

func (csec *CustomSearchEngineCreate) createSpec() (*CustomSearchEngine, *sqlgraph.CreateSpec) {
	var (
		_node = &CustomSearchEngine{config: csec.config}
		_spec = sqlgraph.NewCreateSpec(customsearchengine.Table, sqlgraph.NewFieldSpec(customsearchengine.FieldID, field.TypeInt64))
	)
	if id, ok := csec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := csec.mutation.Domain(); ok {
		_spec.SetField(customsearchengine.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := csec.mutation.Name(); ok {
		_spec.SetField(customsearchengine.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := csec.mutation.CreatedAt(); ok {
		_spec.SetField(customsearchengine.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := csec.mutation.UpdatedAt(); ok {
		_spec.SetField(customsearchengine.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := csec.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customsearchengine.UserTable,
			Columns: []string{customsearchengine.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CustomSearchEngineCreateBulk is the builder for creating many CustomSearchEngine entities in bulk.
type CustomSearchEngineCreateBulk struct {
	config
	err      error
	builders []*CustomSearchEngineCreate
}

// Save creates the CustomSearchEngine entities in the database.
func (csecb *CustomSearchEngineCreateBulk) Save(ctx context.Context) ([]*CustomSearchEngine, error) {
	if csecb.err != nil {
		return nil, csecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(csecb.builders))
	nodes := make([]*CustomSearchEngine, len(csecb.builders))
	mutators := make([]Mutator, len(csecb.builders))
	for i := range csecb.builders {
		func(i int, root context.Context) {
			builder := csecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CustomSearchEngineMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, csecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, csecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, csecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (csecb *CustomSearchEngineCreateBulk) SaveX(ctx context.Context) []*CustomSearchEngine {
	v, err := csecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (csecb *CustomSearchEngineCreateBulk) Exec(ctx context.Context) error {
	_, err := csecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (csecb *CustomSearchEngineCreateBulk) ExecX(ctx context.Context) {
	if err := csecb.Exec(ctx); err != nil {
		panic(err)
	}
}
