// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/funnel"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/funnelstep"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/goal"
)

// FunnelStep is the model entity for the FunnelStep schema.
type FunnelStep struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// FunnelID holds the value of the "funnel_id" field.
	FunnelID int64 `json:"funnel_id,omitempty"`
	// GoalID holds the value of the "goal_id" field.
	GoalID int64 `json:"goal_id,omitempty"`
	// StepOrder holds the value of the "step_order" field.
	StepOrder int `json:"step_order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FunnelStepQuery when eager-loading is set.
	Edges        FunnelStepEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FunnelStepEdges holds the relations/edges for other nodes in the graph.
type FunnelStepEdges struct {
	// Goals holds the value of the goals edge.
	Goals *Goal `json:"goals,omitempty"`
	// Funnels holds the value of the funnels edge.
	Funnels *Funnel `json:"funnels,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GoalsOrErr returns the Goals value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FunnelStepEdges) GoalsOrErr() (*Goal, error) {
	if e.Goals != nil {
		return e.Goals, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: goal.Label}
	}
	return nil, &NotLoadedError{edge: "goals"}
}

// FunnelsOrErr returns the Funnels value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FunnelStepEdges) FunnelsOrErr() (*Funnel, error) {
	if e.Funnels != nil {
		return e.Funnels, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: funnel.Label}
	}
	return nil, &NotLoadedError{edge: "funnels"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FunnelStep) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case funnelstep.FieldID, funnelstep.FieldFunnelID, funnelstep.FieldGoalID, funnelstep.FieldStepOrder:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FunnelStep fields.
func (fs *FunnelStep) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case funnelstep.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			fs.ID = int64(value.Int64)
		case funnelstep.FieldFunnelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field funnel_id", values[i])
			} else if value.Valid {
				fs.FunnelID = value.Int64
			}
		case funnelstep.FieldGoalID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field goal_id", values[i])
			} else if value.Valid {
				fs.GoalID = value.Int64
			}
		case funnelstep.FieldStepOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field step_order", values[i])
			} else if value.Valid {
				fs.StepOrder = int(value.Int64)
			}
		default:
			fs.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FunnelStep.
// This includes values selected through modifiers, order, etc.
func (fs *FunnelStep) Value(name string) (ent.Value, error) {
	return fs.selectValues.Get(name)
}

// QueryGoals queries the "goals" edge of the FunnelStep entity.
func (fs *FunnelStep) QueryGoals() *GoalQuery {
	return NewFunnelStepClient(fs.config).QueryGoals(fs)
}

// QueryFunnels queries the "funnels" edge of the FunnelStep entity.
func (fs *FunnelStep) QueryFunnels() *FunnelQuery {
	return NewFunnelStepClient(fs.config).QueryFunnels(fs)
}

// Update returns a builder for updating this FunnelStep.
// Note that you need to call FunnelStep.Unwrap() before calling this method if this FunnelStep
// was returned from a transaction, and the transaction was committed or rolled back.
func (fs *FunnelStep) Update() *FunnelStepUpdateOne {
	return NewFunnelStepClient(fs.config).UpdateOne(fs)
}

// Unwrap unwraps the FunnelStep entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (fs *FunnelStep) Unwrap() *FunnelStep {
	_tx, ok := fs.config.driver.(*txDriver)
	if !ok {
		panic("ent: FunnelStep is not a transactional entity")
	}
	fs.config.driver = _tx.drv
	return fs
}

// String implements the fmt.Stringer.
func (fs *FunnelStep) String() string {
	var builder strings.Builder
	builder.WriteString("FunnelStep(")
	builder.WriteString(fmt.Sprintf("id=%v, ", fs.ID))
	builder.WriteString("funnel_id=")
	builder.WriteString(fmt.Sprintf("%v", fs.FunnelID))
	builder.WriteString(", ")
	builder.WriteString("goal_id=")
	builder.WriteString(fmt.Sprintf("%v", fs.GoalID))
	builder.WriteString(", ")
	builder.WriteString("step_order=")
	builder.WriteString(fmt.Sprintf("%v", fs.StepOrder))
	builder.WriteByte(')')
	return builder.String()
}

// FunnelSteps is a parsable slice of FunnelStep.
type FunnelSteps []*FunnelStep
