// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/funnelstep"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/goal"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/site"
)

// GoalCreate is the builder for creating a Goal entity.
type GoalCreate struct {
	config
	mutation *GoalMutation
	hooks    []Hook
}

// SetSiteID sets the "site_id" field.
func (gc *GoalCreate) SetSiteID(i int64) *GoalCreate {
	gc.mutation.SetSiteID(i)
	return gc
}

// SetEventName sets the "event_name" field.
func (gc *GoalCreate) SetEventName(s string) *GoalCreate {
	gc.mutation.SetEventName(s)
	return gc
}

// SetNillableEventName sets the "event_name" field if the given value is not nil.
func (gc *GoalCreate) SetNillableEventName(s *string) *GoalCreate {
	if s != nil {
		gc.SetEventName(*s)
	}
	return gc
}

// SetPagePath sets the "page_path" field.
func (gc *GoalCreate) SetPagePath(s string) *GoalCreate {
	gc.mutation.SetPagePath(s)
	return gc
}

// SetNillablePagePath sets the "page_path" field if the given value is not nil.
func (gc *GoalCreate) SetNillablePagePath(s *string) *GoalCreate {
	if s != nil {
		gc.SetPagePath(*s)
	}
	return gc
}

// SetDisplayName sets the "display_name" field.
func (gc *GoalCreate) SetDisplayName(s string) *GoalCreate {
	gc.mutation.SetDisplayName(s)
	return gc
}

// SetCustomProps sets the "custom_props" field.
func (gc *GoalCreate) SetCustomProps(m map[string]string) *GoalCreate {
	gc.mutation.SetCustomProps(m)
	return gc
}

// SetID sets the "id" field.
func (gc *GoalCreate) SetID(i int64) *GoalCreate {
	gc.mutation.SetID(i)
	return gc
}

// SetSite sets the "site" edge to the Site entity.
func (gc *GoalCreate) SetSite(s *Site) *GoalCreate {
	return gc.SetSiteID(s.ID)
}

// AddFunnelStepIDs adds the "funnel_steps" edge to the FunnelStep entity by IDs.
func (gc *GoalCreate) AddFunnelStepIDs(ids ...int64) *GoalCreate {
	gc.mutation.AddFunnelStepIDs(ids...)
	return gc
}

// AddFunnelSteps adds the "funnel_steps" edges to the FunnelStep entity.
func (gc *GoalCreate) AddFunnelSteps(f ...*FunnelStep) *GoalCreate {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return gc.AddFunnelStepIDs(ids...)
}

// Mutation returns the GoalMutation object of the builder.
func (gc *GoalCreate) Mutation() *GoalMutation {
	return gc.mutation
}

// Save creates the Goal in the database.
func (gc *GoalCreate) Save(ctx context.Context) (*Goal, error) {
	return withHooks(ctx, gc.sqlSave, gc.mutation, gc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (gc *GoalCreate) SaveX(ctx context.Context) *Goal {
	v, err := gc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gc *GoalCreate) Exec(ctx context.Context) error {
	_, err := gc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gc *GoalCreate) ExecX(ctx context.Context) {
	if err := gc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gc *GoalCreate) check() error {
	if _, ok := gc.mutation.SiteID(); !ok {
		return &ValidationError{Name: "site_id", err: errors.New(`ent: missing required field "Goal.site_id"`)}
	}
	if _, ok := gc.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "Goal.display_name"`)}
	}
	if len(gc.mutation.SiteIDs()) == 0 {
		return &ValidationError{Name: "site", err: errors.New(`ent: missing required edge "Goal.site"`)}
	}
	return nil
}

func (gc *GoalCreate) sqlSave(ctx context.Context) (*Goal, error) {
	if err := gc.check(); err != nil {
		return nil, err
	}
	_node, _spec := gc.createSpec()
	if err := sqlgraph.CreateNode(ctx, gc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	gc.mutation.id = &_node.ID
	gc.mutation.done = true
	return _node, nil
}

func (gc *GoalCreate) createSpec() (*Goal, *sqlgraph.CreateSpec) {
	var (
		_node = &Goal{config: gc.config}
		_spec = sqlgraph.NewCreateSpec(goal.Table, sqlgraph.NewFieldSpec(goal.FieldID, field.TypeInt64))
	)
	if id, ok := gc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := gc.mutation.EventName(); ok {
		_spec.SetField(goal.FieldEventName, field.TypeString, value)
		_node.EventName = value
	}
	if value, ok := gc.mutation.PagePath(); ok {
		_spec.SetField(goal.FieldPagePath, field.TypeString, value)
		_node.PagePath = value
	}
	if value, ok := gc.mutation.DisplayName(); ok {
		_spec.SetField(goal.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := gc.mutation.CustomProps(); ok {
		_spec.SetField(goal.FieldCustomProps, field.TypeJSON, value)
		_node.CustomProps = value
	}
	if nodes := gc.mutation.SiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goal.SiteTable,
			Columns: []string{goal.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SiteID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := gc.mutation.FunnelStepsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   goal.FunnelStepsTable,
			Columns: []string{goal.FunnelStepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(funnelstep.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GoalCreateBulk is the builder for creating many Goal entities in bulk.
type GoalCreateBulk struct {
	config
	err      error
	builders []*GoalCreate
}

// Save creates the Goal entities in the database.
func (gcb *GoalCreateBulk) Save(ctx context.Context) ([]*Goal, error) {
	if gcb.err != nil {
		return nil, gcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(gcb.builders))
	nodes := make([]*Goal, len(gcb.builders))
	mutators := make([]Mutator, len(gcb.builders))
	for i := range gcb.builders {
		func(i int, root context.Context) {
			builder := gcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GoalMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gcb *GoalCreateBulk) SaveX(ctx context.Context) []*Goal {
	v, err := gcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gcb *GoalCreateBulk) Exec(ctx context.Context) error {
	_, err := gcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gcb *GoalCreateBulk) ExecX(ctx context.Context) {
	if err := gcb.Exec(ctx); err != nil {
		panic(err)
	}
}
