// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/funnelstep"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/goal"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/predicate"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/site"
)

// GoalUpdate is the builder for updating Goal entities.
type GoalUpdate struct {
	config
	hooks    []Hook
	mutation *GoalMutation
}

// Where appends a list predicates to the GoalUpdate builder.
func (gu *GoalUpdate) Where(ps ...predicate.Goal) *GoalUpdate {
	gu.mutation.Where(ps...)
	return gu
}

// SetSiteID sets the "site_id" field.
func (gu *GoalUpdate) SetSiteID(i int64) *GoalUpdate {
	gu.mutation.SetSiteID(i)
	return gu
}

// SetNillableSiteID sets the "site_id" field if the given value is not nil.
func (gu *GoalUpdate) SetNillableSiteID(i *int64) *GoalUpdate {
	if i != nil {
		gu.SetSiteID(*i)
	}
	return gu
}

// SetEventName sets the "event_name" field.
func (gu *GoalUpdate) SetEventName(s string) *GoalUpdate {
	gu.mutation.SetEventName(s)
	return gu
}

// SetNillableEventName sets the "event_name" field if the given value is not nil.
func (gu *GoalUpdate) SetNillableEventName(s *string) *GoalUpdate {
	if s != nil {
		gu.SetEventName(*s)
	}
	return gu
}

// ClearEventName clears the value of the "event_name" field.
func (gu *GoalUpdate) ClearEventName() *GoalUpdate {
	gu.mutation.ClearEventName()
	return gu
}

// SetPagePath sets the "page_path" field.
func (gu *GoalUpdate) SetPagePath(s string) *GoalUpdate {
	gu.mutation.SetPagePath(s)
	return gu
}

// SetNillablePagePath sets the "page_path" field if the given value is not nil.
func (gu *GoalUpdate) SetNillablePagePath(s *string) *GoalUpdate {
	if s != nil {
		gu.SetPagePath(*s)
	}
	return gu
}

// ClearPagePath clears the value of the "page_path" field.
func (gu *GoalUpdate) ClearPagePath() *GoalUpdate {
	gu.mutation.ClearPagePath()
	return gu
}

// SetDisplayName sets the "display_name" field.
func (gu *GoalUpdate) SetDisplayName(s string) *GoalUpdate {
	gu.mutation.SetDisplayName(s)
	return gu
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (gu *GoalUpdate) SetNillableDisplayName(s *string) *GoalUpdate {
	if s != nil {
		gu.SetDisplayName(*s)
	}
	return gu
}

// SetCustomProps sets the "custom_props" field.
func (gu *GoalUpdate) SetCustomProps(m map[string]string) *GoalUpdate {
	gu.mutation.SetCustomProps(m)
	return gu
}

// ClearCustomProps clears the value of the "custom_props" field.
func (gu *GoalUpdate) ClearCustomProps() *GoalUpdate {
	gu.mutation.ClearCustomProps()
	return gu
}

// SetSite sets the "site" edge to the Site entity.
func (gu *GoalUpdate) SetSite(s *Site) *GoalUpdate {
	return gu.SetSiteID(s.ID)
}

// AddFunnelStepIDs adds the "funnel_steps" edge to the FunnelStep entity by IDs.
func (gu *GoalUpdate) AddFunnelStepIDs(ids ...int64) *GoalUpdate {
	gu.mutation.AddFunnelStepIDs(ids...)
	return gu
}

// AddFunnelSteps adds the "funnel_steps" edges to the FunnelStep entity.
func (gu *GoalUpdate) AddFunnelSteps(f ...*FunnelStep) *GoalUpdate {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return gu.AddFunnelStepIDs(ids...)
}

// Mutation returns the GoalMutation object of the builder.
func (gu *GoalUpdate) Mutation() *GoalMutation {
	return gu.mutation
}

// ClearSite clears the "site" edge to the Site entity.
func (gu *GoalUpdate) ClearSite() *GoalUpdate {
	gu.mutation.ClearSite()
	return gu
}

// ClearFunnelSteps clears all "funnel_steps" edges to the FunnelStep entity.
func (gu *GoalUpdate) ClearFunnelSteps() *GoalUpdate {
	gu.mutation.ClearFunnelSteps()
	return gu
}

// RemoveFunnelStepIDs removes the "funnel_steps" edge to FunnelStep entities by IDs.
func (gu *GoalUpdate) RemoveFunnelStepIDs(ids ...int64) *GoalUpdate {
	gu.mutation.RemoveFunnelStepIDs(ids...)
	return gu
}

// RemoveFunnelSteps removes "funnel_steps" edges to FunnelStep entities.
func (gu *GoalUpdate) RemoveFunnelSteps(f ...*FunnelStep) *GoalUpdate {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return gu.RemoveFunnelStepIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (gu *GoalUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, gu.sqlSave, gu.mutation, gu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (gu *GoalUpdate) SaveX(ctx context.Context) int {
	affected, err := gu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (gu *GoalUpdate) Exec(ctx context.Context) error {
	_, err := gu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gu *GoalUpdate) ExecX(ctx context.Context) {
	if err := gu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gu *GoalUpdate) check() error {
	if gu.mutation.SiteCleared() && len(gu.mutation.SiteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Goal.site"`)
	}
	return nil
}

func (gu *GoalUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := gu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(goal.Table, goal.Columns, sqlgraph.NewFieldSpec(goal.FieldID, field.TypeInt64))
	if ps := gu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := gu.mutation.EventName(); ok {
		_spec.SetField(goal.FieldEventName, field.TypeString, value)
	}
	if gu.mutation.EventNameCleared() {
		_spec.ClearField(goal.FieldEventName, field.TypeString)
	}
	if value, ok := gu.mutation.PagePath(); ok {
		_spec.SetField(goal.FieldPagePath, field.TypeString, value)
	}
	if gu.mutation.PagePathCleared() {
		_spec.ClearField(goal.FieldPagePath, field.TypeString)
	}
	if value, ok := gu.mutation.DisplayName(); ok {
		_spec.SetField(goal.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := gu.mutation.CustomProps(); ok {
		_spec.SetField(goal.FieldCustomProps, field.TypeJSON, value)
	}
	if gu.mutation.CustomPropsCleared() {
		_spec.ClearField(goal.FieldCustomProps, field.TypeJSON)
	}
	if gu.mutation.SiteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goal.SiteTable,
			Columns: []string{goal.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := gu.mutation.SiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goal.SiteTable,
			Columns: []string{goal.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if gu.mutation.FunnelStepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   goal.FunnelStepsTable,
			Columns: []string{goal.FunnelStepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(funnelstep.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := gu.mutation.RemovedFunnelStepsIDs(); len(nodes) > 0 && !gu.mutation.FunnelStepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   goal.FunnelStepsTable,
			Columns: []string{goal.FunnelStepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(funnelstep.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := gu.mutation.FunnelStepsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   goal.FunnelStepsTable,
			Columns: []string{goal.FunnelStepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(funnelstep.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, gu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{goal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	gu.mutation.done = true
	return n, nil
}

// GoalUpdateOne is the builder for updating a single Goal entity.
type GoalUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GoalMutation
}

// SetSiteID sets the "site_id" field.
func (guo *GoalUpdateOne) SetSiteID(i int64) *GoalUpdateOne {
	guo.mutation.SetSiteID(i)
	return guo
}

// SetNillableSiteID sets the "site_id" field if the given value is not nil.
func (guo *GoalUpdateOne) SetNillableSiteID(i *int64) *GoalUpdateOne {
	if i != nil {
		guo.SetSiteID(*i)
	}
	return guo
}

// SetEventName sets the "event_name" field.
func (guo *GoalUpdateOne) SetEventName(s string) *GoalUpdateOne {
	guo.mutation.SetEventName(s)
	return guo
}

// SetNillableEventName sets the "event_name" field if the given value is not nil.
func (guo *GoalUpdateOne) SetNillableEventName(s *string) *GoalUpdateOne {
	if s != nil {
		guo.SetEventName(*s)
	}
	return guo
}

// ClearEventName clears the value of the "event_name" field.
func (guo *GoalUpdateOne) ClearEventName() *GoalUpdateOne {
	guo.mutation.ClearEventName()
	return guo
}

// SetPagePath sets the "page_path" field.
func (guo *GoalUpdateOne) SetPagePath(s string) *GoalUpdateOne {
	guo.mutation.SetPagePath(s)
	return guo
}

// SetNillablePagePath sets the "page_path" field if the given value is not nil.
func (guo *GoalUpdateOne) SetNillablePagePath(s *string) *GoalUpdateOne {
	if s != nil {
		guo.SetPagePath(*s)
	}
	return guo
}

// ClearPagePath clears the value of the "page_path" field.
func (guo *GoalUpdateOne) ClearPagePath() *GoalUpdateOne {
	guo.mutation.ClearPagePath()
	return guo
}

// SetDisplayName sets the "display_name" field.
func (guo *GoalUpdateOne) SetDisplayName(s string) *GoalUpdateOne {
	guo.mutation.SetDisplayName(s)
	return guo
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (guo *GoalUpdateOne) SetNillableDisplayName(s *string) *GoalUpdateOne {
	if s != nil {
		guo.SetDisplayName(*s)
	}
	return guo
}

// SetCustomProps sets the "custom_props" field.
func (guo *GoalUpdateOne) SetCustomProps(m map[string]string) *GoalUpdateOne {
	guo.mutation.SetCustomProps(m)
	return guo
}

// ClearCustomProps clears the value of the "custom_props" field.
func (guo *GoalUpdateOne) ClearCustomProps() *GoalUpdateOne {
	guo.mutation.ClearCustomProps()
	return guo
}

// SetSite sets the "site" edge to the Site entity.
func (guo *GoalUpdateOne) SetSite(s *Site) *GoalUpdateOne {
	return guo.SetSiteID(s.ID)
}

// AddFunnelStepIDs adds the "funnel_steps" edge to the FunnelStep entity by IDs.
func (guo *GoalUpdateOne) AddFunnelStepIDs(ids ...int64) *GoalUpdateOne {
	guo.mutation.AddFunnelStepIDs(ids...)
	return guo
}

// AddFunnelSteps adds the "funnel_steps" edges to the FunnelStep entity.
func (guo *GoalUpdateOne) AddFunnelSteps(f ...*FunnelStep) *GoalUpdateOne {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return guo.AddFunnelStepIDs(ids...)
}

// Mutation returns the GoalMutation object of the builder.
func (guo *GoalUpdateOne) Mutation() *GoalMutation {
	return guo.mutation
}

// ClearSite clears the "site" edge to the Site entity.
func (guo *GoalUpdateOne) ClearSite() *GoalUpdateOne {
	guo.mutation.ClearSite()
	return guo
}

// ClearFunnelSteps clears all "funnel_steps" edges to the FunnelStep entity.
func (guo *GoalUpdateOne) ClearFunnelSteps() *GoalUpdateOne {
	guo.mutation.ClearFunnelSteps()
	return guo
}

// RemoveFunnelStepIDs removes the "funnel_steps" edge to FunnelStep entities by IDs.
func (guo *GoalUpdateOne) RemoveFunnelStepIDs(ids ...int64) *GoalUpdateOne {
	guo.mutation.RemoveFunnelStepIDs(ids...)
	return guo
}

// RemoveFunnelSteps removes "funnel_steps" edges to FunnelStep entities.
func (guo *GoalUpdateOne) RemoveFunnelSteps(f ...*FunnelStep) *GoalUpdateOne {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return guo.RemoveFunnelStepIDs(ids...)
}

// Where appends a list predicates to the GoalUpdate builder.
func (guo *GoalUpdateOne) Where(ps ...predicate.Goal) *GoalUpdateOne {
	guo.mutation.Where(ps...)
	return guo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (guo *GoalUpdateOne) Select(field string, fields ...string) *GoalUpdateOne {
	guo.fields = append([]string{field}, fields...)
	return guo
}

// Save executes the query and returns the updated Goal entity.
func (guo *GoalUpdateOne) Save(ctx context.Context) (*Goal, error) {
	return withHooks(ctx, guo.sqlSave, guo.mutation, guo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (guo *GoalUpdateOne) SaveX(ctx context.Context) *Goal {
	node, err := guo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (guo *GoalUpdateOne) Exec(ctx context.Context) error {
	_, err := guo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (guo *GoalUpdateOne) ExecX(ctx context.Context) {
	if err := guo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (guo *GoalUpdateOne) check() error {
	if guo.mutation.SiteCleared() && len(guo.mutation.SiteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Goal.site"`)
	}
	return nil
}

func (guo *GoalUpdateOne) sqlSave(ctx context.Context) (_node *Goal, err error) {
	if err := guo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(goal.Table, goal.Columns, sqlgraph.NewFieldSpec(goal.FieldID, field.TypeInt64))
	id, ok := guo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Goal.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := guo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, goal.FieldID)
		for _, f := range fields {
			if !goal.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != goal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := guo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := guo.mutation.EventName(); ok {
		_spec.SetField(goal.FieldEventName, field.TypeString, value)
	}
	if guo.mutation.EventNameCleared() {
		_spec.ClearField(goal.FieldEventName, field.TypeString)
	}
	if value, ok := guo.mutation.PagePath(); ok {
		_spec.SetField(goal.FieldPagePath, field.TypeString, value)
	}
	if guo.mutation.PagePathCleared() {
		_spec.ClearField(goal.FieldPagePath, field.TypeString)
	}
	if value, ok := guo.mutation.DisplayName(); ok {
		_spec.SetField(goal.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := guo.mutation.CustomProps(); ok {
		_spec.SetField(goal.FieldCustomProps, field.TypeJSON, value)
	}
	if guo.mutation.CustomPropsCleared() {
		_spec.ClearField(goal.FieldCustomProps, field.TypeJSON)
	}
	if guo.mutation.SiteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goal.SiteTable,
			Columns: []string{goal.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := guo.mutation.SiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goal.SiteTable,
			Columns: []string{goal.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if guo.mutation.FunnelStepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   goal.FunnelStepsTable,
			Columns: []string{goal.FunnelStepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(funnelstep.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := guo.mutation.RemovedFunnelStepsIDs(); len(nodes) > 0 && !guo.mutation.FunnelStepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   goal.FunnelStepsTable,
			Columns: []string{goal.FunnelStepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(funnelstep.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := guo.mutation.FunnelStepsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   goal.FunnelStepsTable,
			Columns: []string{goal.FunnelStepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(funnelstep.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Goal{config: guo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, guo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{goal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	guo.mutation.done = true
	return _node, nil
}
