// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/monthlyeventcount"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/predicate"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/user"
)

// MonthlyEventCountQuery is the builder for querying MonthlyEventCount entities.
type MonthlyEventCountQuery struct {
	config
	ctx        *QueryContext
	order      []monthlyeventcount.OrderOption
	inters     []Interceptor
	predicates []predicate.MonthlyEventCount
	withUser   *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MonthlyEventCountQuery builder.
func (mecq *MonthlyEventCountQuery) Where(ps ...predicate.MonthlyEventCount) *MonthlyEventCountQuery {
	mecq.predicates = append(mecq.predicates, ps...)
	return mecq
}

// Limit the number of records to be returned by this query.
func (mecq *MonthlyEventCountQuery) Limit(limit int) *MonthlyEventCountQuery {
	mecq.ctx.Limit = &limit
	return mecq
}

// Offset to start from.
func (mecq *MonthlyEventCountQuery) Offset(offset int) *MonthlyEventCountQuery {
	mecq.ctx.Offset = &offset
	return mecq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mecq *MonthlyEventCountQuery) Unique(unique bool) *MonthlyEventCountQuery {
	mecq.ctx.Unique = &unique
	return mecq
}

// Order specifies how the records should be ordered.
func (mecq *MonthlyEventCountQuery) Order(o ...monthlyeventcount.OrderOption) *MonthlyEventCountQuery {
	mecq.order = append(mecq.order, o...)
	return mecq
}

// QueryUser chains the current query on the "user" edge.
func (mecq *MonthlyEventCountQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: mecq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mecq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mecq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(monthlyeventcount.Table, monthlyeventcount.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, monthlyeventcount.UserTable, monthlyeventcount.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(mecq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MonthlyEventCount entity from the query.
// Returns a *NotFoundError when no MonthlyEventCount was found.
func (mecq *MonthlyEventCountQuery) First(ctx context.Context) (*MonthlyEventCount, error) {
	nodes, err := mecq.Limit(1).All(setContextOp(ctx, mecq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{monthlyeventcount.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mecq *MonthlyEventCountQuery) FirstX(ctx context.Context) *MonthlyEventCount {
	node, err := mecq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MonthlyEventCount ID from the query.
// Returns a *NotFoundError when no MonthlyEventCount ID was found.
func (mecq *MonthlyEventCountQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = mecq.Limit(1).IDs(setContextOp(ctx, mecq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{monthlyeventcount.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mecq *MonthlyEventCountQuery) FirstIDX(ctx context.Context) int64 {
	id, err := mecq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MonthlyEventCount entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MonthlyEventCount entity is found.
// Returns a *NotFoundError when no MonthlyEventCount entities are found.
func (mecq *MonthlyEventCountQuery) Only(ctx context.Context) (*MonthlyEventCount, error) {
	nodes, err := mecq.Limit(2).All(setContextOp(ctx, mecq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{monthlyeventcount.Label}
	default:
		return nil, &NotSingularError{monthlyeventcount.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mecq *MonthlyEventCountQuery) OnlyX(ctx context.Context) *MonthlyEventCount {
	node, err := mecq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MonthlyEventCount ID in the query.
// Returns a *NotSingularError when more than one MonthlyEventCount ID is found.
// Returns a *NotFoundError when no entities are found.
func (mecq *MonthlyEventCountQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = mecq.Limit(2).IDs(setContextOp(ctx, mecq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{monthlyeventcount.Label}
	default:
		err = &NotSingularError{monthlyeventcount.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mecq *MonthlyEventCountQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := mecq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MonthlyEventCounts.
func (mecq *MonthlyEventCountQuery) All(ctx context.Context) ([]*MonthlyEventCount, error) {
	ctx = setContextOp(ctx, mecq.ctx, ent.OpQueryAll)
	if err := mecq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MonthlyEventCount, *MonthlyEventCountQuery]()
	return withInterceptors[[]*MonthlyEventCount](ctx, mecq, qr, mecq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mecq *MonthlyEventCountQuery) AllX(ctx context.Context) []*MonthlyEventCount {
	nodes, err := mecq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MonthlyEventCount IDs.
func (mecq *MonthlyEventCountQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if mecq.ctx.Unique == nil && mecq.path != nil {
		mecq.Unique(true)
	}
	ctx = setContextOp(ctx, mecq.ctx, ent.OpQueryIDs)
	if err = mecq.Select(monthlyeventcount.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mecq *MonthlyEventCountQuery) IDsX(ctx context.Context) []int64 {
	ids, err := mecq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mecq *MonthlyEventCountQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mecq.ctx, ent.OpQueryCount)
	if err := mecq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mecq, querierCount[*MonthlyEventCountQuery](), mecq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mecq *MonthlyEventCountQuery) CountX(ctx context.Context) int {
	count, err := mecq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mecq *MonthlyEventCountQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mecq.ctx, ent.OpQueryExist)
	switch _, err := mecq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mecq *MonthlyEventCountQuery) ExistX(ctx context.Context) bool {
	exist, err := mecq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MonthlyEventCountQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mecq *MonthlyEventCountQuery) Clone() *MonthlyEventCountQuery {
	if mecq == nil {
		return nil
	}
	return &MonthlyEventCountQuery{
		config:     mecq.config,
		ctx:        mecq.ctx.Clone(),
		order:      append([]monthlyeventcount.OrderOption{}, mecq.order...),
		inters:     append([]Interceptor{}, mecq.inters...),
		predicates: append([]predicate.MonthlyEventCount{}, mecq.predicates...),
		withUser:   mecq.withUser.Clone(),
		// clone intermediate query.
		sql:  mecq.sql.Clone(),
		path: mecq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (mecq *MonthlyEventCountQuery) WithUser(opts ...func(*UserQuery)) *MonthlyEventCountQuery {
	query := (&UserClient{config: mecq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mecq.withUser = query
	return mecq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MonthlyEventCount.Query().
//		GroupBy(monthlyeventcount.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mecq *MonthlyEventCountQuery) GroupBy(field string, fields ...string) *MonthlyEventCountGroupBy {
	mecq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MonthlyEventCountGroupBy{build: mecq}
	grbuild.flds = &mecq.ctx.Fields
	grbuild.label = monthlyeventcount.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//	}
//
//	client.MonthlyEventCount.Query().
//		Select(monthlyeventcount.FieldUserID).
//		Scan(ctx, &v)
func (mecq *MonthlyEventCountQuery) Select(fields ...string) *MonthlyEventCountSelect {
	mecq.ctx.Fields = append(mecq.ctx.Fields, fields...)
	sbuild := &MonthlyEventCountSelect{MonthlyEventCountQuery: mecq}
	sbuild.label = monthlyeventcount.Label
	sbuild.flds, sbuild.scan = &mecq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MonthlyEventCountSelect configured with the given aggregations.
func (mecq *MonthlyEventCountQuery) Aggregate(fns ...AggregateFunc) *MonthlyEventCountSelect {
	return mecq.Select().Aggregate(fns...)
}

func (mecq *MonthlyEventCountQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mecq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mecq); err != nil {
				return err
			}
		}
	}
	for _, f := range mecq.ctx.Fields {
		if !monthlyeventcount.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mecq.path != nil {
		prev, err := mecq.path(ctx)
		if err != nil {
			return err
		}
		mecq.sql = prev
	}
	return nil
}

func (mecq *MonthlyEventCountQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MonthlyEventCount, error) {
	var (
		nodes       = []*MonthlyEventCount{}
		_spec       = mecq.querySpec()
		loadedTypes = [1]bool{
			mecq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MonthlyEventCount).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MonthlyEventCount{config: mecq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mecq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mecq.withUser; query != nil {
		if err := mecq.loadUser(ctx, query, nodes, nil,
			func(n *MonthlyEventCount, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mecq *MonthlyEventCountQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*MonthlyEventCount, init func(*MonthlyEventCount), assign func(*MonthlyEventCount, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*MonthlyEventCount)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (mecq *MonthlyEventCountQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mecq.querySpec()
	_spec.Node.Columns = mecq.ctx.Fields
	if len(mecq.ctx.Fields) > 0 {
		_spec.Unique = mecq.ctx.Unique != nil && *mecq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mecq.driver, _spec)
}

func (mecq *MonthlyEventCountQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(monthlyeventcount.Table, monthlyeventcount.Columns, sqlgraph.NewFieldSpec(monthlyeventcount.FieldID, field.TypeInt64))
	_spec.From = mecq.sql
	if unique := mecq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mecq.path != nil {
		_spec.Unique = true
	}
	if fields := mecq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, monthlyeventcount.FieldID)
		for i := range fields {
			if fields[i] != monthlyeventcount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if mecq.withUser != nil {
			_spec.Node.AddColumnOnce(monthlyeventcount.FieldUserID)
		}
	}
	if ps := mecq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mecq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mecq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mecq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mecq *MonthlyEventCountQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mecq.driver.Dialect())
	t1 := builder.Table(monthlyeventcount.Table)
	columns := mecq.ctx.Fields
	if len(columns) == 0 {
		columns = monthlyeventcount.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mecq.sql != nil {
		selector = mecq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mecq.ctx.Unique != nil && *mecq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mecq.predicates {
		p(selector)
	}
	for _, p := range mecq.order {
		p(selector)
	}
	if offset := mecq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mecq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MonthlyEventCountGroupBy is the group-by builder for MonthlyEventCount entities.
type MonthlyEventCountGroupBy struct {
	selector
	build *MonthlyEventCountQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mecgb *MonthlyEventCountGroupBy) Aggregate(fns ...AggregateFunc) *MonthlyEventCountGroupBy {
	mecgb.fns = append(mecgb.fns, fns...)
	return mecgb
}

// Scan applies the selector query and scans the result into the given value.
func (mecgb *MonthlyEventCountGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mecgb.build.ctx, ent.OpQueryGroupBy)
	if err := mecgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MonthlyEventCountQuery, *MonthlyEventCountGroupBy](ctx, mecgb.build, mecgb, mecgb.build.inters, v)
}

func (mecgb *MonthlyEventCountGroupBy) sqlScan(ctx context.Context, root *MonthlyEventCountQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mecgb.fns))
	for _, fn := range mecgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mecgb.flds)+len(mecgb.fns))
		for _, f := range *mecgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mecgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mecgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MonthlyEventCountSelect is the builder for selecting fields of MonthlyEventCount entities.
type MonthlyEventCountSelect struct {
	*MonthlyEventCountQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mecs *MonthlyEventCountSelect) Aggregate(fns ...AggregateFunc) *MonthlyEventCountSelect {
	mecs.fns = append(mecs.fns, fns...)
	return mecs
}

// Scan applies the selector query and scans the result into the given value.
func (mecs *MonthlyEventCountSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mecs.ctx, ent.OpQuerySelect)
	if err := mecs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MonthlyEventCountQuery, *MonthlyEventCountSelect](ctx, mecs.MonthlyEventCountQuery, mecs, mecs.inters, v)
}

func (mecs *MonthlyEventCountSelect) sqlScan(ctx context.Context, root *MonthlyEventCountQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mecs.fns))
	for _, fn := range mecs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mecs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mecs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
