// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/passwordresettoken"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/user"
)

// PasswordResetToken is the model entity for the PasswordResetToken schema.
type PasswordResetToken struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 关联用户ID
	UserID int64 `json:"user_id,omitempty"`
	// 重置 token
	Token string `json:"token,omitempty"`
	// 用户邮箱
	Email string `json:"email,omitempty"`
	// 过期时间
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// 是否已使用
	Used bool `json:"used,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PasswordResetTokenQuery when eager-loading is set.
	Edges        PasswordResetTokenEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PasswordResetTokenEdges holds the relations/edges for other nodes in the graph.
type PasswordResetTokenEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PasswordResetTokenEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PasswordResetToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case passwordresettoken.FieldUsed:
			values[i] = new(sql.NullBool)
		case passwordresettoken.FieldID, passwordresettoken.FieldUserID:
			values[i] = new(sql.NullInt64)
		case passwordresettoken.FieldToken, passwordresettoken.FieldEmail:
			values[i] = new(sql.NullString)
		case passwordresettoken.FieldExpiresAt, passwordresettoken.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PasswordResetToken fields.
func (prt *PasswordResetToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case passwordresettoken.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			prt.ID = int64(value.Int64)
		case passwordresettoken.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				prt.UserID = value.Int64
			}
		case passwordresettoken.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				prt.Token = value.String
			}
		case passwordresettoken.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				prt.Email = value.String
			}
		case passwordresettoken.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				prt.ExpiresAt = value.Time
			}
		case passwordresettoken.FieldUsed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field used", values[i])
			} else if value.Valid {
				prt.Used = value.Bool
			}
		case passwordresettoken.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				prt.CreatedAt = value.Time
			}
		default:
			prt.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PasswordResetToken.
// This includes values selected through modifiers, order, etc.
func (prt *PasswordResetToken) Value(name string) (ent.Value, error) {
	return prt.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the PasswordResetToken entity.
func (prt *PasswordResetToken) QueryUser() *UserQuery {
	return NewPasswordResetTokenClient(prt.config).QueryUser(prt)
}

// Update returns a builder for updating this PasswordResetToken.
// Note that you need to call PasswordResetToken.Unwrap() before calling this method if this PasswordResetToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (prt *PasswordResetToken) Update() *PasswordResetTokenUpdateOne {
	return NewPasswordResetTokenClient(prt.config).UpdateOne(prt)
}

// Unwrap unwraps the PasswordResetToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (prt *PasswordResetToken) Unwrap() *PasswordResetToken {
	_tx, ok := prt.config.driver.(*txDriver)
	if !ok {
		panic("ent: PasswordResetToken is not a transactional entity")
	}
	prt.config.driver = _tx.drv
	return prt
}

// String implements the fmt.Stringer.
func (prt *PasswordResetToken) String() string {
	var builder strings.Builder
	builder.WriteString("PasswordResetToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", prt.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", prt.UserID))
	builder.WriteString(", ")
	builder.WriteString("token=")
	builder.WriteString(prt.Token)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(prt.Email)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(prt.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("used=")
	builder.WriteString(fmt.Sprintf("%v", prt.Used))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(prt.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PasswordResetTokens is a parsable slice of PasswordResetToken.
type PasswordResetTokens []*PasswordResetToken
