// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/passwordresettoken"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/predicate"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/user"
)

// PasswordResetTokenUpdate is the builder for updating PasswordResetToken entities.
type PasswordResetTokenUpdate struct {
	config
	hooks    []Hook
	mutation *PasswordResetTokenMutation
}

// Where appends a list predicates to the PasswordResetTokenUpdate builder.
func (prtu *PasswordResetTokenUpdate) Where(ps ...predicate.PasswordResetToken) *PasswordResetTokenUpdate {
	prtu.mutation.Where(ps...)
	return prtu
}

// SetUserID sets the "user_id" field.
func (prtu *PasswordResetTokenUpdate) SetUserID(i int64) *PasswordResetTokenUpdate {
	prtu.mutation.SetUserID(i)
	return prtu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (prtu *PasswordResetTokenUpdate) SetNillableUserID(i *int64) *PasswordResetTokenUpdate {
	if i != nil {
		prtu.SetUserID(*i)
	}
	return prtu
}

// SetToken sets the "token" field.
func (prtu *PasswordResetTokenUpdate) SetToken(s string) *PasswordResetTokenUpdate {
	prtu.mutation.SetToken(s)
	return prtu
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (prtu *PasswordResetTokenUpdate) SetNillableToken(s *string) *PasswordResetTokenUpdate {
	if s != nil {
		prtu.SetToken(*s)
	}
	return prtu
}

// SetEmail sets the "email" field.
func (prtu *PasswordResetTokenUpdate) SetEmail(s string) *PasswordResetTokenUpdate {
	prtu.mutation.SetEmail(s)
	return prtu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (prtu *PasswordResetTokenUpdate) SetNillableEmail(s *string) *PasswordResetTokenUpdate {
	if s != nil {
		prtu.SetEmail(*s)
	}
	return prtu
}

// SetExpiresAt sets the "expires_at" field.
func (prtu *PasswordResetTokenUpdate) SetExpiresAt(t time.Time) *PasswordResetTokenUpdate {
	prtu.mutation.SetExpiresAt(t)
	return prtu
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (prtu *PasswordResetTokenUpdate) SetNillableExpiresAt(t *time.Time) *PasswordResetTokenUpdate {
	if t != nil {
		prtu.SetExpiresAt(*t)
	}
	return prtu
}

// SetUsed sets the "used" field.
func (prtu *PasswordResetTokenUpdate) SetUsed(b bool) *PasswordResetTokenUpdate {
	prtu.mutation.SetUsed(b)
	return prtu
}

// SetNillableUsed sets the "used" field if the given value is not nil.
func (prtu *PasswordResetTokenUpdate) SetNillableUsed(b *bool) *PasswordResetTokenUpdate {
	if b != nil {
		prtu.SetUsed(*b)
	}
	return prtu
}

// SetUser sets the "user" edge to the User entity.
func (prtu *PasswordResetTokenUpdate) SetUser(u *User) *PasswordResetTokenUpdate {
	return prtu.SetUserID(u.ID)
}

// Mutation returns the PasswordResetTokenMutation object of the builder.
func (prtu *PasswordResetTokenUpdate) Mutation() *PasswordResetTokenMutation {
	return prtu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (prtu *PasswordResetTokenUpdate) ClearUser() *PasswordResetTokenUpdate {
	prtu.mutation.ClearUser()
	return prtu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (prtu *PasswordResetTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, prtu.sqlSave, prtu.mutation, prtu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (prtu *PasswordResetTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := prtu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (prtu *PasswordResetTokenUpdate) Exec(ctx context.Context) error {
	_, err := prtu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (prtu *PasswordResetTokenUpdate) ExecX(ctx context.Context) {
	if err := prtu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (prtu *PasswordResetTokenUpdate) check() error {
	if v, ok := prtu.mutation.Token(); ok {
		if err := passwordresettoken.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "PasswordResetToken.token": %w`, err)}
		}
	}
	if v, ok := prtu.mutation.Email(); ok {
		if err := passwordresettoken.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "PasswordResetToken.email": %w`, err)}
		}
	}
	if prtu.mutation.UserCleared() && len(prtu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PasswordResetToken.user"`)
	}
	return nil
}

func (prtu *PasswordResetTokenUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := prtu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(passwordresettoken.Table, passwordresettoken.Columns, sqlgraph.NewFieldSpec(passwordresettoken.FieldID, field.TypeInt64))
	if ps := prtu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := prtu.mutation.Token(); ok {
		_spec.SetField(passwordresettoken.FieldToken, field.TypeString, value)
	}
	if value, ok := prtu.mutation.Email(); ok {
		_spec.SetField(passwordresettoken.FieldEmail, field.TypeString, value)
	}
	if value, ok := prtu.mutation.ExpiresAt(); ok {
		_spec.SetField(passwordresettoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := prtu.mutation.Used(); ok {
		_spec.SetField(passwordresettoken.FieldUsed, field.TypeBool, value)
	}
	if prtu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   passwordresettoken.UserTable,
			Columns: []string{passwordresettoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := prtu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   passwordresettoken.UserTable,
			Columns: []string{passwordresettoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, prtu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{passwordresettoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	prtu.mutation.done = true
	return n, nil
}

// PasswordResetTokenUpdateOne is the builder for updating a single PasswordResetToken entity.
type PasswordResetTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PasswordResetTokenMutation
}

// SetUserID sets the "user_id" field.
func (prtuo *PasswordResetTokenUpdateOne) SetUserID(i int64) *PasswordResetTokenUpdateOne {
	prtuo.mutation.SetUserID(i)
	return prtuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (prtuo *PasswordResetTokenUpdateOne) SetNillableUserID(i *int64) *PasswordResetTokenUpdateOne {
	if i != nil {
		prtuo.SetUserID(*i)
	}
	return prtuo
}

// SetToken sets the "token" field.
func (prtuo *PasswordResetTokenUpdateOne) SetToken(s string) *PasswordResetTokenUpdateOne {
	prtuo.mutation.SetToken(s)
	return prtuo
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (prtuo *PasswordResetTokenUpdateOne) SetNillableToken(s *string) *PasswordResetTokenUpdateOne {
	if s != nil {
		prtuo.SetToken(*s)
	}
	return prtuo
}

// SetEmail sets the "email" field.
func (prtuo *PasswordResetTokenUpdateOne) SetEmail(s string) *PasswordResetTokenUpdateOne {
	prtuo.mutation.SetEmail(s)
	return prtuo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (prtuo *PasswordResetTokenUpdateOne) SetNillableEmail(s *string) *PasswordResetTokenUpdateOne {
	if s != nil {
		prtuo.SetEmail(*s)
	}
	return prtuo
}

// SetExpiresAt sets the "expires_at" field.
func (prtuo *PasswordResetTokenUpdateOne) SetExpiresAt(t time.Time) *PasswordResetTokenUpdateOne {
	prtuo.mutation.SetExpiresAt(t)
	return prtuo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (prtuo *PasswordResetTokenUpdateOne) SetNillableExpiresAt(t *time.Time) *PasswordResetTokenUpdateOne {
	if t != nil {
		prtuo.SetExpiresAt(*t)
	}
	return prtuo
}

// SetUsed sets the "used" field.
func (prtuo *PasswordResetTokenUpdateOne) SetUsed(b bool) *PasswordResetTokenUpdateOne {
	prtuo.mutation.SetUsed(b)
	return prtuo
}

// SetNillableUsed sets the "used" field if the given value is not nil.
func (prtuo *PasswordResetTokenUpdateOne) SetNillableUsed(b *bool) *PasswordResetTokenUpdateOne {
	if b != nil {
		prtuo.SetUsed(*b)
	}
	return prtuo
}

// SetUser sets the "user" edge to the User entity.
func (prtuo *PasswordResetTokenUpdateOne) SetUser(u *User) *PasswordResetTokenUpdateOne {
	return prtuo.SetUserID(u.ID)
}

// Mutation returns the PasswordResetTokenMutation object of the builder.
func (prtuo *PasswordResetTokenUpdateOne) Mutation() *PasswordResetTokenMutation {
	return prtuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (prtuo *PasswordResetTokenUpdateOne) ClearUser() *PasswordResetTokenUpdateOne {
	prtuo.mutation.ClearUser()
	return prtuo
}

// Where appends a list predicates to the PasswordResetTokenUpdate builder.
func (prtuo *PasswordResetTokenUpdateOne) Where(ps ...predicate.PasswordResetToken) *PasswordResetTokenUpdateOne {
	prtuo.mutation.Where(ps...)
	return prtuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (prtuo *PasswordResetTokenUpdateOne) Select(field string, fields ...string) *PasswordResetTokenUpdateOne {
	prtuo.fields = append([]string{field}, fields...)
	return prtuo
}

// Save executes the query and returns the updated PasswordResetToken entity.
func (prtuo *PasswordResetTokenUpdateOne) Save(ctx context.Context) (*PasswordResetToken, error) {
	return withHooks(ctx, prtuo.sqlSave, prtuo.mutation, prtuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (prtuo *PasswordResetTokenUpdateOne) SaveX(ctx context.Context) *PasswordResetToken {
	node, err := prtuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (prtuo *PasswordResetTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := prtuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (prtuo *PasswordResetTokenUpdateOne) ExecX(ctx context.Context) {
	if err := prtuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (prtuo *PasswordResetTokenUpdateOne) check() error {
	if v, ok := prtuo.mutation.Token(); ok {
		if err := passwordresettoken.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "PasswordResetToken.token": %w`, err)}
		}
	}
	if v, ok := prtuo.mutation.Email(); ok {
		if err := passwordresettoken.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "PasswordResetToken.email": %w`, err)}
		}
	}
	if prtuo.mutation.UserCleared() && len(prtuo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PasswordResetToken.user"`)
	}
	return nil
}

func (prtuo *PasswordResetTokenUpdateOne) sqlSave(ctx context.Context) (_node *PasswordResetToken, err error) {
	if err := prtuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(passwordresettoken.Table, passwordresettoken.Columns, sqlgraph.NewFieldSpec(passwordresettoken.FieldID, field.TypeInt64))
	id, ok := prtuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PasswordResetToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := prtuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, passwordresettoken.FieldID)
		for _, f := range fields {
			if !passwordresettoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != passwordresettoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := prtuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := prtuo.mutation.Token(); ok {
		_spec.SetField(passwordresettoken.FieldToken, field.TypeString, value)
	}
	if value, ok := prtuo.mutation.Email(); ok {
		_spec.SetField(passwordresettoken.FieldEmail, field.TypeString, value)
	}
	if value, ok := prtuo.mutation.ExpiresAt(); ok {
		_spec.SetField(passwordresettoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := prtuo.mutation.Used(); ok {
		_spec.SetField(passwordresettoken.FieldUsed, field.TypeBool, value)
	}
	if prtuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   passwordresettoken.UserTable,
			Columns: []string{passwordresettoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := prtuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   passwordresettoken.UserTable,
			Columns: []string{passwordresettoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PasswordResetToken{config: prtuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, prtuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{passwordresettoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	prtuo.mutation.done = true
	return _node, nil
}
