// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/zenstats/zenstats/internal/store/postgresql/ent/apikey"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/funnel"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/schema"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/site"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/user"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/usersession"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apikeyFields := schema.APIKey{}.Fields()
	_ = apikeyFields
	// apikeyDescName is the schema descriptor for name field.
	apikeyDescName := apikeyFields[2].Descriptor()
	// apikey.NameValidator is a validator for the "name" field. It is called by the builders before save.
	apikey.NameValidator = apikeyDescName.Validators[0].(func(string) error)
	// apikeyDescCreatedAt is the schema descriptor for created_at field.
	apikeyDescCreatedAt := apikeyFields[4].Descriptor()
	// apikey.DefaultCreatedAt holds the default value on creation for the created_at field.
	apikey.DefaultCreatedAt = apikeyDescCreatedAt.Default.(func() time.Time)
	funnelFields := schema.Funnel{}.Fields()
	_ = funnelFields
	// funnelDescName is the schema descriptor for name field.
	funnelDescName := funnelFields[2].Descriptor()
	// funnel.NameValidator is a validator for the "name" field. It is called by the builders before save.
	funnel.NameValidator = funnelDescName.Validators[0].(func(string) error)
	siteFields := schema.Site{}.Fields()
	_ = siteFields
	// siteDescDomain is the schema descriptor for domain field.
	siteDescDomain := siteFields[1].Descriptor()
	// site.DomainValidator is a validator for the "domain" field. It is called by the builders before save.
	site.DomainValidator = func() func(string) error {
		validators := siteDescDomain.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(domain string) error {
			for _, fn := range fns {
				if err := fn(domain); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// siteDescRemark is the schema descriptor for remark field.
	siteDescRemark := siteFields[2].Descriptor()
	// site.RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	site.RemarkValidator = siteDescRemark.Validators[0].(func(string) error)
	// siteDescTimezone is the schema descriptor for timezone field.
	siteDescTimezone := siteFields[3].Descriptor()
	// site.DefaultTimezone holds the default value on creation for the timezone field.
	site.DefaultTimezone = siteDescTimezone.Default.(string)
	// site.TimezoneValidator is a validator for the "timezone" field. It is called by the builders before save.
	site.TimezoneValidator = siteDescTimezone.Validators[0].(func(string) error)
	// siteDescPublic is the schema descriptor for public field.
	siteDescPublic := siteFields[4].Descriptor()
	// site.DefaultPublic holds the default value on creation for the public field.
	site.DefaultPublic = siteDescPublic.Default.(bool)
	// siteDescIngestRateLimitScaleSeconds is the schema descriptor for ingest_rate_limit_scale_seconds field.
	siteDescIngestRateLimitScaleSeconds := siteFields[6].Descriptor()
	// site.DefaultIngestRateLimitScaleSeconds holds the default value on creation for the ingest_rate_limit_scale_seconds field.
	site.DefaultIngestRateLimitScaleSeconds = siteDescIngestRateLimitScaleSeconds.Default.(int)
	// siteDescIngestLimitPerMinute is the schema descriptor for ingest_limit_per_minute field.
	siteDescIngestLimitPerMinute := siteFields[7].Descriptor()
	// site.DefaultIngestLimitPerMinute holds the default value on creation for the ingest_limit_per_minute field.
	site.DefaultIngestLimitPerMinute = siteDescIngestLimitPerMinute.Default.(int)
	// siteDescCreatedAt is the schema descriptor for created_at field.
	siteDescCreatedAt := siteFields[8].Descriptor()
	// site.DefaultCreatedAt holds the default value on creation for the created_at field.
	site.DefaultCreatedAt = siteDescCreatedAt.Default.(func() time.Time)
	// siteDescUpdatedAt is the schema descriptor for updated_at field.
	siteDescUpdatedAt := siteFields[9].Descriptor()
	// site.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	site.DefaultUpdatedAt = siteDescUpdatedAt.Default.(func() time.Time)
	// site.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	site.UpdateDefaultUpdatedAt = siteDescUpdatedAt.UpdateDefault.(func() time.Time)
	sitemembershipFields := schema.SiteMembership{}.Fields()
	_ = sitemembershipFields
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmailVerified is the schema descriptor for email_verified field.
	userDescEmailVerified := userFields[2].Descriptor()
	// user.DefaultEmailVerified holds the default value on creation for the email_verified field.
	user.DefaultEmailVerified = userDescEmailVerified.Default.(bool)
	// userDescLastSeen is the schema descriptor for last_seen field.
	userDescLastSeen := userFields[4].Descriptor()
	// user.DefaultLastSeen holds the default value on creation for the last_seen field.
	user.DefaultLastSeen = userDescLastSeen.Default.(func() time.Time)
	// userDescTotpEnabled is the schema descriptor for totp_enabled field.
	userDescTotpEnabled := userFields[8].Descriptor()
	// user.DefaultTotpEnabled holds the default value on creation for the totp_enabled field.
	user.DefaultTotpEnabled = userDescTotpEnabled.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[12].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[13].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	usersessionFields := schema.UserSession{}.Fields()
	_ = usersessionFields
	// usersessionDescDevice is the schema descriptor for device field.
	usersessionDescDevice := usersessionFields[3].Descriptor()
	// usersession.DeviceValidator is a validator for the "device" field. It is called by the builders before save.
	usersession.DeviceValidator = usersessionDescDevice.Validators[0].(func(string) error)
	// usersessionDescCreatedAt is the schema descriptor for created_at field.
	usersessionDescCreatedAt := usersessionFields[6].Descriptor()
	// usersession.DefaultCreatedAt holds the default value on creation for the created_at field.
	usersession.DefaultCreatedAt = usersessionDescCreatedAt.Default.(func() time.Time)
}
