// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/searchengines"
)

// SearchEngines is the model entity for the SearchEngines schema.
type SearchEngines struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Domain holds the value of the "domain" field.
	Domain string `json:"domain,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SearchEngines) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case searchengines.FieldID:
			values[i] = new(sql.NullInt64)
		case searchengines.FieldDomain, searchengines.FieldName:
			values[i] = new(sql.NullString)
		case searchengines.FieldCreatedAt, searchengines.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SearchEngines fields.
func (se *SearchEngines) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case searchengines.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			se.ID = int64(value.Int64)
		case searchengines.FieldDomain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field domain", values[i])
			} else if value.Valid {
				se.Domain = value.String
			}
		case searchengines.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				se.Name = value.String
			}
		case searchengines.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				se.CreatedAt = value.Time
			}
		case searchengines.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				se.UpdatedAt = value.Time
			}
		default:
			se.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SearchEngines.
// This includes values selected through modifiers, order, etc.
func (se *SearchEngines) Value(name string) (ent.Value, error) {
	return se.selectValues.Get(name)
}

// Update returns a builder for updating this SearchEngines.
// Note that you need to call SearchEngines.Unwrap() before calling this method if this SearchEngines
// was returned from a transaction, and the transaction was committed or rolled back.
func (se *SearchEngines) Update() *SearchEnginesUpdateOne {
	return NewSearchEnginesClient(se.config).UpdateOne(se)
}

// Unwrap unwraps the SearchEngines entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (se *SearchEngines) Unwrap() *SearchEngines {
	_tx, ok := se.config.driver.(*txDriver)
	if !ok {
		panic("ent: SearchEngines is not a transactional entity")
	}
	se.config.driver = _tx.drv
	return se
}

// String implements the fmt.Stringer.
func (se *SearchEngines) String() string {
	var builder strings.Builder
	builder.WriteString("SearchEngines(")
	builder.WriteString(fmt.Sprintf("id=%v, ", se.ID))
	builder.WriteString("domain=")
	builder.WriteString(se.Domain)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(se.Name)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(se.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(se.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SearchEnginesSlice is a parsable slice of SearchEngines.
type SearchEnginesSlice []*SearchEngines
