// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/predicate"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/sharedlink"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/site"
)

// SharedLinkQuery is the builder for querying SharedLink entities.
type SharedLinkQuery struct {
	config
	ctx        *QueryContext
	order      []sharedlink.OrderOption
	inters     []Interceptor
	predicates []predicate.SharedLink
	withSite   *SiteQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SharedLinkQuery builder.
func (slq *SharedLinkQuery) Where(ps ...predicate.SharedLink) *SharedLinkQuery {
	slq.predicates = append(slq.predicates, ps...)
	return slq
}

// Limit the number of records to be returned by this query.
func (slq *SharedLinkQuery) Limit(limit int) *SharedLinkQuery {
	slq.ctx.Limit = &limit
	return slq
}

// Offset to start from.
func (slq *SharedLinkQuery) Offset(offset int) *SharedLinkQuery {
	slq.ctx.Offset = &offset
	return slq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (slq *SharedLinkQuery) Unique(unique bool) *SharedLinkQuery {
	slq.ctx.Unique = &unique
	return slq
}

// Order specifies how the records should be ordered.
func (slq *SharedLinkQuery) Order(o ...sharedlink.OrderOption) *SharedLinkQuery {
	slq.order = append(slq.order, o...)
	return slq
}

// QuerySite chains the current query on the "site" edge.
func (slq *SharedLinkQuery) QuerySite() *SiteQuery {
	query := (&SiteClient{config: slq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := slq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := slq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sharedlink.Table, sharedlink.FieldID, selector),
			sqlgraph.To(site.Table, site.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sharedlink.SiteTable, sharedlink.SiteColumn),
		)
		fromU = sqlgraph.SetNeighbors(slq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SharedLink entity from the query.
// Returns a *NotFoundError when no SharedLink was found.
func (slq *SharedLinkQuery) First(ctx context.Context) (*SharedLink, error) {
	nodes, err := slq.Limit(1).All(setContextOp(ctx, slq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sharedlink.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (slq *SharedLinkQuery) FirstX(ctx context.Context) *SharedLink {
	node, err := slq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SharedLink ID from the query.
// Returns a *NotFoundError when no SharedLink ID was found.
func (slq *SharedLinkQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = slq.Limit(1).IDs(setContextOp(ctx, slq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sharedlink.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (slq *SharedLinkQuery) FirstIDX(ctx context.Context) int64 {
	id, err := slq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SharedLink entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SharedLink entity is found.
// Returns a *NotFoundError when no SharedLink entities are found.
func (slq *SharedLinkQuery) Only(ctx context.Context) (*SharedLink, error) {
	nodes, err := slq.Limit(2).All(setContextOp(ctx, slq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sharedlink.Label}
	default:
		return nil, &NotSingularError{sharedlink.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (slq *SharedLinkQuery) OnlyX(ctx context.Context) *SharedLink {
	node, err := slq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SharedLink ID in the query.
// Returns a *NotSingularError when more than one SharedLink ID is found.
// Returns a *NotFoundError when no entities are found.
func (slq *SharedLinkQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = slq.Limit(2).IDs(setContextOp(ctx, slq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sharedlink.Label}
	default:
		err = &NotSingularError{sharedlink.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (slq *SharedLinkQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := slq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SharedLinks.
func (slq *SharedLinkQuery) All(ctx context.Context) ([]*SharedLink, error) {
	ctx = setContextOp(ctx, slq.ctx, ent.OpQueryAll)
	if err := slq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SharedLink, *SharedLinkQuery]()
	return withInterceptors[[]*SharedLink](ctx, slq, qr, slq.inters)
}

// AllX is like All, but panics if an error occurs.
func (slq *SharedLinkQuery) AllX(ctx context.Context) []*SharedLink {
	nodes, err := slq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SharedLink IDs.
func (slq *SharedLinkQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if slq.ctx.Unique == nil && slq.path != nil {
		slq.Unique(true)
	}
	ctx = setContextOp(ctx, slq.ctx, ent.OpQueryIDs)
	if err = slq.Select(sharedlink.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (slq *SharedLinkQuery) IDsX(ctx context.Context) []int64 {
	ids, err := slq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (slq *SharedLinkQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, slq.ctx, ent.OpQueryCount)
	if err := slq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, slq, querierCount[*SharedLinkQuery](), slq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (slq *SharedLinkQuery) CountX(ctx context.Context) int {
	count, err := slq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (slq *SharedLinkQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, slq.ctx, ent.OpQueryExist)
	switch _, err := slq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (slq *SharedLinkQuery) ExistX(ctx context.Context) bool {
	exist, err := slq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SharedLinkQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (slq *SharedLinkQuery) Clone() *SharedLinkQuery {
	if slq == nil {
		return nil
	}
	return &SharedLinkQuery{
		config:     slq.config,
		ctx:        slq.ctx.Clone(),
		order:      append([]sharedlink.OrderOption{}, slq.order...),
		inters:     append([]Interceptor{}, slq.inters...),
		predicates: append([]predicate.SharedLink{}, slq.predicates...),
		withSite:   slq.withSite.Clone(),
		// clone intermediate query.
		sql:  slq.sql.Clone(),
		path: slq.path,
	}
}

// WithSite tells the query-builder to eager-load the nodes that are connected to
// the "site" edge. The optional arguments are used to configure the query builder of the edge.
func (slq *SharedLinkQuery) WithSite(opts ...func(*SiteQuery)) *SharedLinkQuery {
	query := (&SiteClient{config: slq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	slq.withSite = query
	return slq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SiteID int64 `json:"site_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SharedLink.Query().
//		GroupBy(sharedlink.FieldSiteID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (slq *SharedLinkQuery) GroupBy(field string, fields ...string) *SharedLinkGroupBy {
	slq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SharedLinkGroupBy{build: slq}
	grbuild.flds = &slq.ctx.Fields
	grbuild.label = sharedlink.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SiteID int64 `json:"site_id,omitempty"`
//	}
//
//	client.SharedLink.Query().
//		Select(sharedlink.FieldSiteID).
//		Scan(ctx, &v)
func (slq *SharedLinkQuery) Select(fields ...string) *SharedLinkSelect {
	slq.ctx.Fields = append(slq.ctx.Fields, fields...)
	sbuild := &SharedLinkSelect{SharedLinkQuery: slq}
	sbuild.label = sharedlink.Label
	sbuild.flds, sbuild.scan = &slq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SharedLinkSelect configured with the given aggregations.
func (slq *SharedLinkQuery) Aggregate(fns ...AggregateFunc) *SharedLinkSelect {
	return slq.Select().Aggregate(fns...)
}

func (slq *SharedLinkQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range slq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, slq); err != nil {
				return err
			}
		}
	}
	for _, f := range slq.ctx.Fields {
		if !sharedlink.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if slq.path != nil {
		prev, err := slq.path(ctx)
		if err != nil {
			return err
		}
		slq.sql = prev
	}
	return nil
}

func (slq *SharedLinkQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SharedLink, error) {
	var (
		nodes       = []*SharedLink{}
		_spec       = slq.querySpec()
		loadedTypes = [1]bool{
			slq.withSite != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SharedLink).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SharedLink{config: slq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, slq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := slq.withSite; query != nil {
		if err := slq.loadSite(ctx, query, nodes, nil,
			func(n *SharedLink, e *Site) { n.Edges.Site = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (slq *SharedLinkQuery) loadSite(ctx context.Context, query *SiteQuery, nodes []*SharedLink, init func(*SharedLink), assign func(*SharedLink, *Site)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SharedLink)
	for i := range nodes {
		fk := nodes[i].SiteID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(site.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "site_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (slq *SharedLinkQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := slq.querySpec()
	_spec.Node.Columns = slq.ctx.Fields
	if len(slq.ctx.Fields) > 0 {
		_spec.Unique = slq.ctx.Unique != nil && *slq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, slq.driver, _spec)
}

func (slq *SharedLinkQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sharedlink.Table, sharedlink.Columns, sqlgraph.NewFieldSpec(sharedlink.FieldID, field.TypeInt64))
	_spec.From = slq.sql
	if unique := slq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if slq.path != nil {
		_spec.Unique = true
	}
	if fields := slq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sharedlink.FieldID)
		for i := range fields {
			if fields[i] != sharedlink.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if slq.withSite != nil {
			_spec.Node.AddColumnOnce(sharedlink.FieldSiteID)
		}
	}
	if ps := slq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := slq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := slq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := slq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (slq *SharedLinkQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(slq.driver.Dialect())
	t1 := builder.Table(sharedlink.Table)
	columns := slq.ctx.Fields
	if len(columns) == 0 {
		columns = sharedlink.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if slq.sql != nil {
		selector = slq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if slq.ctx.Unique != nil && *slq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range slq.predicates {
		p(selector)
	}
	for _, p := range slq.order {
		p(selector)
	}
	if offset := slq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := slq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SharedLinkGroupBy is the group-by builder for SharedLink entities.
type SharedLinkGroupBy struct {
	selector
	build *SharedLinkQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (slgb *SharedLinkGroupBy) Aggregate(fns ...AggregateFunc) *SharedLinkGroupBy {
	slgb.fns = append(slgb.fns, fns...)
	return slgb
}

// Scan applies the selector query and scans the result into the given value.
func (slgb *SharedLinkGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, slgb.build.ctx, ent.OpQueryGroupBy)
	if err := slgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SharedLinkQuery, *SharedLinkGroupBy](ctx, slgb.build, slgb, slgb.build.inters, v)
}

func (slgb *SharedLinkGroupBy) sqlScan(ctx context.Context, root *SharedLinkQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(slgb.fns))
	for _, fn := range slgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*slgb.flds)+len(slgb.fns))
		for _, f := range *slgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*slgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := slgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SharedLinkSelect is the builder for selecting fields of SharedLink entities.
type SharedLinkSelect struct {
	*SharedLinkQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sls *SharedLinkSelect) Aggregate(fns ...AggregateFunc) *SharedLinkSelect {
	sls.fns = append(sls.fns, fns...)
	return sls
}

// Scan applies the selector query and scans the result into the given value.
func (sls *SharedLinkSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sls.ctx, ent.OpQuerySelect)
	if err := sls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SharedLinkQuery, *SharedLinkSelect](ctx, sls.SharedLinkQuery, sls, sls.inters, v)
}

func (sls *SharedLinkSelect) sqlScan(ctx context.Context, root *SharedLinkQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sls.fns))
	for _, fn := range sls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
