// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/sharedlink"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/site"
)

// SharedLinkCreate is the builder for creating a SharedLink entity.
type SharedLinkCreate struct {
	config
	mutation *SharedLinkMutation
	hooks    []Hook
}

// SetSiteID sets the "site_id" field.
func (slc *SharedLinkCreate) SetSiteID(i int64) *SharedLinkCreate {
	slc.mutation.SetSiteID(i)
	return slc
}

// SetName sets the "name" field.
func (slc *SharedLinkCreate) SetName(s string) *SharedLinkCreate {
	slc.mutation.SetName(s)
	return slc
}

// SetSlug sets the "slug" field.
func (slc *SharedLinkCreate) SetSlug(s string) *SharedLinkCreate {
	slc.mutation.SetSlug(s)
	return slc
}

// SetPasswordHash sets the "password_hash" field.
func (slc *SharedLinkCreate) SetPasswordHash(s string) *SharedLinkCreate {
	slc.mutation.SetPasswordHash(s)
	return slc
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (slc *SharedLinkCreate) SetNillablePasswordHash(s *string) *SharedLinkCreate {
	if s != nil {
		slc.SetPasswordHash(*s)
	}
	return slc
}

// SetCreatedAt sets the "created_at" field.
func (slc *SharedLinkCreate) SetCreatedAt(t time.Time) *SharedLinkCreate {
	slc.mutation.SetCreatedAt(t)
	return slc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (slc *SharedLinkCreate) SetNillableCreatedAt(t *time.Time) *SharedLinkCreate {
	if t != nil {
		slc.SetCreatedAt(*t)
	}
	return slc
}

// SetUpdatedAt sets the "updated_at" field.
func (slc *SharedLinkCreate) SetUpdatedAt(t time.Time) *SharedLinkCreate {
	slc.mutation.SetUpdatedAt(t)
	return slc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (slc *SharedLinkCreate) SetNillableUpdatedAt(t *time.Time) *SharedLinkCreate {
	if t != nil {
		slc.SetUpdatedAt(*t)
	}
	return slc
}

// SetID sets the "id" field.
func (slc *SharedLinkCreate) SetID(i int64) *SharedLinkCreate {
	slc.mutation.SetID(i)
	return slc
}

// SetSite sets the "site" edge to the Site entity.
func (slc *SharedLinkCreate) SetSite(s *Site) *SharedLinkCreate {
	return slc.SetSiteID(s.ID)
}

// Mutation returns the SharedLinkMutation object of the builder.
func (slc *SharedLinkCreate) Mutation() *SharedLinkMutation {
	return slc.mutation
}

// Save creates the SharedLink in the database.
func (slc *SharedLinkCreate) Save(ctx context.Context) (*SharedLink, error) {
	slc.defaults()
	return withHooks(ctx, slc.sqlSave, slc.mutation, slc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (slc *SharedLinkCreate) SaveX(ctx context.Context) *SharedLink {
	v, err := slc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (slc *SharedLinkCreate) Exec(ctx context.Context) error {
	_, err := slc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (slc *SharedLinkCreate) ExecX(ctx context.Context) {
	if err := slc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (slc *SharedLinkCreate) defaults() {
	if _, ok := slc.mutation.CreatedAt(); !ok {
		v := sharedlink.DefaultCreatedAt()
		slc.mutation.SetCreatedAt(v)
	}
	if _, ok := slc.mutation.UpdatedAt(); !ok {
		v := sharedlink.DefaultUpdatedAt()
		slc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (slc *SharedLinkCreate) check() error {
	if _, ok := slc.mutation.SiteID(); !ok {
		return &ValidationError{Name: "site_id", err: errors.New(`ent: missing required field "SharedLink.site_id"`)}
	}
	if _, ok := slc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SharedLink.name"`)}
	}
	if v, ok := slc.mutation.Name(); ok {
		if err := sharedlink.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SharedLink.name": %w`, err)}
		}
	}
	if _, ok := slc.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "SharedLink.slug"`)}
	}
	if v, ok := slc.mutation.Slug(); ok {
		if err := sharedlink.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "SharedLink.slug": %w`, err)}
		}
	}
	if v, ok := slc.mutation.PasswordHash(); ok {
		if err := sharedlink.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "SharedLink.password_hash": %w`, err)}
		}
	}
	if _, ok := slc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SharedLink.created_at"`)}
	}
	if _, ok := slc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SharedLink.updated_at"`)}
	}
	if len(slc.mutation.SiteIDs()) == 0 {
		return &ValidationError{Name: "site", err: errors.New(`ent: missing required edge "SharedLink.site"`)}
	}
	return nil
}

func (slc *SharedLinkCreate) sqlSave(ctx context.Context) (*SharedLink, error) {
	if err := slc.check(); err != nil {
		return nil, err
	}
	_node, _spec := slc.createSpec()
	if err := sqlgraph.CreateNode(ctx, slc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	slc.mutation.id = &_node.ID
	slc.mutation.done = true
	return _node, nil
}

func (slc *SharedLinkCreate) createSpec() (*SharedLink, *sqlgraph.CreateSpec) {
	var (
		_node = &SharedLink{config: slc.config}
		_spec = sqlgraph.NewCreateSpec(sharedlink.Table, sqlgraph.NewFieldSpec(sharedlink.FieldID, field.TypeInt64))
	)
	if id, ok := slc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := slc.mutation.Name(); ok {
		_spec.SetField(sharedlink.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := slc.mutation.Slug(); ok {
		_spec.SetField(sharedlink.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := slc.mutation.PasswordHash(); ok {
		_spec.SetField(sharedlink.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	if value, ok := slc.mutation.CreatedAt(); ok {
		_spec.SetField(sharedlink.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := slc.mutation.UpdatedAt(); ok {
		_spec.SetField(sharedlink.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := slc.mutation.SiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedlink.SiteTable,
			Columns: []string{sharedlink.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SiteID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SharedLinkCreateBulk is the builder for creating many SharedLink entities in bulk.
type SharedLinkCreateBulk struct {
	config
	err      error
	builders []*SharedLinkCreate
}

// Save creates the SharedLink entities in the database.
func (slcb *SharedLinkCreateBulk) Save(ctx context.Context) ([]*SharedLink, error) {
	if slcb.err != nil {
		return nil, slcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(slcb.builders))
	nodes := make([]*SharedLink, len(slcb.builders))
	mutators := make([]Mutator, len(slcb.builders))
	for i := range slcb.builders {
		func(i int, root context.Context) {
			builder := slcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SharedLinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, slcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, slcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, slcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (slcb *SharedLinkCreateBulk) SaveX(ctx context.Context) []*SharedLink {
	v, err := slcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (slcb *SharedLinkCreateBulk) Exec(ctx context.Context) error {
	_, err := slcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (slcb *SharedLinkCreateBulk) ExecX(ctx context.Context) {
	if err := slcb.Exec(ctx); err != nil {
		panic(err)
	}
}
