// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/predicate"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/shieldrulesreferrer"
)

// ShieldRulesReferrerDelete is the builder for deleting a ShieldRulesReferrer entity.
type ShieldRulesReferrerDelete struct {
	config
	hooks    []Hook
	mutation *ShieldRulesReferrerMutation
}

// Where appends a list predicates to the ShieldRulesReferrerDelete builder.
func (srrd *ShieldRulesReferrerDelete) Where(ps ...predicate.ShieldRulesReferrer) *ShieldRulesReferrerDelete {
	srrd.mutation.Where(ps...)
	return srrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (srrd *ShieldRulesReferrerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, srrd.sqlExec, srrd.mutation, srrd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (srrd *ShieldRulesReferrerDelete) ExecX(ctx context.Context) int {
	n, err := srrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (srrd *ShieldRulesReferrerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(shieldrulesreferrer.Table, sqlgraph.NewFieldSpec(shieldrulesreferrer.FieldID, field.TypeInt64))
	if ps := srrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, srrd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	srrd.mutation.done = true
	return affected, err
}

// ShieldRulesReferrerDeleteOne is the builder for deleting a single ShieldRulesReferrer entity.
type ShieldRulesReferrerDeleteOne struct {
	srrd *ShieldRulesReferrerDelete
}

// Where appends a list predicates to the ShieldRulesReferrerDelete builder.
func (srrdo *ShieldRulesReferrerDeleteOne) Where(ps ...predicate.ShieldRulesReferrer) *ShieldRulesReferrerDeleteOne {
	srrdo.srrd.mutation.Where(ps...)
	return srrdo
}

// Exec executes the deletion query.
func (srrdo *ShieldRulesReferrerDeleteOne) Exec(ctx context.Context) error {
	n, err := srrdo.srrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{shieldrulesreferrer.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (srrdo *ShieldRulesReferrerDeleteOne) ExecX(ctx context.Context) {
	if err := srrdo.Exec(ctx); err != nil {
		panic(err)
	}
}
