// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/shieldruleshostname"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/site"
)

// ShieldRulesHostname is the model entity for the ShieldRulesHostname schema.
type ShieldRulesHostname struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// SiteID holds the value of the "site_id" field.
	SiteID int64 `json:"site_id,omitempty"`
	// Hostname holds the value of the "hostname" field.
	Hostname string `json:"hostname,omitempty"`
	// HostnamePattern holds the value of the "hostname_pattern" field.
	HostnamePattern string `json:"hostname_pattern,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// AddedBy holds the value of the "added_by" field.
	AddedBy string `json:"added_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ShieldRulesHostnameQuery when eager-loading is set.
	Edges        ShieldRulesHostnameEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ShieldRulesHostnameEdges holds the relations/edges for other nodes in the graph.
type ShieldRulesHostnameEdges struct {
	// Site holds the value of the site edge.
	Site *Site `json:"site,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SiteOrErr returns the Site value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ShieldRulesHostnameEdges) SiteOrErr() (*Site, error) {
	if e.Site != nil {
		return e.Site, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: site.Label}
	}
	return nil, &NotLoadedError{edge: "site"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ShieldRulesHostname) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case shieldruleshostname.FieldID, shieldruleshostname.FieldSiteID:
			values[i] = new(sql.NullInt64)
		case shieldruleshostname.FieldHostname, shieldruleshostname.FieldHostnamePattern, shieldruleshostname.FieldAction, shieldruleshostname.FieldAddedBy:
			values[i] = new(sql.NullString)
		case shieldruleshostname.FieldCreatedAt, shieldruleshostname.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ShieldRulesHostname fields.
func (srh *ShieldRulesHostname) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case shieldruleshostname.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			srh.ID = int64(value.Int64)
		case shieldruleshostname.FieldSiteID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field site_id", values[i])
			} else if value.Valid {
				srh.SiteID = value.Int64
			}
		case shieldruleshostname.FieldHostname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hostname", values[i])
			} else if value.Valid {
				srh.Hostname = value.String
			}
		case shieldruleshostname.FieldHostnamePattern:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hostname_pattern", values[i])
			} else if value.Valid {
				srh.HostnamePattern = value.String
			}
		case shieldruleshostname.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				srh.Action = value.String
			}
		case shieldruleshostname.FieldAddedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field added_by", values[i])
			} else if value.Valid {
				srh.AddedBy = value.String
			}
		case shieldruleshostname.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				srh.CreatedAt = value.Time
			}
		case shieldruleshostname.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				srh.UpdatedAt = value.Time
			}
		default:
			srh.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ShieldRulesHostname.
// This includes values selected through modifiers, order, etc.
func (srh *ShieldRulesHostname) Value(name string) (ent.Value, error) {
	return srh.selectValues.Get(name)
}

// QuerySite queries the "site" edge of the ShieldRulesHostname entity.
func (srh *ShieldRulesHostname) QuerySite() *SiteQuery {
	return NewShieldRulesHostnameClient(srh.config).QuerySite(srh)
}

// Update returns a builder for updating this ShieldRulesHostname.
// Note that you need to call ShieldRulesHostname.Unwrap() before calling this method if this ShieldRulesHostname
// was returned from a transaction, and the transaction was committed or rolled back.
func (srh *ShieldRulesHostname) Update() *ShieldRulesHostnameUpdateOne {
	return NewShieldRulesHostnameClient(srh.config).UpdateOne(srh)
}

// Unwrap unwraps the ShieldRulesHostname entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (srh *ShieldRulesHostname) Unwrap() *ShieldRulesHostname {
	_tx, ok := srh.config.driver.(*txDriver)
	if !ok {
		panic("ent: ShieldRulesHostname is not a transactional entity")
	}
	srh.config.driver = _tx.drv
	return srh
}

// String implements the fmt.Stringer.
func (srh *ShieldRulesHostname) String() string {
	var builder strings.Builder
	builder.WriteString("ShieldRulesHostname(")
	builder.WriteString(fmt.Sprintf("id=%v, ", srh.ID))
	builder.WriteString("site_id=")
	builder.WriteString(fmt.Sprintf("%v", srh.SiteID))
	builder.WriteString(", ")
	builder.WriteString("hostname=")
	builder.WriteString(srh.Hostname)
	builder.WriteString(", ")
	builder.WriteString("hostname_pattern=")
	builder.WriteString(srh.HostnamePattern)
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(srh.Action)
	builder.WriteString(", ")
	builder.WriteString("added_by=")
	builder.WriteString(srh.AddedBy)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(srh.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(srh.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ShieldRulesHostnames is a parsable slice of ShieldRulesHostname.
type ShieldRulesHostnames []*ShieldRulesHostname
