// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/site"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/sitemembership"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/user"
)

// SiteMembership is the model entity for the SiteMembership schema.
type SiteMembership struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// SiteID holds the value of the "site_id" field.
	SiteID int64 `json:"site_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Role holds the value of the "role" field.
	Role sitemembership.Role `json:"role,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SiteMembershipQuery when eager-loading is set.
	Edges        SiteMembershipEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SiteMembershipEdges holds the relations/edges for other nodes in the graph.
type SiteMembershipEdges struct {
	// Site holds the value of the site edge.
	Site *Site `json:"site,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SiteOrErr returns the Site value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SiteMembershipEdges) SiteOrErr() (*Site, error) {
	if e.Site != nil {
		return e.Site, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: site.Label}
	}
	return nil, &NotLoadedError{edge: "site"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SiteMembershipEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SiteMembership) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sitemembership.FieldID, sitemembership.FieldSiteID, sitemembership.FieldUserID:
			values[i] = new(sql.NullInt64)
		case sitemembership.FieldRole:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SiteMembership fields.
func (sm *SiteMembership) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sitemembership.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sm.ID = int64(value.Int64)
		case sitemembership.FieldSiteID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field site_id", values[i])
			} else if value.Valid {
				sm.SiteID = value.Int64
			}
		case sitemembership.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				sm.UserID = value.Int64
			}
		case sitemembership.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				sm.Role = sitemembership.Role(value.String)
			}
		default:
			sm.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SiteMembership.
// This includes values selected through modifiers, order, etc.
func (sm *SiteMembership) Value(name string) (ent.Value, error) {
	return sm.selectValues.Get(name)
}

// QuerySite queries the "site" edge of the SiteMembership entity.
func (sm *SiteMembership) QuerySite() *SiteQuery {
	return NewSiteMembershipClient(sm.config).QuerySite(sm)
}

// QueryUser queries the "user" edge of the SiteMembership entity.
func (sm *SiteMembership) QueryUser() *UserQuery {
	return NewSiteMembershipClient(sm.config).QueryUser(sm)
}

// Update returns a builder for updating this SiteMembership.
// Note that you need to call SiteMembership.Unwrap() before calling this method if this SiteMembership
// was returned from a transaction, and the transaction was committed or rolled back.
func (sm *SiteMembership) Update() *SiteMembershipUpdateOne {
	return NewSiteMembershipClient(sm.config).UpdateOne(sm)
}

// Unwrap unwraps the SiteMembership entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sm *SiteMembership) Unwrap() *SiteMembership {
	_tx, ok := sm.config.driver.(*txDriver)
	if !ok {
		panic("ent: SiteMembership is not a transactional entity")
	}
	sm.config.driver = _tx.drv
	return sm
}

// String implements the fmt.Stringer.
func (sm *SiteMembership) String() string {
	var builder strings.Builder
	builder.WriteString("SiteMembership(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sm.ID))
	builder.WriteString("site_id=")
	builder.WriteString(fmt.Sprintf("%v", sm.SiteID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", sm.UserID))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(fmt.Sprintf("%v", sm.Role))
	builder.WriteByte(')')
	return builder.String()
}

// SiteMemberships is a parsable slice of SiteMembership.
type SiteMemberships []*SiteMembership
