// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/funnel"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/goal"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/predicate"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/shieldrulescountry"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/shieldruleshostname"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/shieldrulesip"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/site"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/sitemembership"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/user"
)

// SiteUpdate is the builder for updating Site entities.
type SiteUpdate struct {
	config
	hooks    []Hook
	mutation *SiteMutation
}

// Where appends a list predicates to the SiteUpdate builder.
func (su *SiteUpdate) Where(ps ...predicate.Site) *SiteUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetDomain sets the "domain" field.
func (su *SiteUpdate) SetDomain(s string) *SiteUpdate {
	su.mutation.SetDomain(s)
	return su
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (su *SiteUpdate) SetNillableDomain(s *string) *SiteUpdate {
	if s != nil {
		su.SetDomain(*s)
	}
	return su
}

// SetRemark sets the "remark" field.
func (su *SiteUpdate) SetRemark(s string) *SiteUpdate {
	su.mutation.SetRemark(s)
	return su
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (su *SiteUpdate) SetNillableRemark(s *string) *SiteUpdate {
	if s != nil {
		su.SetRemark(*s)
	}
	return su
}

// ClearRemark clears the value of the "remark" field.
func (su *SiteUpdate) ClearRemark() *SiteUpdate {
	su.mutation.ClearRemark()
	return su
}

// SetTimezone sets the "timezone" field.
func (su *SiteUpdate) SetTimezone(s string) *SiteUpdate {
	su.mutation.SetTimezone(s)
	return su
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (su *SiteUpdate) SetNillableTimezone(s *string) *SiteUpdate {
	if s != nil {
		su.SetTimezone(*s)
	}
	return su
}

// SetPublic sets the "public" field.
func (su *SiteUpdate) SetPublic(b bool) *SiteUpdate {
	su.mutation.SetPublic(b)
	return su
}

// SetNillablePublic sets the "public" field if the given value is not nil.
func (su *SiteUpdate) SetNillablePublic(b *bool) *SiteUpdate {
	if b != nil {
		su.SetPublic(*b)
	}
	return su
}

// SetStatsStartDate sets the "stats_start_date" field.
func (su *SiteUpdate) SetStatsStartDate(t time.Time) *SiteUpdate {
	su.mutation.SetStatsStartDate(t)
	return su
}

// SetNillableStatsStartDate sets the "stats_start_date" field if the given value is not nil.
func (su *SiteUpdate) SetNillableStatsStartDate(t *time.Time) *SiteUpdate {
	if t != nil {
		su.SetStatsStartDate(*t)
	}
	return su
}

// ClearStatsStartDate clears the value of the "stats_start_date" field.
func (su *SiteUpdate) ClearStatsStartDate() *SiteUpdate {
	su.mutation.ClearStatsStartDate()
	return su
}

// SetIngestRateLimitScaleSeconds sets the "ingest_rate_limit_scale_seconds" field.
func (su *SiteUpdate) SetIngestRateLimitScaleSeconds(i int) *SiteUpdate {
	su.mutation.ResetIngestRateLimitScaleSeconds()
	su.mutation.SetIngestRateLimitScaleSeconds(i)
	return su
}

// SetNillableIngestRateLimitScaleSeconds sets the "ingest_rate_limit_scale_seconds" field if the given value is not nil.
func (su *SiteUpdate) SetNillableIngestRateLimitScaleSeconds(i *int) *SiteUpdate {
	if i != nil {
		su.SetIngestRateLimitScaleSeconds(*i)
	}
	return su
}

// AddIngestRateLimitScaleSeconds adds i to the "ingest_rate_limit_scale_seconds" field.
func (su *SiteUpdate) AddIngestRateLimitScaleSeconds(i int) *SiteUpdate {
	su.mutation.AddIngestRateLimitScaleSeconds(i)
	return su
}

// SetIngestLimitPerMinute sets the "ingest_limit_per_minute" field.
func (su *SiteUpdate) SetIngestLimitPerMinute(i int) *SiteUpdate {
	su.mutation.ResetIngestLimitPerMinute()
	su.mutation.SetIngestLimitPerMinute(i)
	return su
}

// SetNillableIngestLimitPerMinute sets the "ingest_limit_per_minute" field if the given value is not nil.
func (su *SiteUpdate) SetNillableIngestLimitPerMinute(i *int) *SiteUpdate {
	if i != nil {
		su.SetIngestLimitPerMinute(*i)
	}
	return su
}

// AddIngestLimitPerMinute adds i to the "ingest_limit_per_minute" field.
func (su *SiteUpdate) AddIngestLimitPerMinute(i int) *SiteUpdate {
	su.mutation.AddIngestLimitPerMinute(i)
	return su
}

// SetAllowedOrigins sets the "allowed_origins" field.
func (su *SiteUpdate) SetAllowedOrigins(s string) *SiteUpdate {
	su.mutation.SetAllowedOrigins(s)
	return su
}

// SetNillableAllowedOrigins sets the "allowed_origins" field if the given value is not nil.
func (su *SiteUpdate) SetNillableAllowedOrigins(s *string) *SiteUpdate {
	if s != nil {
		su.SetAllowedOrigins(*s)
	}
	return su
}

// ClearAllowedOrigins clears the value of the "allowed_origins" field.
func (su *SiteUpdate) ClearAllowedOrigins() *SiteUpdate {
	su.mutation.ClearAllowedOrigins()
	return su
}

// SetUpdatedAt sets the "updated_at" field.
func (su *SiteUpdate) SetUpdatedAt(t time.Time) *SiteUpdate {
	su.mutation.SetUpdatedAt(t)
	return su
}

// SetIsVerified sets the "is_verified" field.
func (su *SiteUpdate) SetIsVerified(b bool) *SiteUpdate {
	su.mutation.SetIsVerified(b)
	return su
}

// SetNillableIsVerified sets the "is_verified" field if the given value is not nil.
func (su *SiteUpdate) SetNillableIsVerified(b *bool) *SiteUpdate {
	if b != nil {
		su.SetIsVerified(*b)
	}
	return su
}

// SetVerifiedAt sets the "verified_at" field.
func (su *SiteUpdate) SetVerifiedAt(t time.Time) *SiteUpdate {
	su.mutation.SetVerifiedAt(t)
	return su
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (su *SiteUpdate) SetNillableVerifiedAt(t *time.Time) *SiteUpdate {
	if t != nil {
		su.SetVerifiedAt(*t)
	}
	return su
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (su *SiteUpdate) ClearVerifiedAt() *SiteUpdate {
	su.mutation.ClearVerifiedAt()
	return su
}

// AddFunnelIDs adds the "funnels" edge to the Funnel entity by IDs.
func (su *SiteUpdate) AddFunnelIDs(ids ...int64) *SiteUpdate {
	su.mutation.AddFunnelIDs(ids...)
	return su
}

// AddFunnels adds the "funnels" edges to the Funnel entity.
func (su *SiteUpdate) AddFunnels(f ...*Funnel) *SiteUpdate {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return su.AddFunnelIDs(ids...)
}

// AddMemberIDs adds the "members" edge to the User entity by IDs.
func (su *SiteUpdate) AddMemberIDs(ids ...int64) *SiteUpdate {
	su.mutation.AddMemberIDs(ids...)
	return su
}

// AddMembers adds the "members" edges to the User entity.
func (su *SiteUpdate) AddMembers(u ...*User) *SiteUpdate {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return su.AddMemberIDs(ids...)
}

// AddGoalIDs adds the "goals" edge to the Goal entity by IDs.
func (su *SiteUpdate) AddGoalIDs(ids ...int64) *SiteUpdate {
	su.mutation.AddGoalIDs(ids...)
	return su
}

// AddGoals adds the "goals" edges to the Goal entity.
func (su *SiteUpdate) AddGoals(g ...*Goal) *SiteUpdate {
	ids := make([]int64, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return su.AddGoalIDs(ids...)
}

// AddSiteMembershipIDs adds the "site_memberships" edge to the SiteMembership entity by IDs.
func (su *SiteUpdate) AddSiteMembershipIDs(ids ...int64) *SiteUpdate {
	su.mutation.AddSiteMembershipIDs(ids...)
	return su
}

// AddSiteMemberships adds the "site_memberships" edges to the SiteMembership entity.
func (su *SiteUpdate) AddSiteMemberships(s ...*SiteMembership) *SiteUpdate {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.AddSiteMembershipIDs(ids...)
}

// AddShieldRulesIPIDs adds the "shield_rules_ip" edge to the ShieldRulesIp entity by IDs.
func (su *SiteUpdate) AddShieldRulesIPIDs(ids ...int64) *SiteUpdate {
	su.mutation.AddShieldRulesIPIDs(ids...)
	return su
}

// AddShieldRulesIP adds the "shield_rules_ip" edges to the ShieldRulesIp entity.
func (su *SiteUpdate) AddShieldRulesIP(s ...*ShieldRulesIp) *SiteUpdate {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.AddShieldRulesIPIDs(ids...)
}

// AddShieldRulesHostnameIDs adds the "shield_rules_hostname" edge to the ShieldRulesHostname entity by IDs.
func (su *SiteUpdate) AddShieldRulesHostnameIDs(ids ...int64) *SiteUpdate {
	su.mutation.AddShieldRulesHostnameIDs(ids...)
	return su
}

// AddShieldRulesHostname adds the "shield_rules_hostname" edges to the ShieldRulesHostname entity.
func (su *SiteUpdate) AddShieldRulesHostname(s ...*ShieldRulesHostname) *SiteUpdate {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.AddShieldRulesHostnameIDs(ids...)
}

// AddShieldRulesCountryIDs adds the "shield_rules_country" edge to the ShieldRulesCountry entity by IDs.
func (su *SiteUpdate) AddShieldRulesCountryIDs(ids ...int64) *SiteUpdate {
	su.mutation.AddShieldRulesCountryIDs(ids...)
	return su
}

// AddShieldRulesCountry adds the "shield_rules_country" edges to the ShieldRulesCountry entity.
func (su *SiteUpdate) AddShieldRulesCountry(s ...*ShieldRulesCountry) *SiteUpdate {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.AddShieldRulesCountryIDs(ids...)
}

// Mutation returns the SiteMutation object of the builder.
func (su *SiteUpdate) Mutation() *SiteMutation {
	return su.mutation
}

// ClearFunnels clears all "funnels" edges to the Funnel entity.
func (su *SiteUpdate) ClearFunnels() *SiteUpdate {
	su.mutation.ClearFunnels()
	return su
}

// RemoveFunnelIDs removes the "funnels" edge to Funnel entities by IDs.
func (su *SiteUpdate) RemoveFunnelIDs(ids ...int64) *SiteUpdate {
	su.mutation.RemoveFunnelIDs(ids...)
	return su
}

// RemoveFunnels removes "funnels" edges to Funnel entities.
func (su *SiteUpdate) RemoveFunnels(f ...*Funnel) *SiteUpdate {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return su.RemoveFunnelIDs(ids...)
}

// ClearMembers clears all "members" edges to the User entity.
func (su *SiteUpdate) ClearMembers() *SiteUpdate {
	su.mutation.ClearMembers()
	return su
}

// RemoveMemberIDs removes the "members" edge to User entities by IDs.
func (su *SiteUpdate) RemoveMemberIDs(ids ...int64) *SiteUpdate {
	su.mutation.RemoveMemberIDs(ids...)
	return su
}

// RemoveMembers removes "members" edges to User entities.
func (su *SiteUpdate) RemoveMembers(u ...*User) *SiteUpdate {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return su.RemoveMemberIDs(ids...)
}

// ClearGoals clears all "goals" edges to the Goal entity.
func (su *SiteUpdate) ClearGoals() *SiteUpdate {
	su.mutation.ClearGoals()
	return su
}

// RemoveGoalIDs removes the "goals" edge to Goal entities by IDs.
func (su *SiteUpdate) RemoveGoalIDs(ids ...int64) *SiteUpdate {
	su.mutation.RemoveGoalIDs(ids...)
	return su
}

// RemoveGoals removes "goals" edges to Goal entities.
func (su *SiteUpdate) RemoveGoals(g ...*Goal) *SiteUpdate {
	ids := make([]int64, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return su.RemoveGoalIDs(ids...)
}

// ClearSiteMemberships clears all "site_memberships" edges to the SiteMembership entity.
func (su *SiteUpdate) ClearSiteMemberships() *SiteUpdate {
	su.mutation.ClearSiteMemberships()
	return su
}

// RemoveSiteMembershipIDs removes the "site_memberships" edge to SiteMembership entities by IDs.
func (su *SiteUpdate) RemoveSiteMembershipIDs(ids ...int64) *SiteUpdate {
	su.mutation.RemoveSiteMembershipIDs(ids...)
	return su
}

// RemoveSiteMemberships removes "site_memberships" edges to SiteMembership entities.
func (su *SiteUpdate) RemoveSiteMemberships(s ...*SiteMembership) *SiteUpdate {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.RemoveSiteMembershipIDs(ids...)
}

// ClearShieldRulesIP clears all "shield_rules_ip" edges to the ShieldRulesIp entity.
func (su *SiteUpdate) ClearShieldRulesIP() *SiteUpdate {
	su.mutation.ClearShieldRulesIP()
	return su
}

// RemoveShieldRulesIPIDs removes the "shield_rules_ip" edge to ShieldRulesIp entities by IDs.
func (su *SiteUpdate) RemoveShieldRulesIPIDs(ids ...int64) *SiteUpdate {
	su.mutation.RemoveShieldRulesIPIDs(ids...)
	return su
}

// RemoveShieldRulesIP removes "shield_rules_ip" edges to ShieldRulesIp entities.
func (su *SiteUpdate) RemoveShieldRulesIP(s ...*ShieldRulesIp) *SiteUpdate {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.RemoveShieldRulesIPIDs(ids...)
}

// ClearShieldRulesHostname clears all "shield_rules_hostname" edges to the ShieldRulesHostname entity.
func (su *SiteUpdate) ClearShieldRulesHostname() *SiteUpdate {
	su.mutation.ClearShieldRulesHostname()
	return su
}

// RemoveShieldRulesHostnameIDs removes the "shield_rules_hostname" edge to ShieldRulesHostname entities by IDs.
func (su *SiteUpdate) RemoveShieldRulesHostnameIDs(ids ...int64) *SiteUpdate {
	su.mutation.RemoveShieldRulesHostnameIDs(ids...)
	return su
}

// RemoveShieldRulesHostname removes "shield_rules_hostname" edges to ShieldRulesHostname entities.
func (su *SiteUpdate) RemoveShieldRulesHostname(s ...*ShieldRulesHostname) *SiteUpdate {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.RemoveShieldRulesHostnameIDs(ids...)
}

// ClearShieldRulesCountry clears all "shield_rules_country" edges to the ShieldRulesCountry entity.
func (su *SiteUpdate) ClearShieldRulesCountry() *SiteUpdate {
	su.mutation.ClearShieldRulesCountry()
	return su
}

// RemoveShieldRulesCountryIDs removes the "shield_rules_country" edge to ShieldRulesCountry entities by IDs.
func (su *SiteUpdate) RemoveShieldRulesCountryIDs(ids ...int64) *SiteUpdate {
	su.mutation.RemoveShieldRulesCountryIDs(ids...)
	return su
}

// RemoveShieldRulesCountry removes "shield_rules_country" edges to ShieldRulesCountry entities.
func (su *SiteUpdate) RemoveShieldRulesCountry(s ...*ShieldRulesCountry) *SiteUpdate {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.RemoveShieldRulesCountryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SiteUpdate) Save(ctx context.Context) (int, error) {
	su.defaults()
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SiteUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SiteUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SiteUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *SiteUpdate) defaults() {
	if _, ok := su.mutation.UpdatedAt(); !ok {
		v := site.UpdateDefaultUpdatedAt()
		su.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SiteUpdate) check() error {
	if v, ok := su.mutation.Domain(); ok {
		if err := site.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "Site.domain": %w`, err)}
		}
	}
	if v, ok := su.mutation.Remark(); ok {
		if err := site.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "Site.remark": %w`, err)}
		}
	}
	if v, ok := su.mutation.Timezone(); ok {
		if err := site.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "Site.timezone": %w`, err)}
		}
	}
	if v, ok := su.mutation.AllowedOrigins(); ok {
		if err := site.AllowedOriginsValidator(v); err != nil {
			return &ValidationError{Name: "allowed_origins", err: fmt.Errorf(`ent: validator failed for field "Site.allowed_origins": %w`, err)}
		}
	}
	return nil
}

func (su *SiteUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(site.Table, site.Columns, sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt64))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Domain(); ok {
		_spec.SetField(site.FieldDomain, field.TypeString, value)
	}
	if value, ok := su.mutation.Remark(); ok {
		_spec.SetField(site.FieldRemark, field.TypeString, value)
	}
	if su.mutation.RemarkCleared() {
		_spec.ClearField(site.FieldRemark, field.TypeString)
	}
	if value, ok := su.mutation.Timezone(); ok {
		_spec.SetField(site.FieldTimezone, field.TypeString, value)
	}
	if value, ok := su.mutation.Public(); ok {
		_spec.SetField(site.FieldPublic, field.TypeBool, value)
	}
	if value, ok := su.mutation.StatsStartDate(); ok {
		_spec.SetField(site.FieldStatsStartDate, field.TypeTime, value)
	}
	if su.mutation.StatsStartDateCleared() {
		_spec.ClearField(site.FieldStatsStartDate, field.TypeTime)
	}
	if value, ok := su.mutation.IngestRateLimitScaleSeconds(); ok {
		_spec.SetField(site.FieldIngestRateLimitScaleSeconds, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedIngestRateLimitScaleSeconds(); ok {
		_spec.AddField(site.FieldIngestRateLimitScaleSeconds, field.TypeInt, value)
	}
	if value, ok := su.mutation.IngestLimitPerMinute(); ok {
		_spec.SetField(site.FieldIngestLimitPerMinute, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedIngestLimitPerMinute(); ok {
		_spec.AddField(site.FieldIngestLimitPerMinute, field.TypeInt, value)
	}
	if value, ok := su.mutation.AllowedOrigins(); ok {
		_spec.SetField(site.FieldAllowedOrigins, field.TypeString, value)
	}
	if su.mutation.AllowedOriginsCleared() {
		_spec.ClearField(site.FieldAllowedOrigins, field.TypeString)
	}
	if value, ok := su.mutation.UpdatedAt(); ok {
		_spec.SetField(site.FieldUpdatedAt, field.TypeTime, value)
	}
	if su.mutation.VerificationTokenCleared() {
		_spec.ClearField(site.FieldVerificationToken, field.TypeString)
	}
	if value, ok := su.mutation.IsVerified(); ok {
		_spec.SetField(site.FieldIsVerified, field.TypeBool, value)
	}
	if value, ok := su.mutation.VerifiedAt(); ok {
		_spec.SetField(site.FieldVerifiedAt, field.TypeTime, value)
	}
	if su.mutation.VerifiedAtCleared() {
		_spec.ClearField(site.FieldVerifiedAt, field.TypeTime)
	}
	if su.mutation.FunnelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.FunnelsTable,
			Columns: []string{site.FunnelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(funnel.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedFunnelsIDs(); len(nodes) > 0 && !su.mutation.FunnelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.FunnelsTable,
			Columns: []string{site.FunnelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(funnel.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.FunnelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.FunnelsTable,
			Columns: []string{site.FunnelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(funnel.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.MembersTable,
			Columns: []string{site.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedMembersIDs(); len(nodes) > 0 && !su.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.MembersTable,
			Columns: []string{site.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.MembersTable,
			Columns: []string{site.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.GoalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.GoalsTable,
			Columns: []string{site.GoalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goal.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedGoalsIDs(); len(nodes) > 0 && !su.mutation.GoalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.GoalsTable,
			Columns: []string{site.GoalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goal.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.GoalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.GoalsTable,
			Columns: []string{site.GoalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goal.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.SiteMembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.SiteMembershipsTable,
			Columns: []string{site.SiteMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitemembership.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedSiteMembershipsIDs(); len(nodes) > 0 && !su.mutation.SiteMembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.SiteMembershipsTable,
			Columns: []string{site.SiteMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitemembership.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.SiteMembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.SiteMembershipsTable,
			Columns: []string{site.SiteMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitemembership.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.ShieldRulesIPCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.ShieldRulesIPTable,
			Columns: []string{site.ShieldRulesIPColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shieldrulesip.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedShieldRulesIPIDs(); len(nodes) > 0 && !su.mutation.ShieldRulesIPCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.ShieldRulesIPTable,
			Columns: []string{site.ShieldRulesIPColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shieldrulesip.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.ShieldRulesIPIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.ShieldRulesIPTable,
			Columns: []string{site.ShieldRulesIPColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shieldrulesip.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.ShieldRulesHostnameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.ShieldRulesHostnameTable,
			Columns: []string{site.ShieldRulesHostnameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shieldruleshostname.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedShieldRulesHostnameIDs(); len(nodes) > 0 && !su.mutation.ShieldRulesHostnameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.ShieldRulesHostnameTable,
			Columns: []string{site.ShieldRulesHostnameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shieldruleshostname.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.ShieldRulesHostnameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.ShieldRulesHostnameTable,
			Columns: []string{site.ShieldRulesHostnameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shieldruleshostname.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.ShieldRulesCountryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.ShieldRulesCountryTable,
			Columns: []string{site.ShieldRulesCountryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shieldrulescountry.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedShieldRulesCountryIDs(); len(nodes) > 0 && !su.mutation.ShieldRulesCountryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.ShieldRulesCountryTable,
			Columns: []string{site.ShieldRulesCountryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shieldrulescountry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.ShieldRulesCountryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.ShieldRulesCountryTable,
			Columns: []string{site.ShieldRulesCountryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shieldrulescountry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{site.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SiteUpdateOne is the builder for updating a single Site entity.
type SiteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SiteMutation
}

// SetDomain sets the "domain" field.
func (suo *SiteUpdateOne) SetDomain(s string) *SiteUpdateOne {
	suo.mutation.SetDomain(s)
	return suo
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (suo *SiteUpdateOne) SetNillableDomain(s *string) *SiteUpdateOne {
	if s != nil {
		suo.SetDomain(*s)
	}
	return suo
}

// SetRemark sets the "remark" field.
func (suo *SiteUpdateOne) SetRemark(s string) *SiteUpdateOne {
	suo.mutation.SetRemark(s)
	return suo
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (suo *SiteUpdateOne) SetNillableRemark(s *string) *SiteUpdateOne {
	if s != nil {
		suo.SetRemark(*s)
	}
	return suo
}

// ClearRemark clears the value of the "remark" field.
func (suo *SiteUpdateOne) ClearRemark() *SiteUpdateOne {
	suo.mutation.ClearRemark()
	return suo
}

// SetTimezone sets the "timezone" field.
func (suo *SiteUpdateOne) SetTimezone(s string) *SiteUpdateOne {
	suo.mutation.SetTimezone(s)
	return suo
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (suo *SiteUpdateOne) SetNillableTimezone(s *string) *SiteUpdateOne {
	if s != nil {
		suo.SetTimezone(*s)
	}
	return suo
}

// SetPublic sets the "public" field.
func (suo *SiteUpdateOne) SetPublic(b bool) *SiteUpdateOne {
	suo.mutation.SetPublic(b)
	return suo
}

// SetNillablePublic sets the "public" field if the given value is not nil.
func (suo *SiteUpdateOne) SetNillablePublic(b *bool) *SiteUpdateOne {
	if b != nil {
		suo.SetPublic(*b)
	}
	return suo
}

// SetStatsStartDate sets the "stats_start_date" field.
func (suo *SiteUpdateOne) SetStatsStartDate(t time.Time) *SiteUpdateOne {
	suo.mutation.SetStatsStartDate(t)
	return suo
}

// SetNillableStatsStartDate sets the "stats_start_date" field if the given value is not nil.
func (suo *SiteUpdateOne) SetNillableStatsStartDate(t *time.Time) *SiteUpdateOne {
	if t != nil {
		suo.SetStatsStartDate(*t)
	}
	return suo
}

// ClearStatsStartDate clears the value of the "stats_start_date" field.
func (suo *SiteUpdateOne) ClearStatsStartDate() *SiteUpdateOne {
	suo.mutation.ClearStatsStartDate()
	return suo
}

// SetIngestRateLimitScaleSeconds sets the "ingest_rate_limit_scale_seconds" field.
func (suo *SiteUpdateOne) SetIngestRateLimitScaleSeconds(i int) *SiteUpdateOne {
	suo.mutation.ResetIngestRateLimitScaleSeconds()
	suo.mutation.SetIngestRateLimitScaleSeconds(i)
	return suo
}

// SetNillableIngestRateLimitScaleSeconds sets the "ingest_rate_limit_scale_seconds" field if the given value is not nil.
func (suo *SiteUpdateOne) SetNillableIngestRateLimitScaleSeconds(i *int) *SiteUpdateOne {
	if i != nil {
		suo.SetIngestRateLimitScaleSeconds(*i)
	}
	return suo
}

// AddIngestRateLimitScaleSeconds adds i to the "ingest_rate_limit_scale_seconds" field.
func (suo *SiteUpdateOne) AddIngestRateLimitScaleSeconds(i int) *SiteUpdateOne {
	suo.mutation.AddIngestRateLimitScaleSeconds(i)
	return suo
}

// SetIngestLimitPerMinute sets the "ingest_limit_per_minute" field.
func (suo *SiteUpdateOne) SetIngestLimitPerMinute(i int) *SiteUpdateOne {
	suo.mutation.ResetIngestLimitPerMinute()
	suo.mutation.SetIngestLimitPerMinute(i)
	return suo
}

// SetNillableIngestLimitPerMinute sets the "ingest_limit_per_minute" field if the given value is not nil.
func (suo *SiteUpdateOne) SetNillableIngestLimitPerMinute(i *int) *SiteUpdateOne {
	if i != nil {
		suo.SetIngestLimitPerMinute(*i)
	}
	return suo
}

// AddIngestLimitPerMinute adds i to the "ingest_limit_per_minute" field.
func (suo *SiteUpdateOne) AddIngestLimitPerMinute(i int) *SiteUpdateOne {
	suo.mutation.AddIngestLimitPerMinute(i)
	return suo
}

// SetAllowedOrigins sets the "allowed_origins" field.
func (suo *SiteUpdateOne) SetAllowedOrigins(s string) *SiteUpdateOne {
	suo.mutation.SetAllowedOrigins(s)
	return suo
}

// SetNillableAllowedOrigins sets the "allowed_origins" field if the given value is not nil.
func (suo *SiteUpdateOne) SetNillableAllowedOrigins(s *string) *SiteUpdateOne {
	if s != nil {
		suo.SetAllowedOrigins(*s)
	}
	return suo
}

// ClearAllowedOrigins clears the value of the "allowed_origins" field.
func (suo *SiteUpdateOne) ClearAllowedOrigins() *SiteUpdateOne {
	suo.mutation.ClearAllowedOrigins()
	return suo
}

// SetUpdatedAt sets the "updated_at" field.
func (suo *SiteUpdateOne) SetUpdatedAt(t time.Time) *SiteUpdateOne {
	suo.mutation.SetUpdatedAt(t)
	return suo
}

// SetIsVerified sets the "is_verified" field.
func (suo *SiteUpdateOne) SetIsVerified(b bool) *SiteUpdateOne {
	suo.mutation.SetIsVerified(b)
	return suo
}

// SetNillableIsVerified sets the "is_verified" field if the given value is not nil.
func (suo *SiteUpdateOne) SetNillableIsVerified(b *bool) *SiteUpdateOne {
	if b != nil {
		suo.SetIsVerified(*b)
	}
	return suo
}

// SetVerifiedAt sets the "verified_at" field.
func (suo *SiteUpdateOne) SetVerifiedAt(t time.Time) *SiteUpdateOne {
	suo.mutation.SetVerifiedAt(t)
	return suo
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (suo *SiteUpdateOne) SetNillableVerifiedAt(t *time.Time) *SiteUpdateOne {
	if t != nil {
		suo.SetVerifiedAt(*t)
	}
	return suo
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (suo *SiteUpdateOne) ClearVerifiedAt() *SiteUpdateOne {
	suo.mutation.ClearVerifiedAt()
	return suo
}

// AddFunnelIDs adds the "funnels" edge to the Funnel entity by IDs.
func (suo *SiteUpdateOne) AddFunnelIDs(ids ...int64) *SiteUpdateOne {
	suo.mutation.AddFunnelIDs(ids...)
	return suo
}

// AddFunnels adds the "funnels" edges to the Funnel entity.
func (suo *SiteUpdateOne) AddFunnels(f ...*Funnel) *SiteUpdateOne {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return suo.AddFunnelIDs(ids...)
}

// AddMemberIDs adds the "members" edge to the User entity by IDs.
func (suo *SiteUpdateOne) AddMemberIDs(ids ...int64) *SiteUpdateOne {
	suo.mutation.AddMemberIDs(ids...)
	return suo
}

// AddMembers adds the "members" edges to the User entity.
func (suo *SiteUpdateOne) AddMembers(u ...*User) *SiteUpdateOne {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return suo.AddMemberIDs(ids...)
}

// AddGoalIDs adds the "goals" edge to the Goal entity by IDs.
func (suo *SiteUpdateOne) AddGoalIDs(ids ...int64) *SiteUpdateOne {
	suo.mutation.AddGoalIDs(ids...)
	return suo
}

// AddGoals adds the "goals" edges to the Goal entity.
func (suo *SiteUpdateOne) AddGoals(g ...*Goal) *SiteUpdateOne {
	ids := make([]int64, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return suo.AddGoalIDs(ids...)
}

// AddSiteMembershipIDs adds the "site_memberships" edge to the SiteMembership entity by IDs.
func (suo *SiteUpdateOne) AddSiteMembershipIDs(ids ...int64) *SiteUpdateOne {
	suo.mutation.AddSiteMembershipIDs(ids...)
	return suo
}

// AddSiteMemberships adds the "site_memberships" edges to the SiteMembership entity.
func (suo *SiteUpdateOne) AddSiteMemberships(s ...*SiteMembership) *SiteUpdateOne {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.AddSiteMembershipIDs(ids...)
}

// AddShieldRulesIPIDs adds the "shield_rules_ip" edge to the ShieldRulesIp entity by IDs.
func (suo *SiteUpdateOne) AddShieldRulesIPIDs(ids ...int64) *SiteUpdateOne {
	suo.mutation.AddShieldRulesIPIDs(ids...)
	return suo
}

// AddShieldRulesIP adds the "shield_rules_ip" edges to the ShieldRulesIp entity.
func (suo *SiteUpdateOne) AddShieldRulesIP(s ...*ShieldRulesIp) *SiteUpdateOne {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.AddShieldRulesIPIDs(ids...)
}

// AddShieldRulesHostnameIDs adds the "shield_rules_hostname" edge to the ShieldRulesHostname entity by IDs.
func (suo *SiteUpdateOne) AddShieldRulesHostnameIDs(ids ...int64) *SiteUpdateOne {
	suo.mutation.AddShieldRulesHostnameIDs(ids...)
	return suo
}

// AddShieldRulesHostname adds the "shield_rules_hostname" edges to the ShieldRulesHostname entity.
func (suo *SiteUpdateOne) AddShieldRulesHostname(s ...*ShieldRulesHostname) *SiteUpdateOne {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.AddShieldRulesHostnameIDs(ids...)
}

// AddShieldRulesCountryIDs adds the "shield_rules_country" edge to the ShieldRulesCountry entity by IDs.
func (suo *SiteUpdateOne) AddShieldRulesCountryIDs(ids ...int64) *SiteUpdateOne {
	suo.mutation.AddShieldRulesCountryIDs(ids...)
	return suo
}

// AddShieldRulesCountry adds the "shield_rules_country" edges to the ShieldRulesCountry entity.
func (suo *SiteUpdateOne) AddShieldRulesCountry(s ...*ShieldRulesCountry) *SiteUpdateOne {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.AddShieldRulesCountryIDs(ids...)
}

// Mutation returns the SiteMutation object of the builder.
func (suo *SiteUpdateOne) Mutation() *SiteMutation {
	return suo.mutation
}

// ClearFunnels clears all "funnels" edges to the Funnel entity.
func (suo *SiteUpdateOne) ClearFunnels() *SiteUpdateOne {
	suo.mutation.ClearFunnels()
	return suo
}

// RemoveFunnelIDs removes the "funnels" edge to Funnel entities by IDs.
func (suo *SiteUpdateOne) RemoveFunnelIDs(ids ...int64) *SiteUpdateOne {
	suo.mutation.RemoveFunnelIDs(ids...)
	return suo
}

// RemoveFunnels removes "funnels" edges to Funnel entities.
func (suo *SiteUpdateOne) RemoveFunnels(f ...*Funnel) *SiteUpdateOne {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return suo.RemoveFunnelIDs(ids...)
}

// ClearMembers clears all "members" edges to the User entity.
func (suo *SiteUpdateOne) ClearMembers() *SiteUpdateOne {
	suo.mutation.ClearMembers()
	return suo
}

// RemoveMemberIDs removes the "members" edge to User entities by IDs.
func (suo *SiteUpdateOne) RemoveMemberIDs(ids ...int64) *SiteUpdateOne {
	suo.mutation.RemoveMemberIDs(ids...)
	return suo
}

// RemoveMembers removes "members" edges to User entities.
func (suo *SiteUpdateOne) RemoveMembers(u ...*User) *SiteUpdateOne {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return suo.RemoveMemberIDs(ids...)
}

// ClearGoals clears all "goals" edges to the Goal entity.
func (suo *SiteUpdateOne) ClearGoals() *SiteUpdateOne {
	suo.mutation.ClearGoals()
	return suo
}

// RemoveGoalIDs removes the "goals" edge to Goal entities by IDs.
func (suo *SiteUpdateOne) RemoveGoalIDs(ids ...int64) *SiteUpdateOne {
	suo.mutation.RemoveGoalIDs(ids...)
	return suo
}

// RemoveGoals removes "goals" edges to Goal entities.
func (suo *SiteUpdateOne) RemoveGoals(g ...*Goal) *SiteUpdateOne {
	ids := make([]int64, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return suo.RemoveGoalIDs(ids...)
}

// ClearSiteMemberships clears all "site_memberships" edges to the SiteMembership entity.
func (suo *SiteUpdateOne) ClearSiteMemberships() *SiteUpdateOne {
	suo.mutation.ClearSiteMemberships()
	return suo
}

// RemoveSiteMembershipIDs removes the "site_memberships" edge to SiteMembership entities by IDs.
func (suo *SiteUpdateOne) RemoveSiteMembershipIDs(ids ...int64) *SiteUpdateOne {
	suo.mutation.RemoveSiteMembershipIDs(ids...)
	return suo
}

// RemoveSiteMemberships removes "site_memberships" edges to SiteMembership entities.
func (suo *SiteUpdateOne) RemoveSiteMemberships(s ...*SiteMembership) *SiteUpdateOne {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.RemoveSiteMembershipIDs(ids...)
}

// ClearShieldRulesIP clears all "shield_rules_ip" edges to the ShieldRulesIp entity.
func (suo *SiteUpdateOne) ClearShieldRulesIP() *SiteUpdateOne {
	suo.mutation.ClearShieldRulesIP()
	return suo
}

// RemoveShieldRulesIPIDs removes the "shield_rules_ip" edge to ShieldRulesIp entities by IDs.
func (suo *SiteUpdateOne) RemoveShieldRulesIPIDs(ids ...int64) *SiteUpdateOne {
	suo.mutation.RemoveShieldRulesIPIDs(ids...)
	return suo
}

// RemoveShieldRulesIP removes "shield_rules_ip" edges to ShieldRulesIp entities.
func (suo *SiteUpdateOne) RemoveShieldRulesIP(s ...*ShieldRulesIp) *SiteUpdateOne {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.RemoveShieldRulesIPIDs(ids...)
}

// ClearShieldRulesHostname clears all "shield_rules_hostname" edges to the ShieldRulesHostname entity.
func (suo *SiteUpdateOne) ClearShieldRulesHostname() *SiteUpdateOne {
	suo.mutation.ClearShieldRulesHostname()
	return suo
}

// RemoveShieldRulesHostnameIDs removes the "shield_rules_hostname" edge to ShieldRulesHostname entities by IDs.
func (suo *SiteUpdateOne) RemoveShieldRulesHostnameIDs(ids ...int64) *SiteUpdateOne {
	suo.mutation.RemoveShieldRulesHostnameIDs(ids...)
	return suo
}

// RemoveShieldRulesHostname removes "shield_rules_hostname" edges to ShieldRulesHostname entities.
func (suo *SiteUpdateOne) RemoveShieldRulesHostname(s ...*ShieldRulesHostname) *SiteUpdateOne {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.RemoveShieldRulesHostnameIDs(ids...)
}

// ClearShieldRulesCountry clears all "shield_rules_country" edges to the ShieldRulesCountry entity.
func (suo *SiteUpdateOne) ClearShieldRulesCountry() *SiteUpdateOne {
	suo.mutation.ClearShieldRulesCountry()
	return suo
}

// RemoveShieldRulesCountryIDs removes the "shield_rules_country" edge to ShieldRulesCountry entities by IDs.
func (suo *SiteUpdateOne) RemoveShieldRulesCountryIDs(ids ...int64) *SiteUpdateOne {
	suo.mutation.RemoveShieldRulesCountryIDs(ids...)
	return suo
}

// RemoveShieldRulesCountry removes "shield_rules_country" edges to ShieldRulesCountry entities.
func (suo *SiteUpdateOne) RemoveShieldRulesCountry(s ...*ShieldRulesCountry) *SiteUpdateOne {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.RemoveShieldRulesCountryIDs(ids...)
}

// Where appends a list predicates to the SiteUpdate builder.
func (suo *SiteUpdateOne) Where(ps ...predicate.Site) *SiteUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SiteUpdateOne) Select(field string, fields ...string) *SiteUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Site entity.
func (suo *SiteUpdateOne) Save(ctx context.Context) (*Site, error) {
	suo.defaults()
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SiteUpdateOne) SaveX(ctx context.Context) *Site {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SiteUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SiteUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *SiteUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdatedAt(); !ok {
		v := site.UpdateDefaultUpdatedAt()
		suo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SiteUpdateOne) check() error {
	if v, ok := suo.mutation.Domain(); ok {
		if err := site.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "Site.domain": %w`, err)}
		}
	}
	if v, ok := suo.mutation.Remark(); ok {
		if err := site.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "Site.remark": %w`, err)}
		}
	}
	if v, ok := suo.mutation.Timezone(); ok {
		if err := site.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "Site.timezone": %w`, err)}
		}
	}
	if v, ok := suo.mutation.AllowedOrigins(); ok {
		if err := site.AllowedOriginsValidator(v); err != nil {
			return &ValidationError{Name: "allowed_origins", err: fmt.Errorf(`ent: validator failed for field "Site.allowed_origins": %w`, err)}
		}
	}
	return nil
}

func (suo *SiteUpdateOne) sqlSave(ctx context.Context) (_node *Site, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(site.Table, site.Columns, sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt64))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Site.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, site.FieldID)
		for _, f := range fields {
			if !site.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != site.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Domain(); ok {
		_spec.SetField(site.FieldDomain, field.TypeString, value)
	}
	if value, ok := suo.mutation.Remark(); ok {
		_spec.SetField(site.FieldRemark, field.TypeString, value)
	}
	if suo.mutation.RemarkCleared() {
		_spec.ClearField(site.FieldRemark, field.TypeString)
	}
	if value, ok := suo.mutation.Timezone(); ok {
		_spec.SetField(site.FieldTimezone, field.TypeString, value)
	}
	if value, ok := suo.mutation.Public(); ok {
		_spec.SetField(site.FieldPublic, field.TypeBool, value)
	}
	if value, ok := suo.mutation.StatsStartDate(); ok {
		_spec.SetField(site.FieldStatsStartDate, field.TypeTime, value)
	}
	if suo.mutation.StatsStartDateCleared() {
		_spec.ClearField(site.FieldStatsStartDate, field.TypeTime)
	}
	if value, ok := suo.mutation.IngestRateLimitScaleSeconds(); ok {
		_spec.SetField(site.FieldIngestRateLimitScaleSeconds, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedIngestRateLimitScaleSeconds(); ok {
		_spec.AddField(site.FieldIngestRateLimitScaleSeconds, field.TypeInt, value)
	}
	if value, ok := suo.mutation.IngestLimitPerMinute(); ok {
		_spec.SetField(site.FieldIngestLimitPerMinute, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedIngestLimitPerMinute(); ok {
		_spec.AddField(site.FieldIngestLimitPerMinute, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AllowedOrigins(); ok {
		_spec.SetField(site.FieldAllowedOrigins, field.TypeString, value)
	}
	if suo.mutation.AllowedOriginsCleared() {
		_spec.ClearField(site.FieldAllowedOrigins, field.TypeString)
	}
	if value, ok := suo.mutation.UpdatedAt(); ok {
		_spec.SetField(site.FieldUpdatedAt, field.TypeTime, value)
	}
	if suo.mutation.VerificationTokenCleared() {
		_spec.ClearField(site.FieldVerificationToken, field.TypeString)
	}
	if value, ok := suo.mutation.IsVerified(); ok {
		_spec.SetField(site.FieldIsVerified, field.TypeBool, value)
	}
	if value, ok := suo.mutation.VerifiedAt(); ok {
		_spec.SetField(site.FieldVerifiedAt, field.TypeTime, value)
	}
	if suo.mutation.VerifiedAtCleared() {
		_spec.ClearField(site.FieldVerifiedAt, field.TypeTime)
	}
	if suo.mutation.FunnelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.FunnelsTable,
			Columns: []string{site.FunnelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(funnel.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedFunnelsIDs(); len(nodes) > 0 && !suo.mutation.FunnelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.FunnelsTable,
			Columns: []string{site.FunnelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(funnel.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.FunnelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.FunnelsTable,
			Columns: []string{site.FunnelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(funnel.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.MembersTable,
			Columns: []string{site.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedMembersIDs(); len(nodes) > 0 && !suo.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.MembersTable,
			Columns: []string{site.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.MembersTable,
			Columns: []string{site.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.GoalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.GoalsTable,
			Columns: []string{site.GoalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goal.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedGoalsIDs(); len(nodes) > 0 && !suo.mutation.GoalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.GoalsTable,
			Columns: []string{site.GoalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goal.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.GoalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.GoalsTable,
			Columns: []string{site.GoalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goal.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.SiteMembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.SiteMembershipsTable,
			Columns: []string{site.SiteMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitemembership.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedSiteMembershipsIDs(); len(nodes) > 0 && !suo.mutation.SiteMembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.SiteMembershipsTable,
			Columns: []string{site.SiteMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitemembership.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.SiteMembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.SiteMembershipsTable,
			Columns: []string{site.SiteMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitemembership.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.ShieldRulesIPCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.ShieldRulesIPTable,
			Columns: []string{site.ShieldRulesIPColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shieldrulesip.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedShieldRulesIPIDs(); len(nodes) > 0 && !suo.mutation.ShieldRulesIPCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.ShieldRulesIPTable,
			Columns: []string{site.ShieldRulesIPColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shieldrulesip.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.ShieldRulesIPIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.ShieldRulesIPTable,
			Columns: []string{site.ShieldRulesIPColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shieldrulesip.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.ShieldRulesHostnameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.ShieldRulesHostnameTable,
			Columns: []string{site.ShieldRulesHostnameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shieldruleshostname.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedShieldRulesHostnameIDs(); len(nodes) > 0 && !suo.mutation.ShieldRulesHostnameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.ShieldRulesHostnameTable,
			Columns: []string{site.ShieldRulesHostnameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shieldruleshostname.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.ShieldRulesHostnameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.ShieldRulesHostnameTable,
			Columns: []string{site.ShieldRulesHostnameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shieldruleshostname.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.ShieldRulesCountryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.ShieldRulesCountryTable,
			Columns: []string{site.ShieldRulesCountryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shieldrulescountry.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedShieldRulesCountryIDs(); len(nodes) > 0 && !suo.mutation.ShieldRulesCountryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.ShieldRulesCountryTable,
			Columns: []string{site.ShieldRulesCountryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shieldrulescountry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.ShieldRulesCountryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.ShieldRulesCountryTable,
			Columns: []string{site.ShieldRulesCountryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shieldrulescountry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Site{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{site.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
