// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/site"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/sitemembership"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/user"
)

// SiteMembershipCreate is the builder for creating a SiteMembership entity.
type SiteMembershipCreate struct {
	config
	mutation *SiteMembershipMutation
	hooks    []Hook
}

// SetSiteID sets the "site_id" field.
func (smc *SiteMembershipCreate) SetSiteID(i int64) *SiteMembershipCreate {
	smc.mutation.SetSiteID(i)
	return smc
}

// SetUserID sets the "user_id" field.
func (smc *SiteMembershipCreate) SetUserID(i int64) *SiteMembershipCreate {
	smc.mutation.SetUserID(i)
	return smc
}

// SetRole sets the "role" field.
func (smc *SiteMembershipCreate) SetRole(s sitemembership.Role) *SiteMembershipCreate {
	smc.mutation.SetRole(s)
	return smc
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (smc *SiteMembershipCreate) SetNillableRole(s *sitemembership.Role) *SiteMembershipCreate {
	if s != nil {
		smc.SetRole(*s)
	}
	return smc
}

// SetID sets the "id" field.
func (smc *SiteMembershipCreate) SetID(i int64) *SiteMembershipCreate {
	smc.mutation.SetID(i)
	return smc
}

// SetSite sets the "site" edge to the Site entity.
func (smc *SiteMembershipCreate) SetSite(s *Site) *SiteMembershipCreate {
	return smc.SetSiteID(s.ID)
}

// SetUser sets the "user" edge to the User entity.
func (smc *SiteMembershipCreate) SetUser(u *User) *SiteMembershipCreate {
	return smc.SetUserID(u.ID)
}

// Mutation returns the SiteMembershipMutation object of the builder.
func (smc *SiteMembershipCreate) Mutation() *SiteMembershipMutation {
	return smc.mutation
}

// Save creates the SiteMembership in the database.
func (smc *SiteMembershipCreate) Save(ctx context.Context) (*SiteMembership, error) {
	smc.defaults()
	return withHooks(ctx, smc.sqlSave, smc.mutation, smc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (smc *SiteMembershipCreate) SaveX(ctx context.Context) *SiteMembership {
	v, err := smc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (smc *SiteMembershipCreate) Exec(ctx context.Context) error {
	_, err := smc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (smc *SiteMembershipCreate) ExecX(ctx context.Context) {
	if err := smc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (smc *SiteMembershipCreate) defaults() {
	if _, ok := smc.mutation.Role(); !ok {
		v := sitemembership.DefaultRole
		smc.mutation.SetRole(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (smc *SiteMembershipCreate) check() error {
	if _, ok := smc.mutation.SiteID(); !ok {
		return &ValidationError{Name: "site_id", err: errors.New(`ent: missing required field "SiteMembership.site_id"`)}
	}
	if _, ok := smc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SiteMembership.user_id"`)}
	}
	if _, ok := smc.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "SiteMembership.role"`)}
	}
	if v, ok := smc.mutation.Role(); ok {
		if err := sitemembership.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "SiteMembership.role": %w`, err)}
		}
	}
	if len(smc.mutation.SiteIDs()) == 0 {
		return &ValidationError{Name: "site", err: errors.New(`ent: missing required edge "SiteMembership.site"`)}
	}
	if len(smc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "SiteMembership.user"`)}
	}
	return nil
}

func (smc *SiteMembershipCreate) sqlSave(ctx context.Context) (*SiteMembership, error) {
	if err := smc.check(); err != nil {
		return nil, err
	}
	_node, _spec := smc.createSpec()
	if err := sqlgraph.CreateNode(ctx, smc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	smc.mutation.id = &_node.ID
	smc.mutation.done = true
	return _node, nil
}

func (smc *SiteMembershipCreate) createSpec() (*SiteMembership, *sqlgraph.CreateSpec) {
	var (
		_node = &SiteMembership{config: smc.config}
		_spec = sqlgraph.NewCreateSpec(sitemembership.Table, sqlgraph.NewFieldSpec(sitemembership.FieldID, field.TypeInt64))
	)
	if id, ok := smc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := smc.mutation.Role(); ok {
		_spec.SetField(sitemembership.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if nodes := smc.mutation.SiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sitemembership.SiteTable,
			Columns: []string{sitemembership.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SiteID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := smc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sitemembership.UserTable,
			Columns: []string{sitemembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SiteMembershipCreateBulk is the builder for creating many SiteMembership entities in bulk.
type SiteMembershipCreateBulk struct {
	config
	err      error
	builders []*SiteMembershipCreate
}

// Save creates the SiteMembership entities in the database.
func (smcb *SiteMembershipCreateBulk) Save(ctx context.Context) ([]*SiteMembership, error) {
	if smcb.err != nil {
		return nil, smcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(smcb.builders))
	nodes := make([]*SiteMembership, len(smcb.builders))
	mutators := make([]Mutator, len(smcb.builders))
	for i := range smcb.builders {
		func(i int, root context.Context) {
			builder := smcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SiteMembershipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, smcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, smcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, smcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (smcb *SiteMembershipCreateBulk) SaveX(ctx context.Context) []*SiteMembership {
	v, err := smcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (smcb *SiteMembershipCreateBulk) Exec(ctx context.Context) error {
	_, err := smcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (smcb *SiteMembershipCreateBulk) ExecX(ctx context.Context) {
	if err := smcb.Exec(ctx); err != nil {
		panic(err)
	}
}
