// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/funnel"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/goal"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/shieldrulescountry"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/shieldruleshostname"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/shieldrulesip"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/site"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/sitemembership"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/user"
)

// SiteCreate is the builder for creating a Site entity.
type SiteCreate struct {
	config
	mutation *SiteMutation
	hooks    []Hook
}

// SetDomain sets the "domain" field.
func (sc *SiteCreate) SetDomain(s string) *SiteCreate {
	sc.mutation.SetDomain(s)
	return sc
}

// SetRemark sets the "remark" field.
func (sc *SiteCreate) SetRemark(s string) *SiteCreate {
	sc.mutation.SetRemark(s)
	return sc
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (sc *SiteCreate) SetNillableRemark(s *string) *SiteCreate {
	if s != nil {
		sc.SetRemark(*s)
	}
	return sc
}

// SetTimezone sets the "timezone" field.
func (sc *SiteCreate) SetTimezone(s string) *SiteCreate {
	sc.mutation.SetTimezone(s)
	return sc
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (sc *SiteCreate) SetNillableTimezone(s *string) *SiteCreate {
	if s != nil {
		sc.SetTimezone(*s)
	}
	return sc
}

// SetPublic sets the "public" field.
func (sc *SiteCreate) SetPublic(b bool) *SiteCreate {
	sc.mutation.SetPublic(b)
	return sc
}

// SetNillablePublic sets the "public" field if the given value is not nil.
func (sc *SiteCreate) SetNillablePublic(b *bool) *SiteCreate {
	if b != nil {
		sc.SetPublic(*b)
	}
	return sc
}

// SetStatsStartDate sets the "stats_start_date" field.
func (sc *SiteCreate) SetStatsStartDate(t time.Time) *SiteCreate {
	sc.mutation.SetStatsStartDate(t)
	return sc
}

// SetNillableStatsStartDate sets the "stats_start_date" field if the given value is not nil.
func (sc *SiteCreate) SetNillableStatsStartDate(t *time.Time) *SiteCreate {
	if t != nil {
		sc.SetStatsStartDate(*t)
	}
	return sc
}

// SetIngestRateLimitScaleSeconds sets the "ingest_rate_limit_scale_seconds" field.
func (sc *SiteCreate) SetIngestRateLimitScaleSeconds(i int) *SiteCreate {
	sc.mutation.SetIngestRateLimitScaleSeconds(i)
	return sc
}

// SetNillableIngestRateLimitScaleSeconds sets the "ingest_rate_limit_scale_seconds" field if the given value is not nil.
func (sc *SiteCreate) SetNillableIngestRateLimitScaleSeconds(i *int) *SiteCreate {
	if i != nil {
		sc.SetIngestRateLimitScaleSeconds(*i)
	}
	return sc
}

// SetIngestLimitPerMinute sets the "ingest_limit_per_minute" field.
func (sc *SiteCreate) SetIngestLimitPerMinute(i int) *SiteCreate {
	sc.mutation.SetIngestLimitPerMinute(i)
	return sc
}

// SetNillableIngestLimitPerMinute sets the "ingest_limit_per_minute" field if the given value is not nil.
func (sc *SiteCreate) SetNillableIngestLimitPerMinute(i *int) *SiteCreate {
	if i != nil {
		sc.SetIngestLimitPerMinute(*i)
	}
	return sc
}

// SetAllowedOrigins sets the "allowed_origins" field.
func (sc *SiteCreate) SetAllowedOrigins(s string) *SiteCreate {
	sc.mutation.SetAllowedOrigins(s)
	return sc
}

// SetNillableAllowedOrigins sets the "allowed_origins" field if the given value is not nil.
func (sc *SiteCreate) SetNillableAllowedOrigins(s *string) *SiteCreate {
	if s != nil {
		sc.SetAllowedOrigins(*s)
	}
	return sc
}

// SetCreatedAt sets the "created_at" field.
func (sc *SiteCreate) SetCreatedAt(t time.Time) *SiteCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sc *SiteCreate) SetNillableCreatedAt(t *time.Time) *SiteCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// SetUpdatedAt sets the "updated_at" field.
func (sc *SiteCreate) SetUpdatedAt(t time.Time) *SiteCreate {
	sc.mutation.SetUpdatedAt(t)
	return sc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sc *SiteCreate) SetNillableUpdatedAt(t *time.Time) *SiteCreate {
	if t != nil {
		sc.SetUpdatedAt(*t)
	}
	return sc
}

// SetVerificationToken sets the "verification_token" field.
func (sc *SiteCreate) SetVerificationToken(s string) *SiteCreate {
	sc.mutation.SetVerificationToken(s)
	return sc
}

// SetIsVerified sets the "is_verified" field.
func (sc *SiteCreate) SetIsVerified(b bool) *SiteCreate {
	sc.mutation.SetIsVerified(b)
	return sc
}

// SetNillableIsVerified sets the "is_verified" field if the given value is not nil.
func (sc *SiteCreate) SetNillableIsVerified(b *bool) *SiteCreate {
	if b != nil {
		sc.SetIsVerified(*b)
	}
	return sc
}

// SetVerifiedAt sets the "verified_at" field.
func (sc *SiteCreate) SetVerifiedAt(t time.Time) *SiteCreate {
	sc.mutation.SetVerifiedAt(t)
	return sc
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (sc *SiteCreate) SetNillableVerifiedAt(t *time.Time) *SiteCreate {
	if t != nil {
		sc.SetVerifiedAt(*t)
	}
	return sc
}

// SetID sets the "id" field.
func (sc *SiteCreate) SetID(i int64) *SiteCreate {
	sc.mutation.SetID(i)
	return sc
}

// AddFunnelIDs adds the "funnels" edge to the Funnel entity by IDs.
func (sc *SiteCreate) AddFunnelIDs(ids ...int64) *SiteCreate {
	sc.mutation.AddFunnelIDs(ids...)
	return sc
}

// AddFunnels adds the "funnels" edges to the Funnel entity.
func (sc *SiteCreate) AddFunnels(f ...*Funnel) *SiteCreate {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return sc.AddFunnelIDs(ids...)
}

// AddMemberIDs adds the "members" edge to the User entity by IDs.
func (sc *SiteCreate) AddMemberIDs(ids ...int64) *SiteCreate {
	sc.mutation.AddMemberIDs(ids...)
	return sc
}

// AddMembers adds the "members" edges to the User entity.
func (sc *SiteCreate) AddMembers(u ...*User) *SiteCreate {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return sc.AddMemberIDs(ids...)
}

// AddGoalIDs adds the "goals" edge to the Goal entity by IDs.
func (sc *SiteCreate) AddGoalIDs(ids ...int64) *SiteCreate {
	sc.mutation.AddGoalIDs(ids...)
	return sc
}

// AddGoals adds the "goals" edges to the Goal entity.
func (sc *SiteCreate) AddGoals(g ...*Goal) *SiteCreate {
	ids := make([]int64, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return sc.AddGoalIDs(ids...)
}

// AddSiteMembershipIDs adds the "site_memberships" edge to the SiteMembership entity by IDs.
func (sc *SiteCreate) AddSiteMembershipIDs(ids ...int64) *SiteCreate {
	sc.mutation.AddSiteMembershipIDs(ids...)
	return sc
}

// AddSiteMemberships adds the "site_memberships" edges to the SiteMembership entity.
func (sc *SiteCreate) AddSiteMemberships(s ...*SiteMembership) *SiteCreate {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sc.AddSiteMembershipIDs(ids...)
}

// AddShieldRulesIPIDs adds the "shield_rules_ip" edge to the ShieldRulesIp entity by IDs.
func (sc *SiteCreate) AddShieldRulesIPIDs(ids ...int64) *SiteCreate {
	sc.mutation.AddShieldRulesIPIDs(ids...)
	return sc
}

// AddShieldRulesIP adds the "shield_rules_ip" edges to the ShieldRulesIp entity.
func (sc *SiteCreate) AddShieldRulesIP(s ...*ShieldRulesIp) *SiteCreate {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sc.AddShieldRulesIPIDs(ids...)
}

// AddShieldRulesHostnameIDs adds the "shield_rules_hostname" edge to the ShieldRulesHostname entity by IDs.
func (sc *SiteCreate) AddShieldRulesHostnameIDs(ids ...int64) *SiteCreate {
	sc.mutation.AddShieldRulesHostnameIDs(ids...)
	return sc
}

// AddShieldRulesHostname adds the "shield_rules_hostname" edges to the ShieldRulesHostname entity.
func (sc *SiteCreate) AddShieldRulesHostname(s ...*ShieldRulesHostname) *SiteCreate {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sc.AddShieldRulesHostnameIDs(ids...)
}

// AddShieldRulesCountryIDs adds the "shield_rules_country" edge to the ShieldRulesCountry entity by IDs.
func (sc *SiteCreate) AddShieldRulesCountryIDs(ids ...int64) *SiteCreate {
	sc.mutation.AddShieldRulesCountryIDs(ids...)
	return sc
}

// AddShieldRulesCountry adds the "shield_rules_country" edges to the ShieldRulesCountry entity.
func (sc *SiteCreate) AddShieldRulesCountry(s ...*ShieldRulesCountry) *SiteCreate {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sc.AddShieldRulesCountryIDs(ids...)
}

// Mutation returns the SiteMutation object of the builder.
func (sc *SiteCreate) Mutation() *SiteMutation {
	return sc.mutation
}

// Save creates the Site in the database.
func (sc *SiteCreate) Save(ctx context.Context) (*Site, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SiteCreate) SaveX(ctx context.Context) *Site {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SiteCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SiteCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SiteCreate) defaults() {
	if _, ok := sc.mutation.Timezone(); !ok {
		v := site.DefaultTimezone
		sc.mutation.SetTimezone(v)
	}
	if _, ok := sc.mutation.Public(); !ok {
		v := site.DefaultPublic
		sc.mutation.SetPublic(v)
	}
	if _, ok := sc.mutation.IngestRateLimitScaleSeconds(); !ok {
		v := site.DefaultIngestRateLimitScaleSeconds
		sc.mutation.SetIngestRateLimitScaleSeconds(v)
	}
	if _, ok := sc.mutation.IngestLimitPerMinute(); !ok {
		v := site.DefaultIngestLimitPerMinute
		sc.mutation.SetIngestLimitPerMinute(v)
	}
	if _, ok := sc.mutation.CreatedAt(); !ok {
		v := site.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		v := site.DefaultUpdatedAt()
		sc.mutation.SetUpdatedAt(v)
	}
	if _, ok := sc.mutation.IsVerified(); !ok {
		v := site.DefaultIsVerified
		sc.mutation.SetIsVerified(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SiteCreate) check() error {
	if _, ok := sc.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "Site.domain"`)}
	}
	if v, ok := sc.mutation.Domain(); ok {
		if err := site.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "Site.domain": %w`, err)}
		}
	}
	if v, ok := sc.mutation.Remark(); ok {
		if err := site.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "Site.remark": %w`, err)}
		}
	}
	if _, ok := sc.mutation.Timezone(); !ok {
		return &ValidationError{Name: "timezone", err: errors.New(`ent: missing required field "Site.timezone"`)}
	}
	if v, ok := sc.mutation.Timezone(); ok {
		if err := site.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "Site.timezone": %w`, err)}
		}
	}
	if _, ok := sc.mutation.Public(); !ok {
		return &ValidationError{Name: "public", err: errors.New(`ent: missing required field "Site.public"`)}
	}
	if _, ok := sc.mutation.IngestRateLimitScaleSeconds(); !ok {
		return &ValidationError{Name: "ingest_rate_limit_scale_seconds", err: errors.New(`ent: missing required field "Site.ingest_rate_limit_scale_seconds"`)}
	}
	if _, ok := sc.mutation.IngestLimitPerMinute(); !ok {
		return &ValidationError{Name: "ingest_limit_per_minute", err: errors.New(`ent: missing required field "Site.ingest_limit_per_minute"`)}
	}
	if v, ok := sc.mutation.AllowedOrigins(); ok {
		if err := site.AllowedOriginsValidator(v); err != nil {
			return &ValidationError{Name: "allowed_origins", err: fmt.Errorf(`ent: validator failed for field "Site.allowed_origins": %w`, err)}
		}
	}
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Site.created_at"`)}
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Site.updated_at"`)}
	}
	if _, ok := sc.mutation.VerificationToken(); !ok {
		return &ValidationError{Name: "verification_token", err: errors.New(`ent: missing required field "Site.verification_token"`)}
	}
	if v, ok := sc.mutation.VerificationToken(); ok {
		if err := site.VerificationTokenValidator(v); err != nil {
			return &ValidationError{Name: "verification_token", err: fmt.Errorf(`ent: validator failed for field "Site.verification_token": %w`, err)}
		}
	}
	if _, ok := sc.mutation.IsVerified(); !ok {
		return &ValidationError{Name: "is_verified", err: errors.New(`ent: missing required field "Site.is_verified"`)}
	}
	return nil
}

func (sc *SiteCreate) sqlSave(ctx context.Context) (*Site, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SiteCreate) createSpec() (*Site, *sqlgraph.CreateSpec) {
	var (
		_node = &Site{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(site.Table, sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt64))
	)
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sc.mutation.Domain(); ok {
		_spec.SetField(site.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := sc.mutation.Remark(); ok {
		_spec.SetField(site.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	if value, ok := sc.mutation.Timezone(); ok {
		_spec.SetField(site.FieldTimezone, field.TypeString, value)
		_node.Timezone = value
	}
	if value, ok := sc.mutation.Public(); ok {
		_spec.SetField(site.FieldPublic, field.TypeBool, value)
		_node.Public = value
	}
	if value, ok := sc.mutation.StatsStartDate(); ok {
		_spec.SetField(site.FieldStatsStartDate, field.TypeTime, value)
		_node.StatsStartDate = &value
	}
	if value, ok := sc.mutation.IngestRateLimitScaleSeconds(); ok {
		_spec.SetField(site.FieldIngestRateLimitScaleSeconds, field.TypeInt, value)
		_node.IngestRateLimitScaleSeconds = value
	}
	if value, ok := sc.mutation.IngestLimitPerMinute(); ok {
		_spec.SetField(site.FieldIngestLimitPerMinute, field.TypeInt, value)
		_node.IngestLimitPerMinute = value
	}
	if value, ok := sc.mutation.AllowedOrigins(); ok {
		_spec.SetField(site.FieldAllowedOrigins, field.TypeString, value)
		_node.AllowedOrigins = value
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(site.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sc.mutation.UpdatedAt(); ok {
		_spec.SetField(site.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := sc.mutation.VerificationToken(); ok {
		_spec.SetField(site.FieldVerificationToken, field.TypeString, value)
		_node.VerificationToken = value
	}
	if value, ok := sc.mutation.IsVerified(); ok {
		_spec.SetField(site.FieldIsVerified, field.TypeBool, value)
		_node.IsVerified = value
	}
	if value, ok := sc.mutation.VerifiedAt(); ok {
		_spec.SetField(site.FieldVerifiedAt, field.TypeTime, value)
		_node.VerifiedAt = &value
	}
	if nodes := sc.mutation.FunnelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.FunnelsTable,
			Columns: []string{site.FunnelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(funnel.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.MembersTable,
			Columns: []string{site.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.GoalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.GoalsTable,
			Columns: []string{site.GoalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goal.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.SiteMembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.SiteMembershipsTable,
			Columns: []string{site.SiteMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitemembership.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.ShieldRulesIPIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.ShieldRulesIPTable,
			Columns: []string{site.ShieldRulesIPColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shieldrulesip.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.ShieldRulesHostnameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.ShieldRulesHostnameTable,
			Columns: []string{site.ShieldRulesHostnameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shieldruleshostname.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.ShieldRulesCountryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.ShieldRulesCountryTable,
			Columns: []string{site.ShieldRulesCountryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shieldrulescountry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SiteCreateBulk is the builder for creating many Site entities in bulk.
type SiteCreateBulk struct {
	config
	err      error
	builders []*SiteCreate
}

// Save creates the Site entities in the database.
func (scb *SiteCreateBulk) Save(ctx context.Context) ([]*Site, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Site, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SiteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SiteCreateBulk) SaveX(ctx context.Context) []*Site {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SiteCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SiteCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
