// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/predicate"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/subaccount"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/user"
)

// SubAccountUpdate is the builder for updating SubAccount entities.
type SubAccountUpdate struct {
	config
	hooks    []Hook
	mutation *SubAccountMutation
}

// Where appends a list predicates to the SubAccountUpdate builder.
func (sau *SubAccountUpdate) Where(ps ...predicate.SubAccount) *SubAccountUpdate {
	sau.mutation.Where(ps...)
	return sau
}

// SetParentUserID sets the "parent_user_id" field.
func (sau *SubAccountUpdate) SetParentUserID(i int64) *SubAccountUpdate {
	sau.mutation.SetParentUserID(i)
	return sau
}

// SetNillableParentUserID sets the "parent_user_id" field if the given value is not nil.
func (sau *SubAccountUpdate) SetNillableParentUserID(i *int64) *SubAccountUpdate {
	if i != nil {
		sau.SetParentUserID(*i)
	}
	return sau
}

// SetEmail sets the "email" field.
func (sau *SubAccountUpdate) SetEmail(s string) *SubAccountUpdate {
	sau.mutation.SetEmail(s)
	return sau
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (sau *SubAccountUpdate) SetNillableEmail(s *string) *SubAccountUpdate {
	if s != nil {
		sau.SetEmail(*s)
	}
	return sau
}

// SetPasswordHash sets the "password_hash" field.
func (sau *SubAccountUpdate) SetPasswordHash(s string) *SubAccountUpdate {
	sau.mutation.SetPasswordHash(s)
	return sau
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (sau *SubAccountUpdate) SetNillablePasswordHash(s *string) *SubAccountUpdate {
	if s != nil {
		sau.SetPasswordHash(*s)
	}
	return sau
}

// SetName sets the "name" field.
func (sau *SubAccountUpdate) SetName(s string) *SubAccountUpdate {
	sau.mutation.SetName(s)
	return sau
}

// SetNillableName sets the "name" field if the given value is not nil.
func (sau *SubAccountUpdate) SetNillableName(s *string) *SubAccountUpdate {
	if s != nil {
		sau.SetName(*s)
	}
	return sau
}

// ClearName clears the value of the "name" field.
func (sau *SubAccountUpdate) ClearName() *SubAccountUpdate {
	sau.mutation.ClearName()
	return sau
}

// SetRole sets the "role" field.
func (sau *SubAccountUpdate) SetRole(s string) *SubAccountUpdate {
	sau.mutation.SetRole(s)
	return sau
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (sau *SubAccountUpdate) SetNillableRole(s *string) *SubAccountUpdate {
	if s != nil {
		sau.SetRole(*s)
	}
	return sau
}

// SetStatus sets the "status" field.
func (sau *SubAccountUpdate) SetStatus(s string) *SubAccountUpdate {
	sau.mutation.SetStatus(s)
	return sau
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (sau *SubAccountUpdate) SetNillableStatus(s *string) *SubAccountUpdate {
	if s != nil {
		sau.SetStatus(*s)
	}
	return sau
}

// SetLastSeen sets the "last_seen" field.
func (sau *SubAccountUpdate) SetLastSeen(t time.Time) *SubAccountUpdate {
	sau.mutation.SetLastSeen(t)
	return sau
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (sau *SubAccountUpdate) SetNillableLastSeen(t *time.Time) *SubAccountUpdate {
	if t != nil {
		sau.SetLastSeen(*t)
	}
	return sau
}

// ClearLastSeen clears the value of the "last_seen" field.
func (sau *SubAccountUpdate) ClearLastSeen() *SubAccountUpdate {
	sau.mutation.ClearLastSeen()
	return sau
}

// SetUpdatedAt sets the "updated_at" field.
func (sau *SubAccountUpdate) SetUpdatedAt(t time.Time) *SubAccountUpdate {
	sau.mutation.SetUpdatedAt(t)
	return sau
}

// SetParentUser sets the "parent_user" edge to the User entity.
func (sau *SubAccountUpdate) SetParentUser(u *User) *SubAccountUpdate {
	return sau.SetParentUserID(u.ID)
}

// Mutation returns the SubAccountMutation object of the builder.
func (sau *SubAccountUpdate) Mutation() *SubAccountMutation {
	return sau.mutation
}

// ClearParentUser clears the "parent_user" edge to the User entity.
func (sau *SubAccountUpdate) ClearParentUser() *SubAccountUpdate {
	sau.mutation.ClearParentUser()
	return sau
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (sau *SubAccountUpdate) Save(ctx context.Context) (int, error) {
	sau.defaults()
	return withHooks(ctx, sau.sqlSave, sau.mutation, sau.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sau *SubAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := sau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (sau *SubAccountUpdate) Exec(ctx context.Context) error {
	_, err := sau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sau *SubAccountUpdate) ExecX(ctx context.Context) {
	if err := sau.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sau *SubAccountUpdate) defaults() {
	if _, ok := sau.mutation.UpdatedAt(); !ok {
		v := subaccount.UpdateDefaultUpdatedAt()
		sau.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sau *SubAccountUpdate) check() error {
	if v, ok := sau.mutation.Email(); ok {
		if err := subaccount.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "SubAccount.email": %w`, err)}
		}
	}
	if v, ok := sau.mutation.PasswordHash(); ok {
		if err := subaccount.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "SubAccount.password_hash": %w`, err)}
		}
	}
	if v, ok := sau.mutation.Name(); ok {
		if err := subaccount.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SubAccount.name": %w`, err)}
		}
	}
	if v, ok := sau.mutation.Role(); ok {
		if err := subaccount.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "SubAccount.role": %w`, err)}
		}
	}
	if v, ok := sau.mutation.Status(); ok {
		if err := subaccount.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubAccount.status": %w`, err)}
		}
	}
	if sau.mutation.ParentUserCleared() && len(sau.mutation.ParentUserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubAccount.parent_user"`)
	}
	return nil
}

func (sau *SubAccountUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := sau.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(subaccount.Table, subaccount.Columns, sqlgraph.NewFieldSpec(subaccount.FieldID, field.TypeInt64))
	if ps := sau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sau.mutation.Email(); ok {
		_spec.SetField(subaccount.FieldEmail, field.TypeString, value)
	}
	if value, ok := sau.mutation.PasswordHash(); ok {
		_spec.SetField(subaccount.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := sau.mutation.Name(); ok {
		_spec.SetField(subaccount.FieldName, field.TypeString, value)
	}
	if sau.mutation.NameCleared() {
		_spec.ClearField(subaccount.FieldName, field.TypeString)
	}
	if value, ok := sau.mutation.Role(); ok {
		_spec.SetField(subaccount.FieldRole, field.TypeString, value)
	}
	if value, ok := sau.mutation.Status(); ok {
		_spec.SetField(subaccount.FieldStatus, field.TypeString, value)
	}
	if value, ok := sau.mutation.LastSeen(); ok {
		_spec.SetField(subaccount.FieldLastSeen, field.TypeTime, value)
	}
	if sau.mutation.LastSeenCleared() {
		_spec.ClearField(subaccount.FieldLastSeen, field.TypeTime)
	}
	if value, ok := sau.mutation.UpdatedAt(); ok {
		_spec.SetField(subaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if sau.mutation.ParentUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subaccount.ParentUserTable,
			Columns: []string{subaccount.ParentUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sau.mutation.ParentUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subaccount.ParentUserTable,
			Columns: []string{subaccount.ParentUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, sau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	sau.mutation.done = true
	return n, nil
}

// SubAccountUpdateOne is the builder for updating a single SubAccount entity.
type SubAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubAccountMutation
}

// SetParentUserID sets the "parent_user_id" field.
func (sauo *SubAccountUpdateOne) SetParentUserID(i int64) *SubAccountUpdateOne {
	sauo.mutation.SetParentUserID(i)
	return sauo
}

// SetNillableParentUserID sets the "parent_user_id" field if the given value is not nil.
func (sauo *SubAccountUpdateOne) SetNillableParentUserID(i *int64) *SubAccountUpdateOne {
	if i != nil {
		sauo.SetParentUserID(*i)
	}
	return sauo
}

// SetEmail sets the "email" field.
func (sauo *SubAccountUpdateOne) SetEmail(s string) *SubAccountUpdateOne {
	sauo.mutation.SetEmail(s)
	return sauo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (sauo *SubAccountUpdateOne) SetNillableEmail(s *string) *SubAccountUpdateOne {
	if s != nil {
		sauo.SetEmail(*s)
	}
	return sauo
}

// SetPasswordHash sets the "password_hash" field.
func (sauo *SubAccountUpdateOne) SetPasswordHash(s string) *SubAccountUpdateOne {
	sauo.mutation.SetPasswordHash(s)
	return sauo
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (sauo *SubAccountUpdateOne) SetNillablePasswordHash(s *string) *SubAccountUpdateOne {
	if s != nil {
		sauo.SetPasswordHash(*s)
	}
	return sauo
}

// SetName sets the "name" field.
func (sauo *SubAccountUpdateOne) SetName(s string) *SubAccountUpdateOne {
	sauo.mutation.SetName(s)
	return sauo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (sauo *SubAccountUpdateOne) SetNillableName(s *string) *SubAccountUpdateOne {
	if s != nil {
		sauo.SetName(*s)
	}
	return sauo
}

// ClearName clears the value of the "name" field.
func (sauo *SubAccountUpdateOne) ClearName() *SubAccountUpdateOne {
	sauo.mutation.ClearName()
	return sauo
}

// SetRole sets the "role" field.
func (sauo *SubAccountUpdateOne) SetRole(s string) *SubAccountUpdateOne {
	sauo.mutation.SetRole(s)
	return sauo
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (sauo *SubAccountUpdateOne) SetNillableRole(s *string) *SubAccountUpdateOne {
	if s != nil {
		sauo.SetRole(*s)
	}
	return sauo
}

// SetStatus sets the "status" field.
func (sauo *SubAccountUpdateOne) SetStatus(s string) *SubAccountUpdateOne {
	sauo.mutation.SetStatus(s)
	return sauo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (sauo *SubAccountUpdateOne) SetNillableStatus(s *string) *SubAccountUpdateOne {
	if s != nil {
		sauo.SetStatus(*s)
	}
	return sauo
}

// SetLastSeen sets the "last_seen" field.
func (sauo *SubAccountUpdateOne) SetLastSeen(t time.Time) *SubAccountUpdateOne {
	sauo.mutation.SetLastSeen(t)
	return sauo
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (sauo *SubAccountUpdateOne) SetNillableLastSeen(t *time.Time) *SubAccountUpdateOne {
	if t != nil {
		sauo.SetLastSeen(*t)
	}
	return sauo
}

// ClearLastSeen clears the value of the "last_seen" field.
func (sauo *SubAccountUpdateOne) ClearLastSeen() *SubAccountUpdateOne {
	sauo.mutation.ClearLastSeen()
	return sauo
}

// SetUpdatedAt sets the "updated_at" field.
func (sauo *SubAccountUpdateOne) SetUpdatedAt(t time.Time) *SubAccountUpdateOne {
	sauo.mutation.SetUpdatedAt(t)
	return sauo
}

// SetParentUser sets the "parent_user" edge to the User entity.
func (sauo *SubAccountUpdateOne) SetParentUser(u *User) *SubAccountUpdateOne {
	return sauo.SetParentUserID(u.ID)
}

// Mutation returns the SubAccountMutation object of the builder.
func (sauo *SubAccountUpdateOne) Mutation() *SubAccountMutation {
	return sauo.mutation
}

// ClearParentUser clears the "parent_user" edge to the User entity.
func (sauo *SubAccountUpdateOne) ClearParentUser() *SubAccountUpdateOne {
	sauo.mutation.ClearParentUser()
	return sauo
}

// Where appends a list predicates to the SubAccountUpdate builder.
func (sauo *SubAccountUpdateOne) Where(ps ...predicate.SubAccount) *SubAccountUpdateOne {
	sauo.mutation.Where(ps...)
	return sauo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (sauo *SubAccountUpdateOne) Select(field string, fields ...string) *SubAccountUpdateOne {
	sauo.fields = append([]string{field}, fields...)
	return sauo
}

// Save executes the query and returns the updated SubAccount entity.
func (sauo *SubAccountUpdateOne) Save(ctx context.Context) (*SubAccount, error) {
	sauo.defaults()
	return withHooks(ctx, sauo.sqlSave, sauo.mutation, sauo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sauo *SubAccountUpdateOne) SaveX(ctx context.Context) *SubAccount {
	node, err := sauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (sauo *SubAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := sauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sauo *SubAccountUpdateOne) ExecX(ctx context.Context) {
	if err := sauo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sauo *SubAccountUpdateOne) defaults() {
	if _, ok := sauo.mutation.UpdatedAt(); !ok {
		v := subaccount.UpdateDefaultUpdatedAt()
		sauo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sauo *SubAccountUpdateOne) check() error {
	if v, ok := sauo.mutation.Email(); ok {
		if err := subaccount.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "SubAccount.email": %w`, err)}
		}
	}
	if v, ok := sauo.mutation.PasswordHash(); ok {
		if err := subaccount.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "SubAccount.password_hash": %w`, err)}
		}
	}
	if v, ok := sauo.mutation.Name(); ok {
		if err := subaccount.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SubAccount.name": %w`, err)}
		}
	}
	if v, ok := sauo.mutation.Role(); ok {
		if err := subaccount.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "SubAccount.role": %w`, err)}
		}
	}
	if v, ok := sauo.mutation.Status(); ok {
		if err := subaccount.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubAccount.status": %w`, err)}
		}
	}
	if sauo.mutation.ParentUserCleared() && len(sauo.mutation.ParentUserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubAccount.parent_user"`)
	}
	return nil
}

func (sauo *SubAccountUpdateOne) sqlSave(ctx context.Context) (_node *SubAccount, err error) {
	if err := sauo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subaccount.Table, subaccount.Columns, sqlgraph.NewFieldSpec(subaccount.FieldID, field.TypeInt64))
	id, ok := sauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := sauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subaccount.FieldID)
		for _, f := range fields {
			if !subaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := sauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sauo.mutation.Email(); ok {
		_spec.SetField(subaccount.FieldEmail, field.TypeString, value)
	}
	if value, ok := sauo.mutation.PasswordHash(); ok {
		_spec.SetField(subaccount.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := sauo.mutation.Name(); ok {
		_spec.SetField(subaccount.FieldName, field.TypeString, value)
	}
	if sauo.mutation.NameCleared() {
		_spec.ClearField(subaccount.FieldName, field.TypeString)
	}
	if value, ok := sauo.mutation.Role(); ok {
		_spec.SetField(subaccount.FieldRole, field.TypeString, value)
	}
	if value, ok := sauo.mutation.Status(); ok {
		_spec.SetField(subaccount.FieldStatus, field.TypeString, value)
	}
	if value, ok := sauo.mutation.LastSeen(); ok {
		_spec.SetField(subaccount.FieldLastSeen, field.TypeTime, value)
	}
	if sauo.mutation.LastSeenCleared() {
		_spec.ClearField(subaccount.FieldLastSeen, field.TypeTime)
	}
	if value, ok := sauo.mutation.UpdatedAt(); ok {
		_spec.SetField(subaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if sauo.mutation.ParentUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subaccount.ParentUserTable,
			Columns: []string{subaccount.ParentUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sauo.mutation.ParentUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subaccount.ParentUserTable,
			Columns: []string{subaccount.ParentUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubAccount{config: sauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, sauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	sauo.mutation.done = true
	return _node, nil
}
