// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/systemconfig"
)

// SystemConfigCreate is the builder for creating a SystemConfig entity.
type SystemConfigCreate struct {
	config
	mutation *SystemConfigMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (scc *SystemConfigCreate) SetKey(s string) *SystemConfigCreate {
	scc.mutation.SetKey(s)
	return scc
}

// SetValue sets the "value" field.
func (scc *SystemConfigCreate) SetValue(s string) *SystemConfigCreate {
	scc.mutation.SetValue(s)
	return scc
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (scc *SystemConfigCreate) SetNillableValue(s *string) *SystemConfigCreate {
	if s != nil {
		scc.SetValue(*s)
	}
	return scc
}

// SetDescription sets the "description" field.
func (scc *SystemConfigCreate) SetDescription(s string) *SystemConfigCreate {
	scc.mutation.SetDescription(s)
	return scc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (scc *SystemConfigCreate) SetNillableDescription(s *string) *SystemConfigCreate {
	if s != nil {
		scc.SetDescription(*s)
	}
	return scc
}

// SetGroupName sets the "group_name" field.
func (scc *SystemConfigCreate) SetGroupName(s string) *SystemConfigCreate {
	scc.mutation.SetGroupName(s)
	return scc
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (scc *SystemConfigCreate) SetNillableGroupName(s *string) *SystemConfigCreate {
	if s != nil {
		scc.SetGroupName(*s)
	}
	return scc
}

// SetUpdatedAt sets the "updated_at" field.
func (scc *SystemConfigCreate) SetUpdatedAt(t time.Time) *SystemConfigCreate {
	scc.mutation.SetUpdatedAt(t)
	return scc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (scc *SystemConfigCreate) SetNillableUpdatedAt(t *time.Time) *SystemConfigCreate {
	if t != nil {
		scc.SetUpdatedAt(*t)
	}
	return scc
}

// Mutation returns the SystemConfigMutation object of the builder.
func (scc *SystemConfigCreate) Mutation() *SystemConfigMutation {
	return scc.mutation
}

// Save creates the SystemConfig in the database.
func (scc *SystemConfigCreate) Save(ctx context.Context) (*SystemConfig, error) {
	scc.defaults()
	return withHooks(ctx, scc.sqlSave, scc.mutation, scc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (scc *SystemConfigCreate) SaveX(ctx context.Context) *SystemConfig {
	v, err := scc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scc *SystemConfigCreate) Exec(ctx context.Context) error {
	_, err := scc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scc *SystemConfigCreate) ExecX(ctx context.Context) {
	if err := scc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (scc *SystemConfigCreate) defaults() {
	if _, ok := scc.mutation.GroupName(); !ok {
		v := systemconfig.DefaultGroupName
		scc.mutation.SetGroupName(v)
	}
	if _, ok := scc.mutation.UpdatedAt(); !ok {
		v := systemconfig.DefaultUpdatedAt()
		scc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (scc *SystemConfigCreate) check() error {
	if _, ok := scc.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "SystemConfig.key"`)}
	}
	if v, ok := scc.mutation.Key(); ok {
		if err := systemconfig.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "SystemConfig.key": %w`, err)}
		}
	}
	if v, ok := scc.mutation.Description(); ok {
		if err := systemconfig.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "SystemConfig.description": %w`, err)}
		}
	}
	if _, ok := scc.mutation.GroupName(); !ok {
		return &ValidationError{Name: "group_name", err: errors.New(`ent: missing required field "SystemConfig.group_name"`)}
	}
	if v, ok := scc.mutation.GroupName(); ok {
		if err := systemconfig.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "SystemConfig.group_name": %w`, err)}
		}
	}
	if _, ok := scc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SystemConfig.updated_at"`)}
	}
	return nil
}

func (scc *SystemConfigCreate) sqlSave(ctx context.Context) (*SystemConfig, error) {
	if err := scc.check(); err != nil {
		return nil, err
	}
	_node, _spec := scc.createSpec()
	if err := sqlgraph.CreateNode(ctx, scc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	scc.mutation.id = &_node.ID
	scc.mutation.done = true
	return _node, nil
}

func (scc *SystemConfigCreate) createSpec() (*SystemConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &SystemConfig{config: scc.config}
		_spec = sqlgraph.NewCreateSpec(systemconfig.Table, sqlgraph.NewFieldSpec(systemconfig.FieldID, field.TypeInt))
	)
	if value, ok := scc.mutation.Key(); ok {
		_spec.SetField(systemconfig.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := scc.mutation.Value(); ok {
		_spec.SetField(systemconfig.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := scc.mutation.Description(); ok {
		_spec.SetField(systemconfig.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := scc.mutation.GroupName(); ok {
		_spec.SetField(systemconfig.FieldGroupName, field.TypeString, value)
		_node.GroupName = value
	}
	if value, ok := scc.mutation.UpdatedAt(); ok {
		_spec.SetField(systemconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// SystemConfigCreateBulk is the builder for creating many SystemConfig entities in bulk.
type SystemConfigCreateBulk struct {
	config
	err      error
	builders []*SystemConfigCreate
}

// Save creates the SystemConfig entities in the database.
func (sccb *SystemConfigCreateBulk) Save(ctx context.Context) ([]*SystemConfig, error) {
	if sccb.err != nil {
		return nil, sccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(sccb.builders))
	nodes := make([]*SystemConfig, len(sccb.builders))
	mutators := make([]Mutator, len(sccb.builders))
	for i := range sccb.builders {
		func(i int, root context.Context) {
			builder := sccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SystemConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sccb *SystemConfigCreateBulk) SaveX(ctx context.Context) []*SystemConfig {
	v, err := sccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sccb *SystemConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := sccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sccb *SystemConfigCreateBulk) ExecX(ctx context.Context) {
	if err := sccb.Exec(ctx); err != nil {
		panic(err)
	}
}
