// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/predicate"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/userconfig"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/usergroup"
)

// UserGroupUpdate is the builder for updating UserGroup entities.
type UserGroupUpdate struct {
	config
	hooks    []Hook
	mutation *UserGroupMutation
}

// Where appends a list predicates to the UserGroupUpdate builder.
func (ugu *UserGroupUpdate) Where(ps ...predicate.UserGroup) *UserGroupUpdate {
	ugu.mutation.Where(ps...)
	return ugu
}

// SetName sets the "name" field.
func (ugu *UserGroupUpdate) SetName(s string) *UserGroupUpdate {
	ugu.mutation.SetName(s)
	return ugu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ugu *UserGroupUpdate) SetNillableName(s *string) *UserGroupUpdate {
	if s != nil {
		ugu.SetName(*s)
	}
	return ugu
}

// SetDescription sets the "description" field.
func (ugu *UserGroupUpdate) SetDescription(s string) *UserGroupUpdate {
	ugu.mutation.SetDescription(s)
	return ugu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ugu *UserGroupUpdate) SetNillableDescription(s *string) *UserGroupUpdate {
	if s != nil {
		ugu.SetDescription(*s)
	}
	return ugu
}

// ClearDescription clears the value of the "description" field.
func (ugu *UserGroupUpdate) ClearDescription() *UserGroupUpdate {
	ugu.mutation.ClearDescription()
	return ugu
}

// SetMaxSites sets the "max_sites" field.
func (ugu *UserGroupUpdate) SetMaxSites(i int) *UserGroupUpdate {
	ugu.mutation.ResetMaxSites()
	ugu.mutation.SetMaxSites(i)
	return ugu
}

// SetNillableMaxSites sets the "max_sites" field if the given value is not nil.
func (ugu *UserGroupUpdate) SetNillableMaxSites(i *int) *UserGroupUpdate {
	if i != nil {
		ugu.SetMaxSites(*i)
	}
	return ugu
}

// AddMaxSites adds i to the "max_sites" field.
func (ugu *UserGroupUpdate) AddMaxSites(i int) *UserGroupUpdate {
	ugu.mutation.AddMaxSites(i)
	return ugu
}

// SetMaxMonthlyEvents sets the "max_monthly_events" field.
func (ugu *UserGroupUpdate) SetMaxMonthlyEvents(i int) *UserGroupUpdate {
	ugu.mutation.ResetMaxMonthlyEvents()
	ugu.mutation.SetMaxMonthlyEvents(i)
	return ugu
}

// SetNillableMaxMonthlyEvents sets the "max_monthly_events" field if the given value is not nil.
func (ugu *UserGroupUpdate) SetNillableMaxMonthlyEvents(i *int) *UserGroupUpdate {
	if i != nil {
		ugu.SetMaxMonthlyEvents(*i)
	}
	return ugu
}

// AddMaxMonthlyEvents adds i to the "max_monthly_events" field.
func (ugu *UserGroupUpdate) AddMaxMonthlyEvents(i int) *UserGroupUpdate {
	ugu.mutation.AddMaxMonthlyEvents(i)
	return ugu
}

// SetMaxAPIKeys sets the "max_api_keys" field.
func (ugu *UserGroupUpdate) SetMaxAPIKeys(i int) *UserGroupUpdate {
	ugu.mutation.ResetMaxAPIKeys()
	ugu.mutation.SetMaxAPIKeys(i)
	return ugu
}

// SetNillableMaxAPIKeys sets the "max_api_keys" field if the given value is not nil.
func (ugu *UserGroupUpdate) SetNillableMaxAPIKeys(i *int) *UserGroupUpdate {
	if i != nil {
		ugu.SetMaxAPIKeys(*i)
	}
	return ugu
}

// AddMaxAPIKeys adds i to the "max_api_keys" field.
func (ugu *UserGroupUpdate) AddMaxAPIKeys(i int) *UserGroupUpdate {
	ugu.mutation.AddMaxAPIKeys(i)
	return ugu
}

// SetMaxSubAccounts sets the "max_sub_accounts" field.
func (ugu *UserGroupUpdate) SetMaxSubAccounts(i int) *UserGroupUpdate {
	ugu.mutation.ResetMaxSubAccounts()
	ugu.mutation.SetMaxSubAccounts(i)
	return ugu
}

// SetNillableMaxSubAccounts sets the "max_sub_accounts" field if the given value is not nil.
func (ugu *UserGroupUpdate) SetNillableMaxSubAccounts(i *int) *UserGroupUpdate {
	if i != nil {
		ugu.SetMaxSubAccounts(*i)
	}
	return ugu
}

// AddMaxSubAccounts adds i to the "max_sub_accounts" field.
func (ugu *UserGroupUpdate) AddMaxSubAccounts(i int) *UserGroupUpdate {
	ugu.mutation.AddMaxSubAccounts(i)
	return ugu
}

// SetCustomSearchEngines sets the "custom_search_engines" field.
func (ugu *UserGroupUpdate) SetCustomSearchEngines(b bool) *UserGroupUpdate {
	ugu.mutation.SetCustomSearchEngines(b)
	return ugu
}

// SetNillableCustomSearchEngines sets the "custom_search_engines" field if the given value is not nil.
func (ugu *UserGroupUpdate) SetNillableCustomSearchEngines(b *bool) *UserGroupUpdate {
	if b != nil {
		ugu.SetCustomSearchEngines(*b)
	}
	return ugu
}

// SetIsDefault sets the "is_default" field.
func (ugu *UserGroupUpdate) SetIsDefault(b bool) *UserGroupUpdate {
	ugu.mutation.SetIsDefault(b)
	return ugu
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (ugu *UserGroupUpdate) SetNillableIsDefault(b *bool) *UserGroupUpdate {
	if b != nil {
		ugu.SetIsDefault(*b)
	}
	return ugu
}

// SetPrice sets the "price" field.
func (ugu *UserGroupUpdate) SetPrice(f float64) *UserGroupUpdate {
	ugu.mutation.ResetPrice()
	ugu.mutation.SetPrice(f)
	return ugu
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (ugu *UserGroupUpdate) SetNillablePrice(f *float64) *UserGroupUpdate {
	if f != nil {
		ugu.SetPrice(*f)
	}
	return ugu
}

// AddPrice adds f to the "price" field.
func (ugu *UserGroupUpdate) AddPrice(f float64) *UserGroupUpdate {
	ugu.mutation.AddPrice(f)
	return ugu
}

// SetUpdatedAt sets the "updated_at" field.
func (ugu *UserGroupUpdate) SetUpdatedAt(t time.Time) *UserGroupUpdate {
	ugu.mutation.SetUpdatedAt(t)
	return ugu
}

// AddUserConfigIDs adds the "user_configs" edge to the UserConfig entity by IDs.
func (ugu *UserGroupUpdate) AddUserConfigIDs(ids ...int64) *UserGroupUpdate {
	ugu.mutation.AddUserConfigIDs(ids...)
	return ugu
}

// AddUserConfigs adds the "user_configs" edges to the UserConfig entity.
func (ugu *UserGroupUpdate) AddUserConfigs(u ...*UserConfig) *UserGroupUpdate {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ugu.AddUserConfigIDs(ids...)
}

// Mutation returns the UserGroupMutation object of the builder.
func (ugu *UserGroupUpdate) Mutation() *UserGroupMutation {
	return ugu.mutation
}

// ClearUserConfigs clears all "user_configs" edges to the UserConfig entity.
func (ugu *UserGroupUpdate) ClearUserConfigs() *UserGroupUpdate {
	ugu.mutation.ClearUserConfigs()
	return ugu
}

// RemoveUserConfigIDs removes the "user_configs" edge to UserConfig entities by IDs.
func (ugu *UserGroupUpdate) RemoveUserConfigIDs(ids ...int64) *UserGroupUpdate {
	ugu.mutation.RemoveUserConfigIDs(ids...)
	return ugu
}

// RemoveUserConfigs removes "user_configs" edges to UserConfig entities.
func (ugu *UserGroupUpdate) RemoveUserConfigs(u ...*UserConfig) *UserGroupUpdate {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ugu.RemoveUserConfigIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ugu *UserGroupUpdate) Save(ctx context.Context) (int, error) {
	ugu.defaults()
	return withHooks(ctx, ugu.sqlSave, ugu.mutation, ugu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ugu *UserGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := ugu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ugu *UserGroupUpdate) Exec(ctx context.Context) error {
	_, err := ugu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ugu *UserGroupUpdate) ExecX(ctx context.Context) {
	if err := ugu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ugu *UserGroupUpdate) defaults() {
	if _, ok := ugu.mutation.UpdatedAt(); !ok {
		v := usergroup.UpdateDefaultUpdatedAt()
		ugu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ugu *UserGroupUpdate) check() error {
	if v, ok := ugu.mutation.Name(); ok {
		if err := usergroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UserGroup.name": %w`, err)}
		}
	}
	return nil
}

func (ugu *UserGroupUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ugu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(usergroup.Table, usergroup.Columns, sqlgraph.NewFieldSpec(usergroup.FieldID, field.TypeInt64))
	if ps := ugu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ugu.mutation.Name(); ok {
		_spec.SetField(usergroup.FieldName, field.TypeString, value)
	}
	if value, ok := ugu.mutation.Description(); ok {
		_spec.SetField(usergroup.FieldDescription, field.TypeString, value)
	}
	if ugu.mutation.DescriptionCleared() {
		_spec.ClearField(usergroup.FieldDescription, field.TypeString)
	}
	if value, ok := ugu.mutation.MaxSites(); ok {
		_spec.SetField(usergroup.FieldMaxSites, field.TypeInt, value)
	}
	if value, ok := ugu.mutation.AddedMaxSites(); ok {
		_spec.AddField(usergroup.FieldMaxSites, field.TypeInt, value)
	}
	if value, ok := ugu.mutation.MaxMonthlyEvents(); ok {
		_spec.SetField(usergroup.FieldMaxMonthlyEvents, field.TypeInt, value)
	}
	if value, ok := ugu.mutation.AddedMaxMonthlyEvents(); ok {
		_spec.AddField(usergroup.FieldMaxMonthlyEvents, field.TypeInt, value)
	}
	if value, ok := ugu.mutation.MaxAPIKeys(); ok {
		_spec.SetField(usergroup.FieldMaxAPIKeys, field.TypeInt, value)
	}
	if value, ok := ugu.mutation.AddedMaxAPIKeys(); ok {
		_spec.AddField(usergroup.FieldMaxAPIKeys, field.TypeInt, value)
	}
	if value, ok := ugu.mutation.MaxSubAccounts(); ok {
		_spec.SetField(usergroup.FieldMaxSubAccounts, field.TypeInt, value)
	}
	if value, ok := ugu.mutation.AddedMaxSubAccounts(); ok {
		_spec.AddField(usergroup.FieldMaxSubAccounts, field.TypeInt, value)
	}
	if value, ok := ugu.mutation.CustomSearchEngines(); ok {
		_spec.SetField(usergroup.FieldCustomSearchEngines, field.TypeBool, value)
	}
	if value, ok := ugu.mutation.IsDefault(); ok {
		_spec.SetField(usergroup.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := ugu.mutation.Price(); ok {
		_spec.SetField(usergroup.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := ugu.mutation.AddedPrice(); ok {
		_spec.AddField(usergroup.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := ugu.mutation.UpdatedAt(); ok {
		_spec.SetField(usergroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if ugu.mutation.UserConfigsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usergroup.UserConfigsTable,
			Columns: []string{usergroup.UserConfigsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userconfig.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ugu.mutation.RemovedUserConfigsIDs(); len(nodes) > 0 && !ugu.mutation.UserConfigsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usergroup.UserConfigsTable,
			Columns: []string{usergroup.UserConfigsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userconfig.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ugu.mutation.UserConfigsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usergroup.UserConfigsTable,
			Columns: []string{usergroup.UserConfigsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userconfig.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ugu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usergroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ugu.mutation.done = true
	return n, nil
}

// UserGroupUpdateOne is the builder for updating a single UserGroup entity.
type UserGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserGroupMutation
}

// SetName sets the "name" field.
func (uguo *UserGroupUpdateOne) SetName(s string) *UserGroupUpdateOne {
	uguo.mutation.SetName(s)
	return uguo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (uguo *UserGroupUpdateOne) SetNillableName(s *string) *UserGroupUpdateOne {
	if s != nil {
		uguo.SetName(*s)
	}
	return uguo
}

// SetDescription sets the "description" field.
func (uguo *UserGroupUpdateOne) SetDescription(s string) *UserGroupUpdateOne {
	uguo.mutation.SetDescription(s)
	return uguo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (uguo *UserGroupUpdateOne) SetNillableDescription(s *string) *UserGroupUpdateOne {
	if s != nil {
		uguo.SetDescription(*s)
	}
	return uguo
}

// ClearDescription clears the value of the "description" field.
func (uguo *UserGroupUpdateOne) ClearDescription() *UserGroupUpdateOne {
	uguo.mutation.ClearDescription()
	return uguo
}

// SetMaxSites sets the "max_sites" field.
func (uguo *UserGroupUpdateOne) SetMaxSites(i int) *UserGroupUpdateOne {
	uguo.mutation.ResetMaxSites()
	uguo.mutation.SetMaxSites(i)
	return uguo
}

// SetNillableMaxSites sets the "max_sites" field if the given value is not nil.
func (uguo *UserGroupUpdateOne) SetNillableMaxSites(i *int) *UserGroupUpdateOne {
	if i != nil {
		uguo.SetMaxSites(*i)
	}
	return uguo
}

// AddMaxSites adds i to the "max_sites" field.
func (uguo *UserGroupUpdateOne) AddMaxSites(i int) *UserGroupUpdateOne {
	uguo.mutation.AddMaxSites(i)
	return uguo
}

// SetMaxMonthlyEvents sets the "max_monthly_events" field.
func (uguo *UserGroupUpdateOne) SetMaxMonthlyEvents(i int) *UserGroupUpdateOne {
	uguo.mutation.ResetMaxMonthlyEvents()
	uguo.mutation.SetMaxMonthlyEvents(i)
	return uguo
}

// SetNillableMaxMonthlyEvents sets the "max_monthly_events" field if the given value is not nil.
func (uguo *UserGroupUpdateOne) SetNillableMaxMonthlyEvents(i *int) *UserGroupUpdateOne {
	if i != nil {
		uguo.SetMaxMonthlyEvents(*i)
	}
	return uguo
}

// AddMaxMonthlyEvents adds i to the "max_monthly_events" field.
func (uguo *UserGroupUpdateOne) AddMaxMonthlyEvents(i int) *UserGroupUpdateOne {
	uguo.mutation.AddMaxMonthlyEvents(i)
	return uguo
}

// SetMaxAPIKeys sets the "max_api_keys" field.
func (uguo *UserGroupUpdateOne) SetMaxAPIKeys(i int) *UserGroupUpdateOne {
	uguo.mutation.ResetMaxAPIKeys()
	uguo.mutation.SetMaxAPIKeys(i)
	return uguo
}

// SetNillableMaxAPIKeys sets the "max_api_keys" field if the given value is not nil.
func (uguo *UserGroupUpdateOne) SetNillableMaxAPIKeys(i *int) *UserGroupUpdateOne {
	if i != nil {
		uguo.SetMaxAPIKeys(*i)
	}
	return uguo
}

// AddMaxAPIKeys adds i to the "max_api_keys" field.
func (uguo *UserGroupUpdateOne) AddMaxAPIKeys(i int) *UserGroupUpdateOne {
	uguo.mutation.AddMaxAPIKeys(i)
	return uguo
}

// SetMaxSubAccounts sets the "max_sub_accounts" field.
func (uguo *UserGroupUpdateOne) SetMaxSubAccounts(i int) *UserGroupUpdateOne {
	uguo.mutation.ResetMaxSubAccounts()
	uguo.mutation.SetMaxSubAccounts(i)
	return uguo
}

// SetNillableMaxSubAccounts sets the "max_sub_accounts" field if the given value is not nil.
func (uguo *UserGroupUpdateOne) SetNillableMaxSubAccounts(i *int) *UserGroupUpdateOne {
	if i != nil {
		uguo.SetMaxSubAccounts(*i)
	}
	return uguo
}

// AddMaxSubAccounts adds i to the "max_sub_accounts" field.
func (uguo *UserGroupUpdateOne) AddMaxSubAccounts(i int) *UserGroupUpdateOne {
	uguo.mutation.AddMaxSubAccounts(i)
	return uguo
}

// SetCustomSearchEngines sets the "custom_search_engines" field.
func (uguo *UserGroupUpdateOne) SetCustomSearchEngines(b bool) *UserGroupUpdateOne {
	uguo.mutation.SetCustomSearchEngines(b)
	return uguo
}

// SetNillableCustomSearchEngines sets the "custom_search_engines" field if the given value is not nil.
func (uguo *UserGroupUpdateOne) SetNillableCustomSearchEngines(b *bool) *UserGroupUpdateOne {
	if b != nil {
		uguo.SetCustomSearchEngines(*b)
	}
	return uguo
}

// SetIsDefault sets the "is_default" field.
func (uguo *UserGroupUpdateOne) SetIsDefault(b bool) *UserGroupUpdateOne {
	uguo.mutation.SetIsDefault(b)
	return uguo
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (uguo *UserGroupUpdateOne) SetNillableIsDefault(b *bool) *UserGroupUpdateOne {
	if b != nil {
		uguo.SetIsDefault(*b)
	}
	return uguo
}

// SetPrice sets the "price" field.
func (uguo *UserGroupUpdateOne) SetPrice(f float64) *UserGroupUpdateOne {
	uguo.mutation.ResetPrice()
	uguo.mutation.SetPrice(f)
	return uguo
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (uguo *UserGroupUpdateOne) SetNillablePrice(f *float64) *UserGroupUpdateOne {
	if f != nil {
		uguo.SetPrice(*f)
	}
	return uguo
}

// AddPrice adds f to the "price" field.
func (uguo *UserGroupUpdateOne) AddPrice(f float64) *UserGroupUpdateOne {
	uguo.mutation.AddPrice(f)
	return uguo
}

// SetUpdatedAt sets the "updated_at" field.
func (uguo *UserGroupUpdateOne) SetUpdatedAt(t time.Time) *UserGroupUpdateOne {
	uguo.mutation.SetUpdatedAt(t)
	return uguo
}

// AddUserConfigIDs adds the "user_configs" edge to the UserConfig entity by IDs.
func (uguo *UserGroupUpdateOne) AddUserConfigIDs(ids ...int64) *UserGroupUpdateOne {
	uguo.mutation.AddUserConfigIDs(ids...)
	return uguo
}

// AddUserConfigs adds the "user_configs" edges to the UserConfig entity.
func (uguo *UserGroupUpdateOne) AddUserConfigs(u ...*UserConfig) *UserGroupUpdateOne {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uguo.AddUserConfigIDs(ids...)
}

// Mutation returns the UserGroupMutation object of the builder.
func (uguo *UserGroupUpdateOne) Mutation() *UserGroupMutation {
	return uguo.mutation
}

// ClearUserConfigs clears all "user_configs" edges to the UserConfig entity.
func (uguo *UserGroupUpdateOne) ClearUserConfigs() *UserGroupUpdateOne {
	uguo.mutation.ClearUserConfigs()
	return uguo
}

// RemoveUserConfigIDs removes the "user_configs" edge to UserConfig entities by IDs.
func (uguo *UserGroupUpdateOne) RemoveUserConfigIDs(ids ...int64) *UserGroupUpdateOne {
	uguo.mutation.RemoveUserConfigIDs(ids...)
	return uguo
}

// RemoveUserConfigs removes "user_configs" edges to UserConfig entities.
func (uguo *UserGroupUpdateOne) RemoveUserConfigs(u ...*UserConfig) *UserGroupUpdateOne {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uguo.RemoveUserConfigIDs(ids...)
}

// Where appends a list predicates to the UserGroupUpdate builder.
func (uguo *UserGroupUpdateOne) Where(ps ...predicate.UserGroup) *UserGroupUpdateOne {
	uguo.mutation.Where(ps...)
	return uguo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uguo *UserGroupUpdateOne) Select(field string, fields ...string) *UserGroupUpdateOne {
	uguo.fields = append([]string{field}, fields...)
	return uguo
}

// Save executes the query and returns the updated UserGroup entity.
func (uguo *UserGroupUpdateOne) Save(ctx context.Context) (*UserGroup, error) {
	uguo.defaults()
	return withHooks(ctx, uguo.sqlSave, uguo.mutation, uguo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uguo *UserGroupUpdateOne) SaveX(ctx context.Context) *UserGroup {
	node, err := uguo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uguo *UserGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := uguo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uguo *UserGroupUpdateOne) ExecX(ctx context.Context) {
	if err := uguo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uguo *UserGroupUpdateOne) defaults() {
	if _, ok := uguo.mutation.UpdatedAt(); !ok {
		v := usergroup.UpdateDefaultUpdatedAt()
		uguo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uguo *UserGroupUpdateOne) check() error {
	if v, ok := uguo.mutation.Name(); ok {
		if err := usergroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UserGroup.name": %w`, err)}
		}
	}
	return nil
}

func (uguo *UserGroupUpdateOne) sqlSave(ctx context.Context) (_node *UserGroup, err error) {
	if err := uguo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usergroup.Table, usergroup.Columns, sqlgraph.NewFieldSpec(usergroup.FieldID, field.TypeInt64))
	id, ok := uguo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uguo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usergroup.FieldID)
		for _, f := range fields {
			if !usergroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usergroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uguo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uguo.mutation.Name(); ok {
		_spec.SetField(usergroup.FieldName, field.TypeString, value)
	}
	if value, ok := uguo.mutation.Description(); ok {
		_spec.SetField(usergroup.FieldDescription, field.TypeString, value)
	}
	if uguo.mutation.DescriptionCleared() {
		_spec.ClearField(usergroup.FieldDescription, field.TypeString)
	}
	if value, ok := uguo.mutation.MaxSites(); ok {
		_spec.SetField(usergroup.FieldMaxSites, field.TypeInt, value)
	}
	if value, ok := uguo.mutation.AddedMaxSites(); ok {
		_spec.AddField(usergroup.FieldMaxSites, field.TypeInt, value)
	}
	if value, ok := uguo.mutation.MaxMonthlyEvents(); ok {
		_spec.SetField(usergroup.FieldMaxMonthlyEvents, field.TypeInt, value)
	}
	if value, ok := uguo.mutation.AddedMaxMonthlyEvents(); ok {
		_spec.AddField(usergroup.FieldMaxMonthlyEvents, field.TypeInt, value)
	}
	if value, ok := uguo.mutation.MaxAPIKeys(); ok {
		_spec.SetField(usergroup.FieldMaxAPIKeys, field.TypeInt, value)
	}
	if value, ok := uguo.mutation.AddedMaxAPIKeys(); ok {
		_spec.AddField(usergroup.FieldMaxAPIKeys, field.TypeInt, value)
	}
	if value, ok := uguo.mutation.MaxSubAccounts(); ok {
		_spec.SetField(usergroup.FieldMaxSubAccounts, field.TypeInt, value)
	}
	if value, ok := uguo.mutation.AddedMaxSubAccounts(); ok {
		_spec.AddField(usergroup.FieldMaxSubAccounts, field.TypeInt, value)
	}
	if value, ok := uguo.mutation.CustomSearchEngines(); ok {
		_spec.SetField(usergroup.FieldCustomSearchEngines, field.TypeBool, value)
	}
	if value, ok := uguo.mutation.IsDefault(); ok {
		_spec.SetField(usergroup.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := uguo.mutation.Price(); ok {
		_spec.SetField(usergroup.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := uguo.mutation.AddedPrice(); ok {
		_spec.AddField(usergroup.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := uguo.mutation.UpdatedAt(); ok {
		_spec.SetField(usergroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if uguo.mutation.UserConfigsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usergroup.UserConfigsTable,
			Columns: []string{usergroup.UserConfigsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userconfig.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uguo.mutation.RemovedUserConfigsIDs(); len(nodes) > 0 && !uguo.mutation.UserConfigsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usergroup.UserConfigsTable,
			Columns: []string{usergroup.UserConfigsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userconfig.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uguo.mutation.UserConfigsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usergroup.UserConfigsTable,
			Columns: []string{usergroup.UserConfigsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userconfig.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserGroup{config: uguo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uguo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usergroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uguo.mutation.done = true
	return _node, nil
}
