// Code generated by ent, DO NOT EDIT.

package usergroup

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the usergroup type in the database.
	Label = "user_group"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldMaxSites holds the string denoting the max_sites field in the database.
	FieldMaxSites = "max_sites"
	// FieldMaxMonthlyEvents holds the string denoting the max_monthly_events field in the database.
	FieldMaxMonthlyEvents = "max_monthly_events"
	// FieldMaxAPIKeys holds the string denoting the max_api_keys field in the database.
	FieldMaxAPIKeys = "max_api_keys"
	// FieldMaxSubAccounts holds the string denoting the max_sub_accounts field in the database.
	FieldMaxSubAccounts = "max_sub_accounts"
	// FieldCustomSearchEngines holds the string denoting the custom_search_engines field in the database.
	FieldCustomSearchEngines = "custom_search_engines"
	// FieldIsDefault holds the string denoting the is_default field in the database.
	FieldIsDefault = "is_default"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUserConfigs holds the string denoting the user_configs edge name in mutations.
	EdgeUserConfigs = "user_configs"
	// Table holds the table name of the usergroup in the database.
	Table = "user_groups"
	// UserConfigsTable is the table that holds the user_configs relation/edge.
	UserConfigsTable = "user_configs"
	// UserConfigsInverseTable is the table name for the UserConfig entity.
	// It exists in this package in order to avoid circular dependency with the "userconfig" package.
	UserConfigsInverseTable = "user_configs"
	// UserConfigsColumn is the table column denoting the user_configs relation/edge.
	UserConfigsColumn = "group_id"
)

// Columns holds all SQL columns for usergroup fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldMaxSites,
	FieldMaxMonthlyEvents,
	FieldMaxAPIKeys,
	FieldMaxSubAccounts,
	FieldCustomSearchEngines,
	FieldIsDefault,
	FieldPrice,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultMaxSites holds the default value on creation for the "max_sites" field.
	DefaultMaxSites int
	// DefaultMaxMonthlyEvents holds the default value on creation for the "max_monthly_events" field.
	DefaultMaxMonthlyEvents int
	// DefaultMaxAPIKeys holds the default value on creation for the "max_api_keys" field.
	DefaultMaxAPIKeys int
	// DefaultMaxSubAccounts holds the default value on creation for the "max_sub_accounts" field.
	DefaultMaxSubAccounts int
	// DefaultCustomSearchEngines holds the default value on creation for the "custom_search_engines" field.
	DefaultCustomSearchEngines bool
	// DefaultIsDefault holds the default value on creation for the "is_default" field.
	DefaultIsDefault bool
	// DefaultPrice holds the default value on creation for the "price" field.
	DefaultPrice float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the UserGroup queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByMaxSites orders the results by the max_sites field.
func ByMaxSites(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxSites, opts...).ToFunc()
}

// ByMaxMonthlyEvents orders the results by the max_monthly_events field.
func ByMaxMonthlyEvents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxMonthlyEvents, opts...).ToFunc()
}

// ByMaxAPIKeys orders the results by the max_api_keys field.
func ByMaxAPIKeys(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxAPIKeys, opts...).ToFunc()
}

// ByMaxSubAccounts orders the results by the max_sub_accounts field.
func ByMaxSubAccounts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxSubAccounts, opts...).ToFunc()
}

// ByCustomSearchEngines orders the results by the custom_search_engines field.
func ByCustomSearchEngines(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomSearchEngines, opts...).ToFunc()
}

// ByIsDefault orders the results by the is_default field.
func ByIsDefault(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDefault, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserConfigsCount orders the results by user_configs count.
func ByUserConfigsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserConfigsStep(), opts...)
	}
}

// ByUserConfigs orders the results by user_configs terms.
func ByUserConfigs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserConfigsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserConfigsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserConfigsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UserConfigsTable, UserConfigsColumn),
	)
}
