pool_size: 100
app_debug: false
log_level: info
secret_key: "KKfc8Y5Zpn5CE/0P+ce3ptJRRAZJBhbcOHSqoessJ4kLxkEi+S4nNsl6ekj0AxKF"
data_path: "./data"
maxmind_license_key: ""
geoip_mirror: ""
base_url: ""

smtp:
  host: ""
  port: 587
  username: ""
  password: ""
  from: ""

scheme:
  address: 0.0.0.0
  http_port: 8080

clickhouse:
  #  This configuration can be overridden using the environment variable ZENSTATS_CLICKHOUSE_ADDR
  addr:
    - zenstats_events_db:9000 # docker compose service name
  database: zenstats_events_db
  username: default
  password: ""
  ssl: false

db:
  host: zenstats_db # docker compose service name
  port: 5432
  username: postgres
  password: "postgres"
  database: "zenstats"
