// Code generated by ent, DO NOT EDIT.

package monthlyeventcount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldEQ(FieldUserID, v))
}

// Year applies equality check predicate on the "year" field. It's identical to YearEQ.
func Year(v int) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldEQ(FieldYear, v))
}

// Month applies equality check predicate on the "month" field. It's identical to MonthEQ.
func Month(v int) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldEQ(FieldMonth, v))
}

// Count applies equality check predicate on the "count" field. It's identical to CountEQ.
func Count(v int64) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldEQ(FieldCount, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldNotIn(FieldUserID, vs...))
}

// YearEQ applies the EQ predicate on the "year" field.
func YearEQ(v int) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldEQ(FieldYear, v))
}

// YearNEQ applies the NEQ predicate on the "year" field.
func YearNEQ(v int) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldNEQ(FieldYear, v))
}

// YearIn applies the In predicate on the "year" field.
func YearIn(vs ...int) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldIn(FieldYear, vs...))
}

// YearNotIn applies the NotIn predicate on the "year" field.
func YearNotIn(vs ...int) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldNotIn(FieldYear, vs...))
}

// YearGT applies the GT predicate on the "year" field.
func YearGT(v int) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldGT(FieldYear, v))
}

// YearGTE applies the GTE predicate on the "year" field.
func YearGTE(v int) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldGTE(FieldYear, v))
}

// YearLT applies the LT predicate on the "year" field.
func YearLT(v int) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldLT(FieldYear, v))
}

// YearLTE applies the LTE predicate on the "year" field.
func YearLTE(v int) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldLTE(FieldYear, v))
}

// MonthEQ applies the EQ predicate on the "month" field.
func MonthEQ(v int) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldEQ(FieldMonth, v))
}

// MonthNEQ applies the NEQ predicate on the "month" field.
func MonthNEQ(v int) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldNEQ(FieldMonth, v))
}

// MonthIn applies the In predicate on the "month" field.
func MonthIn(vs ...int) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldIn(FieldMonth, vs...))
}

// MonthNotIn applies the NotIn predicate on the "month" field.
func MonthNotIn(vs ...int) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldNotIn(FieldMonth, vs...))
}

// MonthGT applies the GT predicate on the "month" field.
func MonthGT(v int) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldGT(FieldMonth, v))
}

// MonthGTE applies the GTE predicate on the "month" field.
func MonthGTE(v int) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldGTE(FieldMonth, v))
}

// MonthLT applies the LT predicate on the "month" field.
func MonthLT(v int) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldLT(FieldMonth, v))
}

// MonthLTE applies the LTE predicate on the "month" field.
func MonthLTE(v int) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldLTE(FieldMonth, v))
}

// CountEQ applies the EQ predicate on the "count" field.
func CountEQ(v int64) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldEQ(FieldCount, v))
}

// CountNEQ applies the NEQ predicate on the "count" field.
func CountNEQ(v int64) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldNEQ(FieldCount, v))
}

// CountIn applies the In predicate on the "count" field.
func CountIn(vs ...int64) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldIn(FieldCount, vs...))
}

// CountNotIn applies the NotIn predicate on the "count" field.
func CountNotIn(vs ...int64) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldNotIn(FieldCount, vs...))
}

// CountGT applies the GT predicate on the "count" field.
func CountGT(v int64) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldGT(FieldCount, v))
}

// CountGTE applies the GTE predicate on the "count" field.
func CountGTE(v int64) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldGTE(FieldCount, v))
}

// CountLT applies the LT predicate on the "count" field.
func CountLT(v int64) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldLT(FieldCount, v))
}

// CountLTE applies the LTE predicate on the "count" field.
func CountLTE(v int64) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldLTE(FieldCount, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MonthlyEventCount) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MonthlyEventCount) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MonthlyEventCount) predicate.MonthlyEventCount {
	return predicate.MonthlyEventCount(sql.NotPredicates(p))
}
