// Code generated by ent, DO NOT EDIT.

package shieldrulesreferrer

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldLTE(FieldID, id))
}

// SiteID applies equality check predicate on the "site_id" field. It's identical to SiteIDEQ.
func SiteID(v int64) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldEQ(FieldSiteID, v))
}

// Hostname applies equality check predicate on the "hostname" field. It's identical to HostnameEQ.
func Hostname(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldEQ(FieldHostname, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldEQ(FieldAction, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldEQ(FieldDescription, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldEQ(FieldCreatedAt, v))
}

// SiteIDEQ applies the EQ predicate on the "site_id" field.
func SiteIDEQ(v int64) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldEQ(FieldSiteID, v))
}

// SiteIDNEQ applies the NEQ predicate on the "site_id" field.
func SiteIDNEQ(v int64) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldNEQ(FieldSiteID, v))
}

// SiteIDIn applies the In predicate on the "site_id" field.
func SiteIDIn(vs ...int64) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldIn(FieldSiteID, vs...))
}

// SiteIDNotIn applies the NotIn predicate on the "site_id" field.
func SiteIDNotIn(vs ...int64) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldNotIn(FieldSiteID, vs...))
}

// HostnameEQ applies the EQ predicate on the "hostname" field.
func HostnameEQ(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldEQ(FieldHostname, v))
}

// HostnameNEQ applies the NEQ predicate on the "hostname" field.
func HostnameNEQ(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldNEQ(FieldHostname, v))
}

// HostnameIn applies the In predicate on the "hostname" field.
func HostnameIn(vs ...string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldIn(FieldHostname, vs...))
}

// HostnameNotIn applies the NotIn predicate on the "hostname" field.
func HostnameNotIn(vs ...string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldNotIn(FieldHostname, vs...))
}

// HostnameGT applies the GT predicate on the "hostname" field.
func HostnameGT(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldGT(FieldHostname, v))
}

// HostnameGTE applies the GTE predicate on the "hostname" field.
func HostnameGTE(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldGTE(FieldHostname, v))
}

// HostnameLT applies the LT predicate on the "hostname" field.
func HostnameLT(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldLT(FieldHostname, v))
}

// HostnameLTE applies the LTE predicate on the "hostname" field.
func HostnameLTE(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldLTE(FieldHostname, v))
}

// HostnameContains applies the Contains predicate on the "hostname" field.
func HostnameContains(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldContains(FieldHostname, v))
}

// HostnameHasPrefix applies the HasPrefix predicate on the "hostname" field.
func HostnameHasPrefix(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldHasPrefix(FieldHostname, v))
}

// HostnameHasSuffix applies the HasSuffix predicate on the "hostname" field.
func HostnameHasSuffix(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldHasSuffix(FieldHostname, v))
}

// HostnameEqualFold applies the EqualFold predicate on the "hostname" field.
func HostnameEqualFold(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldEqualFold(FieldHostname, v))
}

// HostnameContainsFold applies the ContainsFold predicate on the "hostname" field.
func HostnameContainsFold(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldContainsFold(FieldHostname, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldContainsFold(FieldAction, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldContainsFold(FieldDescription, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.FieldLTE(FieldCreatedAt, v))
}

// HasSite applies the HasEdge predicate on the "site" edge.
func HasSite() predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SiteTable, SiteColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSiteWith applies the HasEdge predicate on the "site" edge with a given conditions (other predicates).
func HasSiteWith(preds ...predicate.Site) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(func(s *sql.Selector) {
		step := newSiteStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ShieldRulesReferrer) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ShieldRulesReferrer) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ShieldRulesReferrer) predicate.ShieldRulesReferrer {
	return predicate.ShieldRulesReferrer(sql.NotPredicates(p))
}
