// Code generated by ent, DO NOT EDIT.

package funnelstep

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/zenstats/zenstats/internal/store/postgresql/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldLTE(FieldID, id))
}

// FunnelID applies equality check predicate on the "funnel_id" field. It's identical to FunnelIDEQ.
func FunnelID(v int64) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldEQ(FieldFunnelID, v))
}

// GoalID applies equality check predicate on the "goal_id" field. It's identical to GoalIDEQ.
func GoalID(v int64) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldEQ(FieldGoalID, v))
}

// StepOrder applies equality check predicate on the "step_order" field. It's identical to StepOrderEQ.
func StepOrder(v int) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldEQ(FieldStepOrder, v))
}

// FunnelIDEQ applies the EQ predicate on the "funnel_id" field.
func FunnelIDEQ(v int64) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldEQ(FieldFunnelID, v))
}

// FunnelIDNEQ applies the NEQ predicate on the "funnel_id" field.
func FunnelIDNEQ(v int64) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldNEQ(FieldFunnelID, v))
}

// FunnelIDIn applies the In predicate on the "funnel_id" field.
func FunnelIDIn(vs ...int64) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldIn(FieldFunnelID, vs...))
}

// FunnelIDNotIn applies the NotIn predicate on the "funnel_id" field.
func FunnelIDNotIn(vs ...int64) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldNotIn(FieldFunnelID, vs...))
}

// GoalIDEQ applies the EQ predicate on the "goal_id" field.
func GoalIDEQ(v int64) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldEQ(FieldGoalID, v))
}

// GoalIDNEQ applies the NEQ predicate on the "goal_id" field.
func GoalIDNEQ(v int64) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldNEQ(FieldGoalID, v))
}

// GoalIDIn applies the In predicate on the "goal_id" field.
func GoalIDIn(vs ...int64) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldIn(FieldGoalID, vs...))
}

// GoalIDNotIn applies the NotIn predicate on the "goal_id" field.
func GoalIDNotIn(vs ...int64) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldNotIn(FieldGoalID, vs...))
}

// StepOrderEQ applies the EQ predicate on the "step_order" field.
func StepOrderEQ(v int) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldEQ(FieldStepOrder, v))
}

// StepOrderNEQ applies the NEQ predicate on the "step_order" field.
func StepOrderNEQ(v int) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldNEQ(FieldStepOrder, v))
}

// StepOrderIn applies the In predicate on the "step_order" field.
func StepOrderIn(vs ...int) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldIn(FieldStepOrder, vs...))
}

// StepOrderNotIn applies the NotIn predicate on the "step_order" field.
func StepOrderNotIn(vs ...int) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldNotIn(FieldStepOrder, vs...))
}

// StepOrderGT applies the GT predicate on the "step_order" field.
func StepOrderGT(v int) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldGT(FieldStepOrder, v))
}

// StepOrderGTE applies the GTE predicate on the "step_order" field.
func StepOrderGTE(v int) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldGTE(FieldStepOrder, v))
}

// StepOrderLT applies the LT predicate on the "step_order" field.
func StepOrderLT(v int) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldLT(FieldStepOrder, v))
}

// StepOrderLTE applies the LTE predicate on the "step_order" field.
func StepOrderLTE(v int) predicate.FunnelStep {
	return predicate.FunnelStep(sql.FieldLTE(FieldStepOrder, v))
}

// HasGoals applies the HasEdge predicate on the "goals" edge.
func HasGoals() predicate.FunnelStep {
	return predicate.FunnelStep(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GoalsTable, GoalsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGoalsWith applies the HasEdge predicate on the "goals" edge with a given conditions (other predicates).
func HasGoalsWith(preds ...predicate.Goal) predicate.FunnelStep {
	return predicate.FunnelStep(func(s *sql.Selector) {
		step := newGoalsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFunnels applies the HasEdge predicate on the "funnels" edge.
func HasFunnels() predicate.FunnelStep {
	return predicate.FunnelStep(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FunnelsTable, FunnelsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFunnelsWith applies the HasEdge predicate on the "funnels" edge with a given conditions (other predicates).
func HasFunnelsWith(preds ...predicate.Funnel) predicate.FunnelStep {
	return predicate.FunnelStep(func(s *sql.Selector) {
		step := newFunnelsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FunnelStep) predicate.FunnelStep {
	return predicate.FunnelStep(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FunnelStep) predicate.FunnelStep {
	return predicate.FunnelStep(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FunnelStep) predicate.FunnelStep {
	return predicate.FunnelStep(sql.NotPredicates(p))
}
